import { z } from "zod"; import { auth } from "@/auth"; import { prisma } from "@/lib/prisma"; import { paymentEnvironment } from "@/lib/payments/razorpay";import{paymentProvider}from"@/lib/payments/provider";
const schema=z.object({productId:z.string().uuid(),attribution:z.record(z.string(),z.string().max(200)).optional()});
 export async function POST(request:Request){const session=await auth();if(!session?.user||session.user.role!=="STUDENT")return Response.json({error:"Unauthorized"},{status:401});
 const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:"Invalid product"},{status:400});
 const products=await prisma.$queryRaw<Array<{id:string;name:string;price_in_paise:number;currency:string}>>`select id,name,price_in_paise,currency from public.products where id=${parsed.data.productId}::uuid and active=true`;const product=products[0];if(!product)return Response.json({error:"Product is unavailable"},{status:404});
 const owned=await prisma.$queryRaw<Array<{owned:boolean}>>`select exists(select 1 from public.entitlements where user_id=${session.user.id}::uuid and product_id=${product.id}::uuid and status='active' and (expires_at is null or expires_at>now())) owned`;if(owned[0]?.owned)return Response.json({error:"You already own this product.",alreadyOwned:true},{status:409});
 const env=paymentEnvironment();let provider;try{provider=paymentProvider()}catch{return Response.json({error:"Payments are not configured"},{status:503})}const reference=`TAKSH-${Date.now()}-${crypto.randomUUID().slice(0,8)}`;let order;try{order=await provider.createOrder({amountInPaise:product.price_in_paise,currency:product.currency,receipt:reference,productId:product.id})}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to create payment order"},{status:502})}
 await prisma.$transaction(async tx=>{await tx.$executeRaw`insert into public.payment_orders(user_id,product_id,internal_order_reference,razorpay_order_id,amount_in_paise,currency,status,attribution_json) values(${session.user.id}::uuid,${product.id}::uuid,${reference},${order.providerOrderId},${product.price_in_paise},${product.currency},'created',${JSON.stringify(parsed.data.attribution||{})}::jsonb)`;await tx.$executeRaw`insert into public.product_events(user_id,event_name,product_id,properties) values(${session.user.id}::uuid,'checkout_started',${product.id}::uuid,${JSON.stringify(parsed.data.attribution||{})}::jsonb)`;await tx.$executeRaw`update public.campaign_attributions set checkout_started_at=coalesce(checkout_started_at,now()) where id=(select id from public.campaign_attributions where user_id=${session.user.id}::uuid order by first_touched_at desc limit 1)`;});
 return Response.json({orderId:order.providerOrderId,amount:product.price_in_paise,currency:product.currency,keyId:env.publicKey||env.keyId,productName:product.name,reference});}
