import { z } from "zod"; import { auth } from "@/auth"; import { prisma } from "@/lib/prisma"; import { paymentEnvironment } from "@/lib/payments/razorpay";
const schema=z.object({planId:z.string().uuid(),attribution:z.record(z.string(),z.string().max(200)).optional()});
export async function POST(request:Request){const session=await auth();if(!session?.user||session.user.role!=="STUDENT")return Response.json({error:"Unauthorized"},{status:401});
 const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:"Invalid plan"},{status:400});
 const plans=await prisma.$queryRaw<Array<{id:string;name:string;price_in_paise:number;currency:string}>>`select id,name,price_in_paise,currency from public.plans where id=${parsed.data.planId}::uuid and active=true`;const plan=plans[0];if(!plan)return Response.json({error:"Plan is unavailable"},{status:404});
 const env=paymentEnvironment();if(!env.keyId||!env.keySecret)return Response.json({error:"Payments are not configured"},{status:503});const reference=`TAKSH-${Date.now()}-${crypto.randomUUID().slice(0,8)}`;
 const provider=await fetch("https://api.razorpay.com/v1/orders",{method:"POST",headers:{Authorization:`Basic ${Buffer.from(`${env.keyId}:${env.keySecret}`).toString("base64")}`,"content-type":"application/json"},body:JSON.stringify({amount:plan.price_in_paise,currency:plan.currency,receipt:reference,notes:{internal_reference:reference}})});const order=await provider.json() as {id?:string;error?:{description?:string}};if(!provider.ok||!order.id)return Response.json({error:order.error?.description||"Unable to create payment order"},{status:502});
 await prisma.$executeRaw`insert into public.payment_orders(user_id,plan_id,internal_order_reference,razorpay_order_id,amount_in_paise,currency,status,attribution_json) values(${session.user.id}::uuid,${plan.id}::uuid,${reference},${order.id},${plan.price_in_paise},${plan.currency},'created',${JSON.stringify(parsed.data.attribution||{})}::jsonb)`;
 return Response.json({orderId:order.id,amount:plan.price_in_paise,currency:plan.currency,keyId:env.publicKey||env.keyId,planName:plan.name,reference});}
