import { z } from "zod"; import { auth } from "@/auth"; import { prisma } from "@/lib/prisma"; import { paymentEnvironment } from "@/lib/payments/razorpay";import{paymentProvider}from"@/lib/payments/provider";import{createPayuRequest}from"@/lib/payments/payu";
const schema=z.object({productId:z.string().uuid(),attribution:z.record(z.string(),z.string().max(200)).optional()});
 export async function POST(request:Request){const session=await auth();if(!session?.user||session.user.role!=="STUDENT")return Response.json({error:"Unauthorized"},{status:401});
 const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:"Invalid product"},{status:400});
 const products=await prisma.$queryRaw<Array<{id:string;name:string;price_in_paise:number;currency:string}>>`select id,name,price_in_paise,currency from public.products where id=${parsed.data.productId}::uuid and active=true`;const product=products[0];if(!product)return Response.json({error:"Product is unavailable"},{status:404});
 const owned=await prisma.$queryRaw<Array<{owned:boolean}>>`select exists(select 1 from public.entitlements where user_id=${session.user.id}::uuid and product_id=${product.id}::uuid and status='active' and (expires_at is null or expires_at>now())) owned`;if(owned[0]?.owned)return Response.json({error:"You already own this product.",alreadyOwned:true},{status:409});
 const reference=`TK${Date.now().toString(36)}${crypto.randomUUID().replaceAll("-","").slice(0,8)}`.slice(0,25),activeProvider=process.env.PAYMENT_PROVIDER?.toLowerCase()==="payu"?"payu":"razorpay";let providerOrderId=reference,checkout:Record<string,unknown>;
 try{if(activeProvider==="payu"){if(product.currency!=="INR")throw new Error("PayU checkout currently supports INR products only");const appUrl=process.env.NEXT_PUBLIC_APP_URL;if(!appUrl||!session.user.email)throw new Error("PayU checkout is not configured");const callback=`${appUrl.replace(/\/$/,"")}/api/payments/payu/callback`,request=createPayuRequest({txnid:reference,amount:(product.price_in_paise/100).toFixed(2),productinfo:product.name,firstname:(session.user.name||"Taksh Learner").slice(0,60),email:session.user.email,surl:callback,furl:callback});checkout={provider:"payu",...request}}else{const env=paymentEnvironment(),provider=paymentProvider(),order=await provider.createOrder({amountInPaise:product.price_in_paise,currency:product.currency,receipt:reference,productId:product.id});providerOrderId=order.providerOrderId;checkout={provider:"razorpay",orderId:providerOrderId,amount:product.price_in_paise,currency:product.currency,keyId:env.publicKey||env.keyId,productName:product.name}}}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to create payment order"},{status:502})}
 await prisma.$transaction(async tx=>{await tx.$executeRaw`insert into public.payment_orders(user_id,product_id,internal_order_reference,provider,provider_order_id,razorpay_order_id,amount_in_paise,currency,status,attribution_json) values(${session.user.id}::uuid,${product.id}::uuid,${reference},${activeProvider},${providerOrderId},${activeProvider==="razorpay"?providerOrderId:null},${product.price_in_paise},${product.currency},'created',${JSON.stringify(parsed.data.attribution||{})}::jsonb)`;await tx.$executeRaw`insert into public.product_events(user_id,event_name,product_id,properties) values(${session.user.id}::uuid,'checkout_started',${product.id}::uuid,${JSON.stringify({...parsed.data.attribution,provider:activeProvider})}::jsonb)`;await tx.$executeRaw`update public.campaign_attributions set checkout_started_at=coalesce(checkout_started_at,now()) where id=(select id from public.campaign_attributions where user_id=${session.user.id}::uuid order by first_touched_at desc limit 1)`;});
 return Response.json({...checkout,reference});}
