import {engineOutputSchema,reportSchema} from "./schemas";
import {interviewProviderConfig} from "./config";

async function chat<T>(messages:Array<{role:"system"|"user"|"assistant";content:string}>,schemaName:string,schema:Record<string,unknown>,parse:(value:unknown)=>T){
 const cfg=interviewProviderConfig();
 const response=await fetch(`${cfg.baseUrl}/chat/completions`,{method:"POST",headers:{authorization:`Bearer ${cfg.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:cfg.chatModel,messages,temperature:.35,max_completion_tokens:1400,reasoning_effort:"low",include_reasoning:false,response_format:{type:"json_schema",json_schema:{name:schemaName,strict:true,schema}}}),signal:AbortSignal.timeout(25000)});
 if(!response.ok)throw new Error(`Interview provider failed (${response.status}).`);
 const payload=await response.json() as {choices?:Array<{message?:{content?:string}}>};
 return parse(JSON.parse(payload.choices?.[0]?.message?.content??"{}"));
}
const engineJson={type:"object",additionalProperties:false,required:["reply","stage","shouldComplete","questionType"],properties:{reply:{type:"string"},stage:{type:"string",enum:["introduction","background","technical","behavioral","candidate_questions","closing"]},shouldComplete:{type:"boolean"},questionType:{type:"string"}}};
export function generateInterviewTurn(input:{role:string;difficulty:string;mode:string;stage:string;remainingSeconds:number;resumeText?:string|null;transcript:string}){
 return chat([{role:"system",content:`You are a professional job interviewer. Ask exactly one concise question per turn. Adapt follow-ups to the candidate answer. Do not reveal scoring or hidden reasoning. Role: ${input.role}. Difficulty: ${input.difficulty}. Mode: ${input.mode}. Current stage: ${input.stage}. Time left: ${input.remainingSeconds}s. Move through introduction, background, technical, behavioral, candidate_questions, closing. Finish when time is nearly over or the interview is complete. Resume context: ${input.resumeText?.slice(0,5000)||"none"}.`},{role:"user",content:input.transcript.slice(-12000)}],"interview_turn",engineJson,value=>engineOutputSchema.parse(value));
}
const reportJson={type:"object",additionalProperties:false,required:["overallScore","scores","strengths","improvements","evidence","summary"],properties:{overallScore:{type:"integer",minimum:0,maximum:100},scores:{type:"object",additionalProperties:false,required:["communication","technical","problemSolving","confidence"],properties:{communication:{type:"integer",minimum:0,maximum:100},technical:{type:"integer",minimum:0,maximum:100},problemSolving:{type:"integer",minimum:0,maximum:100},confidence:{type:"integer",minimum:0,maximum:100}}},strengths:{type:"array",maxItems:5,items:{type:"string"}},improvements:{type:"array",maxItems:5,items:{type:"string"}},evidence:{type:"array",maxItems:8,items:{type:"object",additionalProperties:false,required:["observation","quote"],properties:{observation:{type:"string"},quote:{type:"string"}}}},summary:{type:"string"}}};
export function generateReport(input:{role:string;difficulty:string;transcript:string}){return chat([{role:"system",content:`Evaluate this mock interview for the ${input.role} role at ${input.difficulty} difficulty. Ground every observation only in the transcript. Weighted overall score: communication 30%, technical 30%, problem solving 25%, confidence 15%. Keep quotes short and verbatim.`},{role:"user",content:input.transcript.slice(0,30000)}],"interview_report",reportJson,value=>reportSchema.parse(value))}
export async function transcribeAudio(file:File){const cfg=interviewProviderConfig(),form=new FormData();form.set("file",file,file.name||"answer.webm");form.set("model",cfg.transcriptionModel);form.set("response_format","verbose_json");form.set("language","en");form.set("temperature","0");const response=await fetch(`${cfg.baseUrl}/audio/transcriptions`,{method:"POST",headers:{authorization:`Bearer ${cfg.apiKey}`},body:form,signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`Transcription failed (${response.status}).`);const result=await response.json() as {text?:string;segments?:Array<{avg_logprob?:number}>};const text=result.text?.trim();if(!text)throw new Error("No speech was detected. Please try again.");const logs=result.segments?.map(s=>s.avg_logprob).filter((v):v is number=>typeof v==="number")??[];return{text,confidence:logs.length?Math.max(0,Math.min(1,Math.exp(logs.reduce((a,b)=>a+b,0)/logs.length))):null}}
