import {redirect} from "next/navigation";
import {auth} from "@/auth";
import {prisma} from "@/lib/prisma";
import {DashboardShell} from "@/components/dashboard-shell";
import {ActionFeedbackForm} from "@/components/feedback/action-feedback-form";
import {saveCampaign} from "../actions";

function localDate(value:Date|null){return value?new Date(value.getTime()-value.getTimezoneOffset()*60000).toISOString().slice(0,16):""}
export default async function Campaigns(){
  const session=await auth(); if(!session?.user||session.user.role!=="SUPER_ADMIN") redirect("/login");
  const campaigns=await prisma.$queryRaw<Array<{id:string;name:string;code:string;source:string;starts_at:Date|null;ends_at:Date|null;active:boolean}>>`select id,name,code,source,starts_at,ends_at,active from public.campaigns order by created_at desc`;
  return <DashboardShell {...session.user}><header><h2 className="text-3xl font-semibold">Campaigns</h2><p className="mt-2 text-zinc-400">Create controlled diagnostic links and preserve attribution through registration.</p></header><ActionFeedbackForm action={saveCampaign} successMessage="Campaign created." pendingMessage="Saving campaign…" className="mt-7 grid gap-3 rounded-xl border border-zinc-800 p-5 md:grid-cols-2"><input className="field" name="name" placeholder="Campaign name" required/><input className="field" name="code" placeholder="graduate-trainee-01" required/><input className="field" name="source" placeholder="naukri, instagram, college…" required/><div className="grid grid-cols-2 gap-3"><input className="field" name="startsAt" type="datetime-local"/><input className="field" name="endsAt" type="datetime-local"/></div><label className="text-sm"><input name="active" type="checkbox" defaultChecked/> Active</label><button className="btn-primary">Create campaign</button></ActionFeedbackForm><div className="mt-7 space-y-3">{campaigns.map(campaign=>{const url=`https://takshai.in/assessment/job-readiness?source=${encodeURIComponent(campaign.source)}&campaign=${encodeURIComponent(campaign.code)}`;return <ActionFeedbackForm action={saveCampaign} successMessage={`${campaign.name} updated.`} pendingMessage="Updating campaign…" className="rounded-xl border border-zinc-800 p-5" key={campaign.id}><input type="hidden" name="id" value={campaign.id}/><div className="grid gap-3 md:grid-cols-2"><input className="field" name="name" defaultValue={campaign.name} required/><input className="field" name="code" defaultValue={campaign.code} required/><input className="field" name="source" defaultValue={campaign.source} required/><div className="grid grid-cols-2 gap-3"><input className="field" name="startsAt" type="datetime-local" defaultValue={localDate(campaign.starts_at)}/><input className="field" name="endsAt" type="datetime-local" defaultValue={localDate(campaign.ends_at)}/></div></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><label className="text-sm"><input name="active" type="checkbox" defaultChecked={campaign.active}/> Active</label><div className="flex gap-2"><a className="btn-ghost border border-white/10" href={url} target="_blank" rel="noreferrer">Open link</a><button className="btn-primary">Save campaign</button></div></div><code className="mt-4 block overflow-x-auto rounded-lg bg-black/30 p-3 text-xs text-zinc-400">{url}</code></ActionFeedbackForm>})}</div></DashboardShell>;
}
