import{notFound}from"next/navigation";import{DashboardShell}from"@/components/dashboard-shell";import{requireCollegeAdmin}from"@/lib/admin-scope";import{prisma}from"@/lib/prisma";
export default async function StudentDetail({params}:{params:Promise<{studentId:string}>}){const{studentId}=await params;const{session,institutionId}=await requireCollegeAdmin();const students=await prisma.$queryRaw<Array<{email:string;account_status:string;department:string|null;batch:string|null;roll_number:string|null;current_streak:number|null;xp:bigint}>>`SELECT account.email,role.account_status,department.name department,batch.name batch,membership.roll_number,streak.current_streak,(SELECT coalesce(sum(points),0) FROM public.student_xp_ledger WHERE student_id=role.user_id)::bigint xp FROM public.user_roles role JOIN auth.users account ON account.id=role.user_id LEFT JOIN public.user_academic_memberships membership ON membership.user_id=role.user_id AND membership.active LEFT JOIN public.departments department ON department.id=membership.department_id LEFT JOIN public.academic_batches batch ON batch.id=membership.batch_id LEFT JOIN public.student_streaks streak ON streak.student_id=role.user_id WHERE role.user_id=${studentId}::uuid AND role.institution_id=${institutionId}::uuid AND role.role='STUDENT'`;if(!students[0])notFound();const student=students[0];const[courses,progress,attempts,feedback,activity]=await Promise.all([
prisma.$queryRaw<Array<{course:string;active:boolean;assigned_at:Date}>>`SELECT course,active,assigned_at FROM public.student_course_assignments WHERE student_id=${studentId}::uuid AND institution_id=${institutionId}::uuid ORDER BY assigned_at DESC`,
prisma.$queryRaw<Array<{course:string;completed:bigint;total:bigint}>>`SELECT course,count(*) FILTER(WHERE status='completed')::bigint completed,count(*)::bigint total FROM public.student_content_progress WHERE student_id=${studentId}::uuid GROUP BY course`,
prisma.$queryRaw<Array<{title:string;percentage:number|null;passed:boolean|null;submitted_at:Date|null}>>`SELECT assessment.title,attempt.percentage,attempt.passed,attempt.submitted_at FROM public.assessment_attempts attempt JOIN public.assessments assessment ON assessment.id=attempt.assessment_id WHERE attempt.student_id=${studentId}::uuid AND assessment.institution_id=${institutionId}::uuid ORDER BY attempt.started_at DESC`,
prisma.$queryRaw<Array<{body:string;course:string|null;topic:string|null;created_at:Date}>>`SELECT body,course,topic,created_at FROM public.faculty_feedback WHERE student_id=${studentId}::uuid AND institution_id=${institutionId}::uuid ORDER BY created_at DESC`,
prisma.$queryRaw<Array<{label:string;occurred_at:Date}>>`SELECT 'Lesson activity: '||subtopic label,last_viewed_at occurred_at FROM public.student_content_progress WHERE student_id=${studentId}::uuid AND last_viewed_at IS NOT NULL UNION ALL SELECT 'Assessment submitted: '||assessment.title,attempt.submitted_at FROM public.assessment_attempts attempt JOIN public.assessments assessment ON assessment.id=attempt.assessment_id WHERE attempt.student_id=${studentId}::uuid AND attempt.submitted_at IS NOT NULL ORDER BY occurred_at DESC LIMIT 30`]);
return <DashboardShell {...session.user}><section className="glass-card"><h2 className="text-2xl font-semibold">{student.email}</h2><p className="mt-2 text-zinc-400">{student.roll_number} · {student.department} · {student.batch} · {student.account_status}</p><p className="mt-3">{Number(student.xp)} XP · {student.current_streak??0} day streak</p></section><div className="mt-6 grid gap-6 lg:grid-cols-2"><Panel title="Assigned courses">{courses.map(x=><p key={x.course}>{x.course} · {x.active?"Active":"Revoked"}</p>)}</Panel><Panel title="Course completion">{progress.map(x=><p key={x.course}>{x.course}: {Number(x.completed)}/{Number(x.total)} lessons</p>)}</Panel><Panel title="Assessments">{attempts.map((x,i)=><p key={i}>{x.title}: {x.percentage??0}% · {x.passed?"Passed":"Not passed"}</p>)}</Panel><Panel title="Faculty feedback">{feedback.map((x,i)=><p key={i}>{x.body}<small className="block">{x.course} · {x.created_at.toLocaleDateString()}</small></p>)}</Panel><Panel title="Activity timeline">{activity.map((x,i)=><p key={i}>{x.label}<small className="block">{x.occurred_at.toLocaleString()}</small></p>)}</Panel></div></DashboardShell>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="glass-card"><h3 className="text-lg font-semibold">{title}</h3><div className="mt-4 space-y-3 text-sm text-zinc-300">{children}</div></section>}
