import {redirect} from "next/navigation";
import {auth} from "@/auth";
import {prisma} from "@/lib/prisma";
import {DashboardShell} from "@/components/dashboard-shell";
import {ActionFeedbackForm} from "@/components/feedback/action-feedback-form";
import {saveProduct} from "../actions";

export default async function Products(){
  const session=await auth(); if(!session?.user||session.user.role!=="SUPER_ADMIN") redirect("/login");
  const [products,courses]=await Promise.all([
    prisma.$queryRaw<Array<{id:string;code:string;name:string;description:string;product_type:string;price_in_paise:number;reference_price_in_paise:number|null;active:boolean;campaign_available:boolean;display_order:number;courses:string[]}>>`select product.id,product.code,product.name,product.description,product.product_type,product.price_in_paise,product.reference_price_in_paise,product.active,product.campaign_available,product.display_order,array_remove(array_agg(mapping.course order by mapping.display_order),null) courses from public.products product left join public.product_courses mapping on mapping.product_id=product.id group by product.id order by product.display_order`,
    prisma.$queryRaw<Array<{title:string}>>`select title from public.courses where published order by title`,
  ]);
  return <DashboardShell {...session.user}><header><h2 className="text-3xl font-semibold">Products</h2><p className="mt-2 text-zinc-400">Control pricing, availability, and which courses each product unlocks.</p></header><div className="mt-7 space-y-4">{products.map(product=><ActionFeedbackForm key={product.id} action={saveProduct} successMessage={`${product.name} updated.`} pendingMessage="Saving product…" className="rounded-xl border border-zinc-800 p-5"><input type="hidden" name="id" value={product.id}/><div className="grid gap-3 md:grid-cols-2"><label className="text-sm">Name<input className="field mt-2" name="name" defaultValue={product.name}/></label><label className="text-sm">Code<input className="field mt-2" value={product.code} disabled/></label><label className="text-sm md:col-span-2">Description<textarea className="field mt-2" name="description" defaultValue={product.description}/></label><label className="text-sm">Sale price (₹)<input className="field mt-2" name="price" type="number" min="0" step="1" defaultValue={product.price_in_paise/100}/></label><label className="text-sm">Reference price (₹)<input className="field mt-2" name="referencePrice" type="number" min="0" step="1" defaultValue={product.reference_price_in_paise?product.reference_price_in_paise/100:""}/></label><label className="text-sm">Display order<input className="field mt-2" name="displayOrder" type="number" defaultValue={product.display_order}/></label><div className="flex items-end gap-5 pb-3 text-sm"><label><input name="active" type="checkbox" defaultChecked={product.active}/> Active</label><label><input name="campaignAvailable" type="checkbox" defaultChecked={product.campaign_available}/> Campaign recommendation</label></div></div><fieldset className="mt-4"><legend className="text-sm font-medium">Included courses</legend><div className="mt-2 grid gap-2 md:grid-cols-2">{courses.map(course=><label className="text-sm text-zinc-400" key={course.title}><input name="courses" value={course.title} type="checkbox" defaultChecked={product.courses.includes(course.title)}/> {course.title}</label>)}</div></fieldset><p className="mt-3 text-xs text-zinc-500">{product.product_type} · {product.courses.length} course(s)</p><button className="btn-primary mt-4">Save product</button></ActionFeedbackForm>)}</div></DashboardShell>;
}
