"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Clock3, Loader2 } from "lucide-react";
import Link from "next/link";

type Key="A"|"B"|"C"|"D";
type Question={number:number;id:string;question:string;category:string;subcategory:string;options:Record<Key,string>};
type Payload={attemptId:string;expiresAt:string;serverNow:string;answers:Record<string,Key>;questions:Question[]};
type Result={score:number;total:number;incorrect:number;unanswered:number;timeTakenSeconds:number;paidAccess:boolean;categories:Array<{category:string;correct:number;total:number;percentage:number;label:string}>;analysis:{message:string;recommended:string[]}};
const keys:Key[]=["A","B","C","D"];
const names:Record<string,string>={logical_reasoning:"Logical Reasoning",english_verbal:"English / Verbal",quantitative_aptitude:"Quantitative Aptitude",database_technical:"Database & Technical"};
const formatTime=(s:number)=>`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;

export function SkillDiagnostic(){
 const[data,setData]=useState<Payload>();const[answers,setAnswers]=useState<Record<string,Key>>({});const[index,setIndex]=useState(0);const[remaining,setRemaining]=useState(600);const[loading,setLoading]=useState(true);const[submitting,setSubmitting]=useState(false);const[error,setError]=useState("");const[upgrade,setUpgrade]=useState(false);const[result,setResult]=useState<Result>();const offset=useRef(0),submittingRef=useRef(false);
 const submit=useCallback(async()=>{if(!data||submittingRef.current)return;submittingRef.current=true;setSubmitting(true);const r=await fetch("/api/diagnostic/attempt/submit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({attemptId:data.attemptId})});const x=await r.json();if(r.ok)setResult(x);else setError(x.error||"Unable to submit");setSubmitting(false);submittingRef.current=false},[data]);
 useEffect(()=>{void fetch("/api/diagnostic/attempt",{cache:"no-store"}).then(async r=>{const x=await r.json();if(!r.ok){setUpgrade(Boolean(x.upgradeRequired));throw new Error(x.error)}setData(x);setAnswers(x.answers||{});offset.current=new Date(x.serverNow).getTime()-Date.now();setRemaining(Math.max(0,Math.ceil((new Date(x.expiresAt).getTime()-(Date.now()+offset.current))/1000)))}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 useEffect(()=>{if(!data||result)return;const id=window.setInterval(()=>{const left=Math.max(0,Math.ceil((new Date(data.expiresAt).getTime()-(Date.now()+offset.current))/1000));setRemaining(left);if(left===0){window.clearInterval(id);void submit()}},1000);return()=>window.clearInterval(id)},[data,result,submit]);
 async function choose(q:Question,k:Key){setAnswers(v=>({...v,[q.id]:k}));const r=await fetch("/api/diagnostic/attempt/answer",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({attemptId:data!.attemptId,questionId:q.id,answer:k})});if(!r.ok)setError("That answer could not be saved. Check your connection.")}
 if(loading)return <div className="glass-card flex min-h-80 items-center justify-center"><Loader2 className="size-7 animate-spin"/></div>;
 if(error&&!data)return <div className="glass-card"><h2 className="text-2xl font-semibold">{upgrade?"Improve your placement score":"Diagnostic unavailable"}</h2><p className="mt-3 text-zinc-300">{error}</p>{upgrade&&<><ul className="mt-5 list-disc space-y-2 pl-5 text-zinc-300"><li>60 guided Python, Prompt Engineering and UI/UX lessons</li><li>Logical Reasoning and English placement preparation</li><li>Placement Readiness retest</li></ul><p className="mt-6 text-3xl font-bold">₹499</p><Link className="btn-primary mt-5 inline-flex" href="/pricing">Improve My Score</Link></>}</div>;
 if(result)return <div className="space-y-6"><section className="glass-card"><p className="eyebrow">Taksh AI Skill Analysis</p><h2 className="mt-4 text-4xl font-semibold">Overall Diagnostic Score</h2><p className="mt-4 text-6xl font-bold text-violet-300">{result.score} / {result.total}</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><Stat n={result.incorrect} l="Incorrect"/><Stat n={result.unanswered} l="Unanswered"/><Stat n={formatTime(result.timeTakenSeconds)} l="Time taken"/></div></section><section className="grid gap-4 md:grid-cols-2">{result.categories.map(x=><article className="glass-card" key={x.category}><div className="flex justify-between"><h3 className="font-semibold">{names[x.category]}</h3><b>{x.correct}/{x.total}</b></div><div className="mt-4 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-violet-500" style={{width:`${x.percentage}%`}}/></div><p className="mt-3 text-sm text-zinc-400">{x.label} · {x.percentage}%</p></article>)}</section><section className="glass-card"><h3 className="text-xl font-semibold">Taksh AI analysis</h3><p className="mt-4 leading-7 text-zinc-300">{result.analysis.message}</p><h4 className="mt-6 font-semibold">Recommended Focus</h4><ol className="mt-3 list-decimal space-y-2 pl-5 text-zinc-300">{result.analysis.recommended.map(x=><li key={x}>{x}</li>)}</ol><div className="mt-7 flex flex-wrap gap-3"><Link prefetch={false} className="btn-primary" href="/student/courses">Begin recommended learning</Link>{!result.paidAccess&&<Link prefetch={false} className="btn-primary" href="/pricing">Pay ₹499 and activate</Link>}<Link prefetch={false} className="btn-ghost border border-white/10" href="/dashboard">Dashboard</Link></div></section>{!result.paidAccess&&<section className="glass-card"><h3 className="text-2xl font-semibold">Activate your complete learning path</h3><p className="mt-3 text-zinc-300">Unlock Python, Prompt Engineering, UI/UX, ServiceNow development, Logical Reasoning, English Proficiency and your readiness retest.</p><p className="mt-5 text-3xl font-bold">₹499</p><Link className="btn-primary mt-5 inline-flex" href="/pricing">Pay and activate</Link></section>}</div>;
 const q=data!.questions[index],answered=Object.keys(answers).length;
 return <div className="grid gap-5 lg:grid-cols-[1fr_280px]"><section className="glass-card"><div className="flex items-center justify-between gap-3"><div><p className="eyebrow">Taksh AI Skill Diagnostic</p><h2 className="mt-3 text-2xl font-semibold">Question {index+1} of 10</h2></div><div className={`flex items-center gap-2 rounded-xl border px-4 py-3 font-mono text-xl ${remaining<=60?"border-red-400/30 text-red-200":"border-white/10"}`}><Clock3 className="size-5"/>{formatTime(remaining)}</div></div>{error&&<p role="status" className="mt-4 text-sm text-amber-200">{error}</p>}<p className="mt-7 text-xs text-violet-300">{names[q.category]} · {q.subcategory}</p><h3 className="mt-3 text-xl leading-8">{q.question}</h3><div className="mt-6 grid gap-3">{keys.map(k=><button key={k} onClick={()=>void choose(q,k)} className={`flex gap-3 rounded-2xl border p-4 text-left ${answers[q.id]===k?"border-violet-400 bg-violet-500/15":"border-white/10 bg-black/20"}`}><b>{k}</b><span>{q.options[k]}</span></button>)}</div><div className="mt-7 flex justify-between gap-3"><button className="btn-ghost border border-white/10" disabled={index===0} onClick={()=>setIndex(i=>i-1)}>Previous</button>{index<9?<button className="btn-primary" onClick={()=>setIndex(i=>i+1)}>Next</button>:<button className="btn-primary" disabled={submitting} onClick={()=>void submit()}>{submitting?"Submitting…":"Submit Test"}</button>}</div></section><aside className="glass-card h-fit"><p className="text-sm text-zinc-400">{answered}/10 answered</p><div className="mt-4 grid grid-cols-5 gap-2">{data!.questions.map((x,i)=><button key={x.id} onClick={()=>setIndex(i)} aria-label={`Question ${i+1}`} className={`grid size-10 place-items-center rounded-xl border ${i===index?"border-violet-400 bg-violet-500/20":answers[x.id]?"border-emerald-400/30 bg-emerald-500/10":"border-white/10"}`}>{i+1}</button>)}</div><p className="mt-5 text-xs leading-5 text-zinc-500">Answers save immediately. Refreshing does not reset your test or timer.</p><button className="mt-5 w-full text-sm text-violet-300" disabled={submitting} onClick={()=>void submit()}>Submit Test</button></aside></div>
}
function Stat({n,l}:{n:string|number;l:string}){return <div className="rounded-xl border border-white/10 p-4"><b className="text-xl">{n}</b><p className="mt-1 text-xs text-zinc-500">{l}</p></div>}
