import Link from "next/link";
import { auth } from "@/auth";
import { DashboardShell } from "@/components/dashboard-shell";
import { ActionFeedbackForm } from "@/components/feedback/action-feedback-form";
import { prisma } from "@/lib/prisma";
import { redirect } from "next/navigation";
import { changeSalesRepStatus,inviteSalesRep,promoteSelectedParticipant } from "./actions";

type Rep={id:string;full_name:string;email:string;college:string|null;network_reach:number|null;referral_code:string|null;status:string;visits:bigint;registrations:bigint;paid:bigint;revenue:bigint;refunds:bigint};

export default async function SalesRepManagement({searchParams}:{searchParams:Promise<{q?:string;status?:string}>}){
  const session=await auth();if(!session?.user||session.user.role!=="SUPER_ADMIN")redirect("/login");
  const filters=await searchParams,q=filters.q?.trim()??"",status=filters.status??"";
  const reps=await prisma.$queryRaw<Rep[]>`
    select rep.id,rep.full_name,rep.email,rep.college,rep.network_reach,rep.referral_code,rep.status,
      coalesce(a.visits,0)::bigint visits,coalesce(a.registrations,0)::bigint registrations,
      coalesce(s.paid,0)::bigint paid,coalesce(s.revenue,0)::bigint revenue,coalesce(s.refunds,0)::bigint refunds
    from public.sales_reps rep
    left join lateral(select sum(total_visits) visits,count(*) filter(where registered_user_id is not null) registrations from public.sales_referral_attributions where sales_rep_id=rep.id and validity_status='valid')a on true
    left join lateral(select count(*) filter(where status<>'refunded') paid,coalesce(sum(amount_in_paise-refunded_amount_in_paise),0) revenue,count(*) filter(where status='refunded') refunds from public.referral_sales where sales_rep_id=rep.id)s on true
    where (${q}='' or rep.full_name ilike ${`%${q}%`} or rep.email ilike ${`%${q}%`} or coalesce(rep.referral_code,'') ilike ${`%${q}%`}) and (${status}='' or rep.status=${status})
    order by case rep.status when 'pending' then 0 when 'invited' then 1 else 2 end,rep.created_at desc`;
  const selected=await prisma.$queryRaw<Array<{id:string;display_name:string;email:string}>>`select p.id,p.display_name,u.email from public.sales_challenge_participants p join auth.users u on u.id=p.user_id left join public.sales_reps rep on rep.user_id=p.user_id where p.selection_status='selected' and rep.id is null order by p.selected_at desc`;
  const pending=reps.filter(rep=>rep.status==="pending").length;
  return <DashboardShell {...session.user}><div className="rounded-2xl border border-zinc-200 bg-[#f8f7f3] p-6 text-zinc-950">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-violet-700">Growth operations</p><h2 className="mt-2 text-3xl font-semibold">Sales Reps</h2><p className="mt-2 text-zinc-600">Review applications, manage access and monitor verified performance.</p></div>{pending>0&&<span className="w-fit rounded-full bg-amber-100 px-3 py-1 text-sm font-medium text-amber-800">{pending} pending review</span>}</div>
    <ActionFeedbackForm action={inviteSalesRep} successMessage="Sales Rep invitation created." pendingMessage="Creating invitation…" className="mt-7 grid gap-3 rounded-xl border border-zinc-200 bg-white p-5 md:grid-cols-2 lg:grid-cols-3"><input className="field" name="fullName" placeholder="Full name" required/><input className="field" name="email" type="email" placeholder="Email" required/><input className="field" name="phone" placeholder="Phone (optional)"/><input className="field" name="college" placeholder="College (optional)"/><input className="field" name="city" placeholder="City (optional)"/><button className="btn-primary">Invite Sales Rep</button></ActionFeedbackForm>
    {selected.length>0&&<section className="mt-6 rounded-xl border border-zinc-200 bg-white p-5"><h3 className="font-semibold">Selected challenge participants</h3>{selected.map(row=><ActionFeedbackForm action={promoteSelectedParticipant} successMessage={`${row.display_name} promoted to Sales Rep.`} pendingMessage="Promoting…" className="mt-3 flex items-center justify-between gap-3 border-t border-zinc-100 pt-3" key={row.id}><input type="hidden" name="participantId" value={row.id}/><span><b>{row.display_name}</b><small className="block text-zinc-500">{row.email}</small></span><button className="rounded-lg border border-zinc-300 px-3 py-2 text-sm">Promote</button></ActionFeedbackForm>)}</section>}
    <form className="mt-6 flex flex-wrap gap-3"><input className="field max-w-sm" name="q" placeholder="Search name, email or code" defaultValue={q}/><select className="field max-w-44" name="status" defaultValue={status}><option value="">All statuses</option>{["pending","active","suspended","rejected","invited"].map(value=><option key={value}>{value}</option>)}</select><button className="rounded-lg border border-zinc-300 bg-white px-4">Filter</button></form>
    <section className="mt-5 overflow-hidden rounded-xl border border-zinc-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-zinc-50 text-zinc-500"><tr><th className="p-4">Sales Rep</th><th>Code</th><th>Registrations</th><th>Paid</th><th>Revenue</th><th>Conversion</th><th className="pr-4">Review / access</th></tr></thead><tbody>{reps.map(rep=>{const registrations=Number(rep.registrations),paid=Number(rep.paid),conversion=registrations?paid/registrations*100:0;return <tr className="border-t border-zinc-100" key={rep.id}><td className="p-4"><Link className="font-semibold text-violet-800" href={`/super-admin/sales-reps/${rep.id}`}>{rep.full_name}</Link><small className="block text-zinc-500">{rep.email}{rep.college?` · ${rep.college}`:""}{rep.network_reach?` · reach ${rep.network_reach.toLocaleString("en-IN")}`:""}</small></td><td className="font-mono text-xs">{rep.referral_code??"Assigned on approval"}</td><td>{registrations}</td><td>{paid}</td><td>₹{(Number(rep.revenue)/100).toLocaleString("en-IN")}</td><td>{conversion.toFixed(1)}%</td><td className="pr-4"><ActionFeedbackForm action={changeSalesRepStatus} successMessage={`${rep.full_name} updated.`} pendingMessage="Updating…" className="flex gap-2"><input type="hidden" name="id" value={rep.id}/><select className="rounded-lg border border-zinc-300 px-2 py-1" name="status" defaultValue={rep.status==="active"?"active":rep.status==="rejected"?"rejected":"suspended"}><option value="active">{rep.status==="pending"||rep.status==="invited"?"Approve":"Active"}</option><option value="suspended">Suspend</option><option value="rejected">Reject</option></select><button className="rounded-lg border border-zinc-300 px-2">Save</button></ActionFeedbackForm></td></tr>})}</tbody></table>{!reps.length&&<p className="p-6 text-center text-zinc-500">No Sales Reps match these filters.</p>}</div></section>
  </div></DashboardShell>;
}
