import Link from "next/link";
import { auth } from "@/auth";
import { DashboardShell } from "@/components/dashboard-shell";
import { ActionFeedbackForm } from "@/components/feedback/action-feedback-form";
import { prisma } from "@/lib/prisma";
import { redirect } from "next/navigation";
import { changeSalesRepStatus,inviteSalesRep,promoteSelectedParticipant } from "./actions";

export default async function SalesRepManagement({searchParams}:{searchParams:Promise<{q?:string;status?:string}>}){
 const session=await auth();if(!session?.user||session.user.role!=="SUPER_ADMIN")redirect("/login");
 const filters=await searchParams,q=filters.q?.trim()??"",status=filters.status??"";
 const reps=await prisma.$queryRaw<Array<{id:string;full_name:string;email:string;referral_code:string;status:string;visits:bigint;registrations:bigint;paid:bigint;revenue:bigint;refunds:bigint}>>`
  select rep.id,rep.full_name,rep.email,rep.referral_code,rep.status,coalesce(a.visits,0)::bigint visits,coalesce(a.registrations,0)::bigint registrations,coalesce(s.paid,0)::bigint paid,coalesce(s.revenue,0)::bigint revenue,coalesce(s.refunds,0)::bigint refunds
  from public.sales_reps rep
  left join lateral(select sum(total_visits) visits,count(*) filter(where registered_user_id is not null) registrations from public.sales_referral_attributions where sales_rep_id=rep.id and validity_status='valid')a on true
  left join lateral(select count(*) filter(where status<>'refunded') paid,coalesce(sum(amount_in_paise-refunded_amount_in_paise),0) revenue,count(*) filter(where status='refunded') refunds from public.referral_sales where sales_rep_id=rep.id)s on true
  where (${q}='' or rep.full_name ilike ${`%${q}%`} or rep.email ilike ${`%${q}%`} or rep.referral_code ilike ${`%${q}%`}) and (${status}='' or rep.status=${status}) order by revenue desc,paid desc,rep.created_at desc`;
 const selected=await prisma.$queryRaw<Array<{id:string;display_name:string;email:string}>>`select p.id,p.display_name,u.email from public.sales_challenge_participants p join auth.users u on u.id=p.user_id left join public.sales_reps rep on rep.user_id=p.user_id where p.selection_status='selected' and rep.id is null order by p.selected_at desc`;
 return <DashboardShell {...session.user}><div className="rounded-2xl border border-zinc-200 bg-[#f8f7f3] p-6 text-zinc-950"><p className="text-sm text-violet-700">Growth operations</p><h2 className="mt-2 text-3xl font-semibold">Sales Reps</h2><p className="mt-2 text-zinc-600">Invite approved interns, manage access, and review verified revenue.</p>
 <ActionFeedbackForm action={inviteSalesRep} successMessage="Sales Rep invitation created." pendingMessage="Creating invitation…" className="mt-7 grid gap-3 rounded-xl border border-zinc-200 bg-white p-5 md:grid-cols-2 lg:grid-cols-3"><input className="field" name="fullName" placeholder="Full name" required/><input className="field" name="email" type="email" placeholder="Email" required/><input className="field" name="phone" placeholder="Phone (optional)"/><input className="field" name="college" placeholder="College (optional)"/><input className="field" name="city" placeholder="City (optional)"/><button className="btn-primary">Invite Sales Rep</button></ActionFeedbackForm>
 {selected.length>0&&<section className="mt-6 rounded-xl border border-zinc-200 bg-white p-5"><h3 className="font-semibold">Selected challenge participants</h3>{selected.map(row=><ActionFeedbackForm action={promoteSelectedParticipant} successMessage={`${row.display_name} promoted to Sales Rep.`} pendingMessage="Promoting…" className="mt-3 flex items-center justify-between gap-3 border-t border-zinc-100 pt-3" key={row.id}><input type="hidden" name="participantId" value={row.id}/><span><b>{row.display_name}</b><small className="block text-zinc-500">{row.email}</small></span><button className="rounded-lg border border-zinc-300 px-3 py-2 text-sm">Promote</button></ActionFeedbackForm>)}</section>}
 <form className="mt-6 flex flex-wrap gap-3"><input className="field max-w-sm" name="q" placeholder="Search name, email or code" defaultValue={q}/><select className="field max-w-44" name="status" defaultValue={status}><option value="">All statuses</option>{["invited","active","inactive","suspended"].map(x=><option key={x}>{x}</option>)}</select><button className="rounded-lg border border-zinc-300 bg-white px-4">Filter</button></form>
 <section className="mt-5 overflow-hidden rounded-xl border border-zinc-200 bg-white"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-zinc-50 text-zinc-500"><tr><th className="p-4">Sales Rep</th><th>Code</th><th>Visits</th><th>Registrations</th><th>Paid</th><th>Revenue</th><th>Refunds</th><th className="pr-4">Access</th></tr></thead><tbody>{reps.map(rep=><tr className="border-t border-zinc-100" key={rep.id}><td className="p-4"><Link className="font-semibold text-violet-800" href={`/super-admin/sales-reps/${rep.id}`}>{rep.full_name}</Link><small className="block text-zinc-500">{rep.email}</small></td><td>{rep.referral_code}</td><td>{Number(rep.visits)}</td><td>{Number(rep.registrations)}</td><td>{Number(rep.paid)}</td><td>₹{(Number(rep.revenue)/100).toLocaleString("en-IN")}</td><td>{Number(rep.refunds)}</td><td className="pr-4"><ActionFeedbackForm action={changeSalesRepStatus} successMessage={`${rep.full_name} updated.`} pendingMessage="Updating…" className="flex gap-2"><input type="hidden" name="id" value={rep.id}/><select className="rounded-lg border border-zinc-300 px-2 py-1" name="status" defaultValue={rep.status}>{["active","inactive","suspended"].map(x=><option key={x}>{x}</option>)}</select><button className="rounded-lg border border-zinc-300 px-2">Save</button></ActionFeedbackForm></td></tr>)}</tbody></table></div></section></div></DashboardShell>;
}
