import { auth } from "@/auth";
import { CopyReferralLink } from "@/components/sales/copy-referral-link";
import { SalesPortalShell } from "@/components/sales/sales-portal-shell";
import { prisma } from "@/lib/prisma";
import { challengeAnalytics } from "@/lib/sales-challenge/analytics";
import { headers } from "next/headers";
import { redirect } from "next/navigation";

type Metrics={visits:bigint;registrations:bigint;diagnostics:bigint;paid:bigint;revenue:bigint};
type Activity={id:string;occurred_at:Date;kind:"registration"|"diagnostic"|"payment";label:string;detail:string};

export default async function SalesDashboardPage(){
  const session=await auth();if(!session?.user||session.user.role!=="SALES_REP")redirect("/sales/login");
  const rep=(await prisma.$queryRaw<Array<{id:string;full_name:string;email:string;phone:string|null;college:string|null;city:string|null;network_reach:number|null;referral_code:string|null;status:string;source_participant_id:string|null}>>`select id,full_name,email,phone,college,city,network_reach,referral_code,status,source_participant_id from public.sales_reps where user_id=${session.user.id}::uuid`)[0];
  if(!rep||rep.status!=="active"||!rep.referral_code)redirect("/sales/pending");
  const [metric,sales,activity,challenge]=await Promise.all([
    prisma.$queryRaw<Metrics[]>`select coalesce(sum(total_visits) filter(where validity_status='valid'),0)::bigint visits,count(*) filter(where validity_status='valid' and registered_user_id is not null)::bigint registrations,count(*) filter(where validity_status='valid' and assessment_completed_at is not null)::bigint diagnostics,(select count(*) from public.referral_sales where sales_rep_id=${rep.id}::uuid and status in('confirmed','partially_refunded'))::bigint paid,coalesce((select sum(amount_in_paise-refunded_amount_in_paise) from public.referral_sales where sales_rep_id=${rep.id}::uuid and status in('confirmed','partially_refunded')),0)::bigint revenue from public.sales_referral_attributions where sales_rep_id=${rep.id}::uuid`,
    prisma.$queryRaw<Array<{id:string;paid_at:Date;product:string;amount:number;status:string}>>`select sale.id,sale.paid_at,coalesce(product.name,sale.product_type,'Taksh product') product,sale.amount_in_paise-sale.refunded_amount_in_paise amount,sale.status from public.referral_sales sale left join public.products product on product.id=sale.product_id where sale.sales_rep_id=${rep.id}::uuid order by sale.paid_at desc limit 20`,
    prisma.$queryRaw<Activity[]>`select id,occurred_at,kind,label,detail from((select attribution.id,attribution.registered_at occurred_at,'registration'::text kind,'New registration'::text label,'A referred learner created an account'::text detail from public.sales_referral_attributions attribution where attribution.sales_rep_id=${rep.id}::uuid and attribution.validity_status='valid' and attribution.registered_at is not null) union all (select attribution.id,attribution.assessment_completed_at,'diagnostic','Diagnostic completed','A referred learner completed the diagnostic' from public.sales_referral_attributions attribution where attribution.sales_rep_id=${rep.id}::uuid and attribution.validity_status='valid' and attribution.assessment_completed_at is not null) union all (select sale.id,sale.paid_at,'payment','Verified payment',coalesce(product.name,sale.product_type,'Taksh product') from public.referral_sales sale left join public.products product on product.id=sale.product_id where sale.sales_rep_id=${rep.id}::uuid and sale.status in('confirmed','partially_refunded'))) events order by occurred_at desc limit 15`,
    rep.source_participant_id?prisma.$queryRaw<Array<{challenge_id:string;name:string}>>`select participant.challenge_id,challenge.name from public.sales_challenge_participants participant join public.sales_challenges challenge on challenge.id=participant.challenge_id where participant.id=${rep.source_participant_id}::uuid and challenge.show_participant_leaderboard and challenge.status in('active','completed') limit 1`:Promise.resolve([]),
  ]);
  let challengeRank:{name:string;rank:number;score:number}|null=null;
  if(challenge[0]){const rows=await challengeAnalytics(challenge[0].challenge_id),row=rows?.find(item=>item.participantId===rep.source_participant_id);if(row&&row.rank>0)challengeRank={name:challenge[0].name,rank:row.rank,score:row.finalScore}}
  const values=metric[0],registrations=Number(values.registrations),paid=Number(values.paid),conversion=registrations?paid/registrations*100:0;
  const h=await headers(),host=h.get("x-forwarded-host")??h.get("host")??"takshai.in",protocol=h.get("x-forwarded-proto")??"https",referralUrl=`${protocol}://${host}/r/${rep.referral_code}`;
  const cards=[["Link visits",Number(values.visits).toLocaleString("en-IN")],["Registrations",registrations.toLocaleString("en-IN")],["Paid conversions",paid.toLocaleString("en-IN")],["Revenue generated",`₹${(Number(values.revenue)/100).toLocaleString("en-IN")}`],["Conversion rate",`${conversion.toFixed(1)}%`]];
  return <SalesPortalShell><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 sm:py-12">
    <section id="overview" className="scroll-mt-24"><div className="flex flex-col justify-between gap-4 border-b border-zinc-200 pb-7 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-violet-700">Sales overview</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.035em]">Welcome, {rep.full_name.split(" ")[0]}</h1><p className="mt-2 text-sm text-zinc-600">Performance is calculated from live Taksh records and verified payments.</p></div><span className="sales-status-badge sales-status-active">Active Sales Rep</span></div>
    <div className="mt-7 border border-zinc-200 bg-white p-5 sm:p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-zinc-500">Referral code</p><b className="mt-2 block font-mono text-xl">{rep.referral_code}</b></div><p className="max-w-md text-sm leading-6 text-zinc-500">Share this link with prospective learners. The first valid referral is attributed for 30 days.</p></div><div className="mt-5"><CopyReferralLink url={referralUrl}/></div></div>
    <div className="mt-5 grid border border-zinc-200 bg-zinc-200 sm:grid-cols-2 lg:grid-cols-5">{cards.map(([label,value])=><article className="bg-white p-5" key={label}><p className="text-xs font-medium text-zinc-500">{label}</p><b className="mt-3 block text-2xl font-semibold tracking-tight">{value}</b></article>)}</div></section>
    <section className="mt-10 grid gap-6 lg:grid-cols-[1.3fr_.7fr]" id="referrals"><div className="border border-zinc-200 bg-white"><header className="border-b border-zinc-200 px-5 py-4"><h2 className="font-semibold">Recent referral activity</h2><p className="mt-1 text-xs text-zinc-500">Registrations, diagnostics and verified payments</p></header>{activity.length?<div className="divide-y divide-zinc-100">{activity.map(item=><div className="flex items-start justify-between gap-5 px-5 py-4" key={`${item.kind}-${item.id}-${item.occurred_at.toISOString()}`}><div><b className="text-sm">{item.label}</b><p className="mt-1 text-xs text-zinc-500">{item.detail}</p></div><time className="shrink-0 text-xs text-zinc-500">{item.occurred_at.toLocaleDateString("en-IN",{day:"numeric",month:"short"})}</time></div>)}</div>:<div className="p-8 text-center"><b className="text-sm">No referral activity yet</b><p className="mt-2 text-sm text-zinc-500">Activity will appear when learners use your referral link.</p></div>}</div>
    <aside className="space-y-6"><div className="border border-zinc-200 bg-white p-5" id="challenge"><h2 className="font-semibold">Challenge</h2>{challengeRank?<><p className="mt-5 text-3xl font-semibold">#{challengeRank.rank}</p><p className="mt-1 text-sm text-zinc-600">{challengeRank.name}</p><p className="mt-3 text-xs text-zinc-500">Current score {challengeRank.score.toFixed(1)}</p></>:<p className="mt-4 text-sm leading-6 text-zinc-500">No active ranked challenge is linked to your Sales Rep profile.</p>}</div><div className="border border-zinc-200 bg-white p-5" id="profile"><h2 className="font-semibold">Profile</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-xs text-zinc-500">Email</dt><dd className="mt-1">{rep.email}</dd></div><div><dt className="text-xs text-zinc-500">Organization</dt><dd className="mt-1">{rep.college??"Not provided"}</dd></div><div><dt className="text-xs text-zinc-500">City · Network reach</dt><dd className="mt-1">{rep.city??"Not provided"} · {rep.network_reach?.toLocaleString("en-IN")??"Not provided"}</dd></div></dl></div></aside></section>
    <section className="mt-10 scroll-mt-24 border border-zinc-200 bg-white" id="performance"><header className="border-b border-zinc-200 px-5 py-4"><h2 className="font-semibold">Verified conversions</h2><p className="mt-1 text-xs text-zinc-500">Revenue reflects refunds and excludes unverified payments.</p></header><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-zinc-50 text-xs text-zinc-500"><tr><th className="px-5 py-3 font-medium">Date</th><th className="font-medium">Product</th><th className="font-medium">Net amount</th><th className="pr-5 font-medium">Status</th></tr></thead><tbody>{sales.map(sale=><tr className="border-t border-zinc-100" key={sale.id}><td className="px-5 py-4">{sale.paid_at.toLocaleDateString("en-IN")}</td><td>{sale.product}</td><td>₹{(sale.amount/100).toLocaleString("en-IN")}</td><td className="pr-5 capitalize">{sale.status.replaceAll("_"," ")}</td></tr>)}</tbody></table>{!sales.length&&<div className="p-8 text-center"><b className="text-sm">No verified conversions yet</b><p className="mt-2 text-sm text-zinc-500">Verified purchases attributed to your referral code will appear here.</p></div>}</div></section>
  </div></SalesPortalShell>;
}
