import Link from "next/link";
import { ArrowRight,BarChart3,BookOpen,BrainCircuit,CheckCircle2,Code2,LayoutTemplate,Sparkles,Target } from "lucide-react";

const features=[
  {icon:Target,title:"Placement Readiness Test",text:"Measure logical reasoning, English, quantitative aptitude and technical fundamentals in one focused assessment."},
  {icon:BrainCircuit,title:"Personalised Analysis",text:"See a clear readiness band, category-level performance and the skills that deserve your attention next."},
  {icon:BookOpen,title:"Structured Learning",text:"Follow published, guided lessons with definitions, worked examples, common mistakes, activities and knowledge checks."},
  {icon:BarChart3,title:"Progress Tracking",text:"Continue from where you stopped and see completed lessons against the full course journey."},
  {icon:Code2,title:"Career Starter Skills",text:"Build practical foundations in Python, prompt engineering, UI/UX, ServiceNow development, logical reasoning and English."},
  {icon:CheckCircle2,title:"Readiness Retest",text:"Career Starter learners can prepare, retest and compare improvement instead of practising without direction."},
];

const branches=[
  {emoji:"👨‍💻",name:"Computer Science Engineering",topics:["Programming","Data & Databases","Problem Solving","System Thinking"]},
  {emoji:"💻",name:"Information Technology",topics:["Web Foundations","Database Skills","IT Services","Security Awareness"]},
  {emoji:"🤖",name:"AI & Machine Learning",topics:["Python","Prompt Engineering","AI Workflows","Responsible AI"]},
  {emoji:"📊",name:"Data Science",topics:["Python","Data Reasoning","Statistics Mindset","Communication"]},
  {emoji:"⚡",name:"Electronics & Communication",topics:["Technical Aptitude","Logical Reasoning","Programming Basics","Communication"]},
  {emoji:"🔌",name:"Electrical Engineering",topics:["Technical Aptitude","Analytical Thinking","Programming Basics","Communication"]},
  {emoji:"⚙️",name:"Mechanical Engineering",topics:["Quantitative Skills","Logical Reasoning","Digital Skills","Communication"]},
  {emoji:"🏗️",name:"Civil Engineering",topics:["Quantitative Skills","Problem Solving","Digital Skills","Communication"]},
  {emoji:"✈️",name:"Aeronautical Engineering",topics:["Technical Aptitude","Analytical Thinking","Digital Skills","Communication"]},
  {emoji:"🚗",name:"Automobile Engineering",topics:["Technical Aptitude","Problem Solving","Digital Skills","Communication"]},
];

export default function Home(){return <main className="min-h-screen bg-white text-zinc-950">
  <nav className="sticky top-0 z-20 border-b border-zinc-100 bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Brand/><div className="hidden items-center gap-6 text-sm text-zinc-600 md:flex"><a href="#features">Features</a><a href="#branches">Branches</a><a href="#path">How it works</a><Link href="/pricing">Pricing</Link></div><div className="flex gap-2"><Link className="rounded-xl px-4 py-2 text-sm" href="/login">Sign in</Link><Link className="rounded-xl bg-violet-700 px-4 py-2 text-sm font-semibold text-white" href="/signup?next=/diagnostic">Get started</Link></div></div></nav>

  <section className="relative overflow-hidden bg-gradient-to-br from-violet-50 via-white to-fuchsia-50 px-5 py-20 sm:py-28"><div className="absolute left-1/2 top-0 h-80 w-80 -translate-x-1/2 rounded-full bg-violet-300/20 blur-3xl"/><div className="relative mx-auto max-w-6xl text-center"><p className="inline-flex items-center gap-2 rounded-full border border-violet-200 bg-white px-4 py-2 text-sm font-semibold text-violet-700"><Sparkles className="size-4"/>AI-powered placement preparation</p><h1 className="mx-auto mt-7 max-w-5xl text-5xl font-bold tracking-[-.05em] sm:text-7xl">Get placement ready with a path built around your score.</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-zinc-600">Take the free readiness test, understand your gaps and build practical career skills through detailed, guided learning.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><Link className="inline-flex items-center gap-2 rounded-2xl bg-violet-700 px-6 py-4 font-semibold text-white shadow-xl shadow-violet-200" href="/signup?next=/diagnostic">Take the Free Test <ArrowRight className="size-4"/></Link><Link className="rounded-2xl border border-violet-200 bg-white px-6 py-4 font-semibold text-violet-800" href="/pricing">Explore Career Starter</Link></div><div className="mx-auto mt-12 grid max-w-3xl grid-cols-3 divide-x divide-violet-100 rounded-3xl border border-violet-100 bg-white/80 p-5 shadow-sm"><Stat value="6" label="Published courses"/><Stat value="159" label="Guided lessons"/><Stat value="₹499" label="Career Starter"/></div></div></section>

  <section id="features" className="mx-auto max-w-6xl scroll-mt-24 px-5 py-20"><p className="text-sm font-semibold uppercase tracking-[.18em] text-violet-700">Why Taksh AI?</p><h2 className="mt-3 max-w-2xl text-4xl font-bold tracking-tight">Preparation that connects assessment, learning and progress</h2><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{features.map(({icon:Icon,title,text})=><article className="rounded-3xl border border-violet-100 bg-violet-50/40 p-7" key={title}><span className="grid size-11 place-items-center rounded-2xl bg-violet-700 text-white"><Icon className="size-5"/></span><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-zinc-600">{text}</p></article>)}</div></section>

  <section id="branches" className="scroll-mt-24 bg-zinc-950 px-5 py-20 text-white"><div className="mx-auto max-w-6xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-violet-300">Choose your path</p><h2 className="mt-3 text-4xl font-bold tracking-tight">Placement foundations for every engineering branch</h2><p className="mt-4 max-w-3xl leading-7 text-zinc-400">Your core placement skills travel across disciplines. Start with readiness, reasoning, communication and modern digital skills, then apply them to your chosen engineering career.</p><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{branches.map(branch=><article className="group rounded-3xl border border-white/10 bg-white/[.04] p-6 transition hover:border-violet-400/50 hover:bg-violet-500/10" key={branch.name}><div className="text-3xl">{branch.emoji}</div><h3 className="mt-4 text-lg font-semibold">{branch.name}</h3><div className="mt-4 flex flex-wrap gap-2">{branch.topics.map(topic=><span className="rounded-full border border-white/10 bg-black/20 px-3 py-1 text-xs text-zinc-300" key={topic}>{topic}</span>)}</div><Link className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-violet-300" href="/signup?next=/diagnostic">Check my readiness <ArrowRight className="size-4"/></Link></article>)}</div></div></section>

  <section className="mx-auto max-w-6xl px-5 py-20"><div className="grid gap-5 md:grid-cols-3"><Course icon={Code2} title="Python Fundamentals" text="20 lessons from first program to a tested placement-readiness project."/><Course icon={Sparkles} title="Prompt Engineering" text="20 lessons on context, constraints, examples, evaluation and reliable AI workflows."/><Course icon={LayoutTemplate} title="UI/UX Fundamentals" text="20 lessons spanning research, interaction, visual design, accessibility and portfolio delivery."/></div></section>

  <section id="path" className="bg-violet-50 px-5 py-20"><div className="mx-auto max-w-6xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-violet-700">A clear journey</p><h2 className="mt-3 text-4xl font-bold">How it works</h2><div className="mt-9 grid gap-4 md:grid-cols-5">{["Create your free account","Take the readiness test","Understand your score","Follow guided courses","Retest and measure growth"].map((x,i)=><div className="rounded-2xl border border-violet-100 bg-white p-5" key={x}><b className="text-violet-700">0{i+1}</b><p className="mt-4 text-sm font-medium">{x}</p></div>)}</div><div className="mt-12 rounded-3xl bg-violet-700 p-8 text-white md:flex md:items-center md:justify-between"><div><p className="text-sm text-violet-200">Start with evidence, not guesswork</p><h3 className="mt-2 text-3xl font-bold">Discover your placement readiness today.</h3></div><Link className="mt-6 inline-flex items-center gap-2 rounded-2xl bg-white px-6 py-4 font-semibold text-violet-800 md:mt-0" href="/signup?next=/diagnostic">Take the Free Test <ArrowRight className="size-4"/></Link></div></div></section>

  <footer className="bg-zinc-950 px-5 py-12 text-white"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-8 md:flex-row"><div><Brand dark/><p className="mt-4 max-w-sm text-sm leading-6 text-zinc-400">AI-powered placement readiness and guided career learning for students across India.</p></div><div className="flex flex-wrap gap-x-6 gap-y-3 text-sm text-zinc-400"><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/refund-policy">Refunds</Link><Link href="/contact">Contact</Link><Link href="/pricing">Pricing</Link></div></div><p className="mx-auto mt-10 max-w-6xl border-t border-white/10 pt-6 text-xs leading-5 text-zinc-500">Taksh AI supports learning and employability preparation. It does not guarantee employment, placement, salary or examination results.</p></footer>
</main>}

function Stat({value,label}:{value:string;label:string}){return <div className="px-2"><b className="text-2xl text-violet-800">{value}</b><p className="mt-1 text-xs text-zinc-500">{label}</p></div>}
function Course({icon:Icon,title,text}:{icon:typeof Code2;title:string;text:string}){return <article className="rounded-3xl border border-zinc-200 p-7"><Icon className="size-7 text-violet-700"/><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-zinc-600">{text}</p></article>}
export function Brand({dark=false}:{dark?:boolean}){return <Link href="/" className={`flex items-center gap-2 font-bold ${dark?"text-white":"text-violet-800"}`}><span className="grid size-9 place-items-center rounded-xl bg-violet-700 text-white"><BrainCircuit className="size-5"/></span>Taksh AI</Link>}
