import { auth } from "@/auth"; import { prisma } from "@/lib/prisma";
export async function POST(_:Request,{params}:{params:Promise<{assessmentId:string}>}){const session=await auth();if(!session?.user||session.user.role!=="STUDENT")return Response.json({error:"Unauthorized"},{status:401});const {assessmentId}=await params;
const rows=await prisma.$queryRaw<Array<{assignment_id:string;duration_minutes:number;max_attempts:number;randomize_questions:boolean}>>`
SELECT assignment.id assignment_id,assessment.duration_minutes,assessment.max_attempts,assessment.randomize_questions FROM public.assessments assessment JOIN public.assessment_assignments assignment ON assignment.assessment_id=assessment.id AND assignment.active
LEFT JOIN public.user_academic_memberships membership ON membership.user_id=${session.user.id}::uuid AND membership.active
WHERE assessment.id=${assessmentId}::uuid AND assessment.status='published' AND (assessment.available_from IS NULL OR assessment.available_from<=now()) AND (assessment.available_until IS NULL OR assessment.available_until>=now())
AND (assignment.student_id=${session.user.id}::uuid OR assignment.batch_id=membership.batch_id OR assignment.cohort_id=membership.cohort_id) LIMIT 1`;
if(!rows[0])return Response.json({error:"Assessment is unavailable or unassigned."},{status:403});
try{const result=await prisma.$transaction(async tx=>{const count=await tx.$queryRaw<Array<{count:bigint}>>`SELECT count(*)::bigint count FROM public.assessment_attempts WHERE assessment_id=${assessmentId}::uuid AND student_id=${session.user.id}::uuid AND status<>'expired'`;if(Number(count[0].count)>=rows[0].max_attempts)throw new Error("Attempt limit reached.");
const attempt=await tx.$queryRaw<Array<{id:string;started_at:Date}>>`INSERT INTO public.assessment_attempts(assessment_id,assignment_id,student_id,attempt_number) VALUES(${assessmentId}::uuid,${rows[0].assignment_id}::uuid,${session.user.id}::uuid,${Number(count[0].count)+1}) RETURNING id,started_at`;
const questions=await tx.$queryRaw<Array<{id:string;question:string;option_a:string|null;option_b:string|null;option_c:string|null;option_d:string|null;display_order:number}>>`SELECT bank.id,bank.question,bank.option_a,bank.option_b,bank.option_c,bank.option_d,link.display_order FROM public.assessment_questions link JOIN public.question_bank bank ON bank.id=link.question_id WHERE link.assessment_id=${assessmentId}::uuid ORDER BY CASE WHEN ${rows[0].randomize_questions} THEN random() ELSE link.display_order END`;
return {attemptId:attempt[0].id,startedAt:attempt[0].started_at,durationMinutes:rows[0].duration_minutes,questions:questions.map(q=>({id:q.id,question:q.question,options:{A:q.option_a,B:q.option_b,C:q.option_c,D:q.option_d},displayOrder:q.display_order}))};});return Response.json(result);}catch(error){return Response.json({error:error instanceof Error?error.message:"Attempt could not start."},{status:409});}}
