import Link from "next/link";
import { redirect } from "next/navigation";
import { auth } from "@/auth";
import { DashboardShell } from "@/components/dashboard-shell";
import { prisma } from "@/lib/prisma";

type Candidate={user_id:string;name:string|null;email:string|null;diagnostic_track:string;technical_track:string|null;readiness_status:string;current_score:number|null;verification_status:string;employer_eligible:boolean;employer_sharing_consent:boolean;time_taken_seconds:number|null;source:string|null};
const statuses=["PLACEMENT_READY","VERIFIED_PLACEMENT_READY","VERIFICATION_REQUIRED","NEARLY_READY","DEVELOPMENT_REQUIRED","FOUNDATION_REQUIRED","ASSESSMENT_INVALID","ASSESSMENT_INCOMPLETE","MANUAL_REVIEW"];
export default async function Candidates({searchParams}:{searchParams:Promise<{status?:string;track?:string}>}){
 const session=await auth();if(!session?.user||session.user.role!=="SUPER_ADMIN")redirect("/login");
 const filters=await searchParams;
 const rows=await prisma.$queryRaw<Candidate[]>`select candidate.user_id,profile.full_name name,profile.email,candidate.diagnostic_track,candidate.technical_track,candidate.readiness_status,candidate.current_score,candidate.verification_status,candidate.employer_eligible,candidate.employer_sharing_consent,attempt.time_taken_seconds,attribution.source from public.candidate_readiness candidate left join public.students profile on profile.id=candidate.user_id left join public.diagnostic_attempts attempt on attempt.id=candidate.latest_attempt_id left join lateral(select source from public.campaign_attributions where user_id=candidate.user_id order by first_touched_at desc limit 1) attribution on true where (${filters.status??null}::text is null or candidate.readiness_status=${filters.status??null}) and (${filters.track??null}::text is null or candidate.diagnostic_track=${filters.track??null}) order by candidate.updated_at desc`;
 return <DashboardShell {...session.user}><header><h2 className="text-3xl font-semibold">Candidate pipeline</h2><p className="mt-2 text-zinc-400">Readiness is based on verified assessment evidence, never purchase history.</p></header><form className="mt-6 flex flex-wrap gap-3"><select name="status" defaultValue={filters.status??""} className="rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2"><option value="">All statuses</option>{statuses.map(status=><option key={status}>{status}</option>)}</select><select name="track" defaultValue={filters.track??""} className="rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2"><option value="">All tracks</option><option value="technical">Technical</option><option value="non_technical">Non-Technical</option></select><button className="btn-primary">Filter</button></form><div className="mt-6 overflow-x-auto rounded-xl border border-zinc-800"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-white/[.04] text-zinc-400"><tr>{["Candidate","Track","Score","Duration","Status","Verification","Consent","Eligible","Source"].map(label=><th className="px-4 py-3" key={label}>{label}</th>)}</tr></thead><tbody>{rows.map(row=><tr className="border-t border-zinc-800" key={row.user_id}><td className="px-4 py-3"><Link className="font-medium text-violet-300" href={`/super-admin/candidates/${row.user_id}`}>{row.name||row.email||"Candidate"}</Link><p className="text-xs text-zinc-500">{row.email}</p></td><td className="px-4 py-3"><b>{row.diagnostic_track==="non_technical"?"Non-Technical":"Technical"}</b>{row.diagnostic_track==="technical"&&row.technical_track?<span className="block text-xs text-zinc-500">{row.technical_track}</span>:null}</td><td className="px-4 py-3">{row.current_score??"—"}</td><td className="px-4 py-3">{row.time_taken_seconds?`${Math.round(row.time_taken_seconds/60)} min`:"—"}</td><td className="px-4 py-3">{row.readiness_status.replaceAll("_"," ")}</td><td className="px-4 py-3">{row.verification_status}</td><td className="px-4 py-3">{row.employer_sharing_consent?"Yes":"No"}</td><td className="px-4 py-3">{row.employer_eligible?"Yes":"No"}</td><td className="px-4 py-3">{row.source||"direct"}</td></tr>)}</tbody></table>{rows.length===0?<p className="p-6 text-zinc-400">No candidates match these filters.</p>:null}</div></DashboardShell>;
}
