import type { AuthoredCurriculumItem } from "@/lib/content-factory/authored-curriculum";

type Spec={module:string;title:string;definition:string;example:string;answer:string;tip:string;practice:[string,string,string]};
const make=(course:string,topic:string,s:Spec,index:number):AuthoredCurriculumItem=>({course,module:s.module,topic,subtopic:s.title,definition:s.definition,example:s.example,answer:s.answer,tip:s.tip,difficulty:index<6?"Beginner":"Beginner to intermediate",estimatedMinutes:25,whyItMatters:`${s.title} is a practical foundation used in real ${topic.toLowerCase()} work and entry-level interviews.`,coverage:s.practice,practical:`Complete this activity: ${s.example}`,detailedSections:[
 {title:"Concept in plain language",explanation:s.definition,example:s.example},
 {title:"How to apply it",explanation:`First identify the input and desired outcome. Apply the ${s.title.toLowerCase()} principle in small steps, inspect the result, and revise deliberately.`,example:s.answer},
 {title:"Professional habit",explanation:`Do not stop at a result that merely looks correct. Test assumptions, edge cases and clarity. ${s.tip}`,example:`Explain what you changed, why it works and how you verified it.`}
],keyTerms:[{term:s.title,definition:s.definition,example:s.example}],practiceQuestions:s.practice.map((q,i)=>({question:q,answer:i===0?s.answer:`A strong response applies ${s.title.toLowerCase()}, explains the decision, and verifies the outcome.`,explanation:s.tip}))});

const python:Spec[]=[
 {module:"Getting Started",title:"Python and Your First Program",definition:"Python is a readable, general-purpose programming language that executes instructions in order.",example:"Run print('Hello, Taksh') and change the message.",answer:"The console displays Hello, Taksh.",tip:"Run after every small change.",practice:["What does print('Hello, Taksh') produce?","Why is rapid execution useful while learning?","Write a print statement introducing yourself."]},
 {module:"Getting Started",title:"Variables and Data Types",definition:"A variable names a value; common types include int, float, str and bool.",example:"Create name='Asha', age=20 and eligible=True, then inspect type(age).",answer:"type(age) is int.",tip:"Choose names that describe meaning, not storage.",practice:["What is the type of age=20?","How does '20' differ from 20?","Model a product with three variables."]},
 {module:"Getting Started",title:"Input, Output and Type Conversion",definition:"input reads text from a user, conversion changes it to the type needed for calculation, and output presents the result.",example:"Read two prices with float(input(...)) and print their total.",answer:"Convert both inputs before adding, otherwise strings concatenate.",tip:"Validate input before trusting it.",practice:["Why must numeric input usually be converted?","What can int('3.5') do?","Build a Celsius-to-Fahrenheit converter."]},
 {module:"Getting Started",title:"Operators and Expressions",definition:"Operators combine values using arithmetic, comparison, assignment and Boolean logic; precedence controls evaluation order.",example:"Evaluate (price*quantity)*(1-discount) and compare it with a budget.",answer:"Parentheses make the intended order explicit.",tip:"Use parentheses when human readers could misread precedence.",practice:["What does 2+3*4 evaluate to?","When does and return true?","Write an expression for an average."]},
 {module:"Getting Started",title:"Strings and Text Processing",definition:"A string is an immutable sequence of characters that supports indexing, slicing and transformation methods.",example:"Clean '  Taksh AI  ' with strip(), lower() and replace().",answer:"'taksh ai' after stripping and lowering.",tip:"Store transformed strings because methods do not mutate the original.",practice:["What does 'Python'[0:3] return?","Why does strip not change the source variable?","Normalize a user email."]},
 {module:"Program Flow",title:"Conditional Decisions",definition:"if, elif and else select a path based on mutually understood Boolean conditions.",example:"Classify a score as ready when >=80, almost ready when >=60, otherwise needs preparation.",answer:"Order conditions from the highest threshold downward.",tip:"Test boundary values such as 59, 60, 79 and 80.",practice:["Why should >=80 be checked before >=60?","What is a truthy value?","Write an age eligibility decision."]},
 {module:"Program Flow",title:"For Loops and range",definition:"A for loop processes each item in an iterable; range creates a predictable integer sequence.",example:"Loop through five marks, accumulate the total and calculate the mean.",answer:"Initialize total=0, add each mark, then divide by len(marks).",tip:"Prefer direct iteration when an index is unnecessary.",practice:["What values are in range(1,5)?","When is enumerate useful?","Print the squares from 1 to 10."]},
 {module:"Program Flow",title:"While Loops and Validation",definition:"A while loop repeats while its condition remains true and must make progress toward termination.",example:"Keep asking for a password until it has at least eight characters.",answer:"Update the password inside the loop and exit once valid.",tip:"Identify the exit condition before writing the loop.",practice:["What creates an infinite loop?","When is while better than for?","Build a three-attempt PIN loop."]},
 {module:"Program Flow",title:"Lists and Tuples",definition:"Lists are ordered mutable collections; tuples are ordered immutable collections suited to fixed records.",example:"Add, remove and sort student marks, then represent an RGB colour as a tuple.",answer:"Use a list for changing marks and a tuple for fixed RGB components.",tip:"Choose mutability deliberately.",practice:["How does append differ from extend?","Why use a tuple for coordinates?","Find the highest value in a list."]},
 {module:"Program Flow",title:"Dictionaries and Sets",definition:"Dictionaries map unique keys to values; sets store unique values and support membership and set operations.",example:"Count word frequencies with a dictionary and remove duplicate skills with a set.",answer:"Use counts[word]=counts.get(word,0)+1.",tip:"Use get when a key may not exist.",practice:["What makes a dictionary key suitable?","What does a set remove?","Create a student lookup by email."]},
 {module:"Reusable Programs",title:"Functions and Return Values",definition:"A function packages a named responsibility with parameters and returns a result to its caller.",example:"Write calculate_total(price,quantity,tax_rate=0.18) and test it.",answer:"Return subtotal*(1+tax_rate); do not only print it.",tip:"Keep one function focused on one job.",practice:["How does return differ from print?","What is a default parameter?","Write an is_even function."]},
 {module:"Reusable Programs",title:"Scope and Clean Function Design",definition:"Scope determines where a name is visible; clean functions limit hidden state and make inputs and outputs explicit.",example:"Replace a function that modifies a global total with one that accepts and returns total.",answer:"Explicit input and return value make testing predictable.",tip:"Avoid globals unless the program genuinely needs shared state.",practice:["What is local scope?","Why are pure functions easier to test?","Refactor a global counter."]},
 {module:"Reusable Programs",title:"Errors and Exception Handling",definition:"Exceptions represent runtime failures; try/except handles expected failures without hiding programming defects.",example:"Safely convert user input to int and give a useful message for ValueError.",answer:"Catch ValueError specifically and ask for a whole number.",tip:"Catch the narrowest expected exception.",practice:["When does ValueError occur?","Why avoid bare except?","Handle a missing dictionary key safely."]},
 {module:"Reusable Programs",title:"Files and Context Managers",definition:"Files provide persistent storage; with opens and reliably closes a resource even when work fails.",example:"Read scores.txt, calculate valid scores and write a summary report.",answer:"Use with open(path, encoding='utf-8') as file.",tip:"Treat file format and encoding as part of the contract.",practice:["Why use with open?","How do read and readline differ?","Append one audit entry to a log."]},
 {module:"Reusable Programs",title:"Modules, Packages and Imports",definition:"A module is a Python file; a package groups modules so programs can reuse organized capabilities.",example:"Move validation into validators.py and import its email function.",answer:"from validators import is_valid_email.",tip:"Import dependencies clearly at the top of the module.",practice:["What is a module?","Why avoid from x import *?","Use the standard math module."]},
 {module:"Applied Python",title:"Comprehensions and Data Transformation",definition:"A comprehension builds a collection from iteration, optional filtering and a transformation.",example:"Create normalized emails from non-empty raw values in one readable list comprehension.",answer:"[e.strip().lower() for e in emails if e.strip()].",tip:"Use a normal loop when the logic needs several steps.",practice:["What are the three parts of a comprehension?","When does a comprehension hurt readability?","Build squares of even numbers."]},
 {module:"Applied Python",title:"Classes and Objects",definition:"A class defines shared data and behaviour; each object is an instance with its own state.",example:"Create a Student class with name, completed_lessons and a progress_percent method.",answer:"Store instance state on self and calculate progress from the total.",tip:"Model cohesive behaviour, not every noun as a class.",practice:["What does self represent?","What does __init__ do?","Model a BankAccount deposit method."]},
 {module:"Applied Python",title:"Testing and Debugging",definition:"Testing checks expected behaviour automatically; debugging traces observed behaviour to its cause.",example:"Write assert-based tests for score bands at 39, 40, 59, 60, 79 and 80.",answer:"Boundary tests reveal incorrect comparison operators and ordering.",tip:"Reproduce first, isolate second, fix third, retest last.",practice:["Why test boundaries?","What is a minimal reproduction?","Write two tests for is_even."]},
 {module:"Applied Python",title:"Working with JSON and APIs",definition:"JSON represents structured data; an API exchanges requests and responses under a defined contract.",example:"Parse a JSON student response, check the status and safely read its courses.",answer:"Use json.loads for text and handle missing fields or non-success status.",tip:"Never assume an external response is complete or valid.",practice:["How do JSON objects map to Python?","Why check HTTP status?","Serialize a dictionary to JSON."]},
 {module:"Applied Python",title:"Final Project: Placement Readiness Tracker",definition:"A complete program combines data modelling, functions, validation, files and tests into a usable workflow.",example:"Build a CLI that records scores, calculates a readiness band, saves JSON and displays recommendations.",answer:"A modular tracker with validated input, persistent records and tested score boundaries.",tip:"Plan data and functions before coding the interface.",practice:["Which modules should the tracker contain?","How will you prove saved data reloads?","Add one feature and a test for it."]}
];

const prompt:Spec[]=[
 ["Foundations","How Generative AI Responds","A language model predicts a useful continuation from instructions and context; it does not independently verify truth.","Compare 'Tell me marketing' with 'Explain three digital-marketing channels to a first-year student in 120 words'.","The second prompt gives task, audience, scope and length.","Treat outputs as drafts that require verification."],
 ["Foundations","Anatomy of an Effective Prompt","A dependable prompt states the role or perspective, task, context, constraints, output format and success criteria.","Rewrite 'Make a plan' using all six elements.","Specify the plan's goal, audience, inputs, limits, table format and quality check.","Put the most important instruction where it cannot be missed."],
 ["Foundations","Clear Tasks and Action Verbs","Concrete verbs such as compare, classify, draft and evaluate reduce ambiguity better than vague verbs such as help.","Bad: 'Help with this CV.' Improved: 'Rewrite these four CV bullets using action-result structure without inventing metrics.'","The improved version defines the transformation and truth constraint.","One prompt should have one primary outcome."],
 ["Foundations","Context and Audience","Context supplies facts needed for the task; audience controls vocabulary, depth, tone and assumed knowledge.","Bad: 'Explain APIs.' Improved: 'Explain REST APIs to a non-technical recruiter using a restaurant analogy and one limitation.'","The model can now select the right depth and analogy.","Include relevant context, not an unfiltered data dump."],
 ["Foundations","Constraints and Output Formats","Constraints define boundaries, while a schema, table or template makes an output predictable and reusable.","Ask for three interview questions as JSON with question, skill and difficulty fields.","A defined schema can be validated by software and reviewed consistently.","State units, limits and required fields explicitly."],
 ["Prompt Patterns","Zero-shot and Few-shot Prompting","Zero-shot relies on instructions; few-shot adds representative input-output examples to demonstrate a pattern.","Show two correctly labelled support tickets before asking the model to label a third.","Examples clarify the label definitions and response shape.","Use diverse, correct examples rather than many repetitive ones."],
 ["Prompt Patterns","Decomposition and Stepwise Work","Decomposition splits a complex outcome into smaller, checkable tasks with explicit intermediate deliverables.","Bad: 'Launch my app.' Improved: 'First identify users, then risks, then a two-week launch checklist.'","The sequence reduces omissions and makes each stage reviewable.","Ask for concise reasoning artefacts, not hidden chain-of-thought."],
 ["Prompt Patterns","Delimiters and Source Grounding","Delimiters separate instructions from supplied material; grounding requires answers to use that material and expose missing evidence.","Summarise only text between <source> tags and cite paragraph numbers.","The boundary reduces instruction-data confusion and citations aid verification.","Tell the model what to do when the source is insufficient."],
 ["Prompt Patterns","Tone, Voice and Style","Style instructions define how an answer sounds without changing its factual obligations.","Rewrite a rejection message as warm, direct and professional, under 90 words.","The prompt names three compatible qualities and a length boundary.","Prefer observable style traits over 'make it good'."],
 ["Prompt Patterns","Structured Data Extraction","Extraction prompts identify a schema, normalisation rules, null behaviour and a prohibition against guessing.","Extract candidate name, email and skills from a CV into valid JSON; use null when absent.","The response is machine-readable and missing data is represented honestly.","Validate generated JSON before storing it."],
 ["Reliable Results","Prompt Iteration and Versioning","Prompt engineering is an empirical cycle: define success, test varied inputs, diagnose failures and version deliberate changes.","Compare v1 and v2 against five CVs and record accuracy and unsupported claims.","A test set reveals whether the change generalises beyond one example.","Change one major variable at a time."],
 ["Reliable Results","Evaluation Rubrics","A rubric turns quality into observable criteria with rating anchors, enabling repeatable human or automated review.","Score a cover letter on relevance, evidence, clarity and truthfulness from 1 to 4.","Anchored criteria make feedback more consistent and actionable.","Do not combine unrelated qualities into one score."],
 ["Reliable Results","Hallucinations and Verification","Hallucination is plausible but unsupported output; mitigation uses sources, uncertainty instructions, citations and external checks.","Bad: 'Give current market statistics.' Improved: 'Use only the supplied report; quote table identifiers; say not provided otherwise.'","The evidence boundary prevents invented current figures.","Verify high-impact claims against authoritative sources."],
 ["Reliable Results","Handling Ambiguity and Clarification","When missing information materially changes the outcome, a prompt should require focused clarification before execution.","Ask the assistant to request target role and experience level before rewriting a CV.","Two high-value questions prevent a generic or misleading result.","Do not ask questions whose answers cannot affect the work."],
 ["Reliable Results","Safety, Privacy and Responsible Use","Responsible prompting minimises personal data, blocks harmful use, preserves human oversight and communicates limitations.","Replace real student records with synthetic examples before requesting analysis.","Data minimisation reduces exposure without losing the learning objective.","Never paste secrets, passwords or unnecessary personal data."],
 ["Applied Prompting","Research and Summarisation","A research prompt defines source quality, timeframe, claim-evidence mapping and uncertainty instead of requesting an unsupported overview.","Summarise three supplied reports in a claim/evidence/disagreement table.","The format separates consensus from disagreement and connects claims to sources.","A summary must not be more certain than its sources."],
 ["Applied Prompting","Learning and Tutoring Prompts","A tutoring prompt establishes learner level, learning goal, diagnostic questions, guided practice and feedback without doing all work for the learner.","Tutor me on SQL joins: test me first, explain one gap, give one exercise, then evaluate my attempt.","The sequence adapts teaching to evidence and preserves active practice.","Ask for hints before complete solutions."],
 ["Applied Prompting","Coding and Debugging Prompts","A strong coding prompt supplies environment, expected behaviour, minimal code, actual error and constraints for a verifiable fix.","Bad: 'Code broken.' Improved: include Next.js version, route, stack trace, reproduction and expected response.","Concrete evidence helps isolate the cause and avoids unrelated rewrites.","Remove credentials and reproduce with the smallest case."],
 ["Applied Prompting","Workflow and Template Design","Reusable prompt templates separate stable instructions from named variables and define input validation and output contracts.","Create an interview-feedback template with {{role}}, {{rubric}} and {{notes}} variables.","Stable structure improves consistency while variables preserve reuse.","Document required variables and defaults."],
 ["Applied Prompting","Capstone: A Tested Prompt System","A prompt system combines a reusable template, examples, test cases, rubric, safety rules and a versioned improvement log.","Build and test a CV feedback assistant against normal, incomplete and adversarial inputs.","A complete submission includes the prompt, test set, rubric, results and revisions.","Judge the system by repeatable outcomes, not one impressive output."]
].map(r=>({module:r[0],title:r[1],definition:r[2],example:r[3],answer:r[4],tip:r[5],practice:[`Apply ${r[1]} to a new example.`,`What failure does this technique prevent?`,`Improve the example and explain your change.`] as [string,string,string]}));

const ux:Spec[]=[
 ["UX Foundations","UI, UX and Product Outcomes","UI is the interface people perceive; UX is the end-to-end experience; both serve user needs and measurable product outcomes.","Compare a beautiful checkout that loses cart data with a plain checkout that completes reliably.","The reliable flow has better UX; visual polish alone cannot compensate for task failure.","Connect every design decision to a user and business outcome."],
 ["UX Foundations","Human-centred Design Process","Human-centred design cycles through understanding people, defining problems, exploring solutions, prototyping and testing.","Improve a college application portal by interviewing applicants before redesigning forms.","Research evidence should shape the problem statement before screens are drawn.","Treat the process as iterative, not a one-way sequence."],
 ["UX Foundations","User Research Basics","Research reduces assumptions through appropriate methods such as interviews, observation, surveys and analytics.","Interview five new users about course discovery using neutral, behaviour-focused questions.","Ask about recent actions, not whether they like your proposed feature.","Recruit participants who resemble the actual audience."],
 ["UX Foundations","Personas and Jobs to Be Done","Evidence-based personas describe relevant behaviour; jobs-to-be-done frames the progress a person seeks in a situation.","A commuter hires a learning app to use 20-minute travel windows productively.","The job guides offline access and short lesson design better than demographics alone.","Never invent a persona from stereotypes."],
 ["UX Foundations","Problem Statements and Success Metrics","A problem statement names the user, need, barrier and evidence; metrics define observable improvement.","Students abandon signup because institution codes are unclear; reduce code-related exits from 30% to 10%.","The statement is specific, evidenced and measurable without prescribing a solution.","Measure behaviour and outcome, not only screen delivery."],
 ["Information and Interaction","Information Architecture","Information architecture organises, labels and connects content so users can predict where to find things.","Use card sorting to decide whether certificates belong under Learning, Profile or Achievements.","Participant groupings reveal mental models that can inform navigation.","Use user language rather than internal department names."],
 ["Information and Interaction","User Flows and Task Analysis","A user flow maps states, decisions, system responses and recovery paths required to complete a goal.","Map course purchase from pricing through payment success, failure, retry and entitlement confirmation.","Including failure states prevents a deceptively simple happy-path design.","Every flow needs a clear start, outcome and recovery route."],
 ["Information and Interaction","Interaction Design and Affordances","Interaction design makes available actions perceivable, predictable and responsive through controls, feedback and constraints.","A disabled Submit button explains which required field is missing.","Visible status and guidance help users recover instead of guessing.","Never rely on colour alone to communicate state."],
 ["Information and Interaction","Forms and Error Recovery","Good forms ask only necessary information, group logically, validate at the right time and preserve user input after errors.","Replace 'Invalid input' with 'Password needs at least 8 characters' beside the field.","Specific inline feedback explains how to recover without losing context.","Do not erase completed fields after one validation failure."],
 ["Information and Interaction","Mobile and Responsive Design","Responsive design prioritises content and adapts layout, touch targets and navigation across available space and input methods.","Turn a five-column desktop course table into stacked mobile cards with primary actions visible.","The mobile layout preserves task priority instead of shrinking unusably.","Test real narrow widths and long content, not one device mockup."],
 ["Visual Design","Visual Hierarchy and Layout","Hierarchy uses size, weight, position, spacing and contrast to communicate reading order and importance.","Make the lesson title primary, progress secondary and destructive actions visually quiet.","Users can scan the page and understand what to do next.","If everything is emphasised, nothing is emphasised."],
 ["Visual Design","Typography and Readability","Typography establishes legibility and hierarchy through typeface, size, line height, line length and consistent styles.","Use 16px readable body text, comfortable line height and limited paragraph width for lessons.","The settings reduce visual fatigue and support sustained reading.","Do not use tiny text to force content into a layout."],
 ["Visual Design","Colour and Contrast","Colour supports hierarchy, meaning and identity; sufficient contrast ensures content remains perceivable.","Check button text contrast and pair red error colour with an icon and message.","Contrast and redundant signals support low vision and colour-vision differences.","Use an accessibility contrast checker, not visual guesswork."],
 ["Visual Design","Components and Design Systems","A design system combines reusable components, tokens, patterns and guidance to create consistency at scale.","Define one Button component with documented primary, secondary, disabled and loading states.","Central rules prevent inconsistent one-off buttons and speed implementation.","A component library without usage guidance is incomplete."],
 ["Visual Design","Content Design and Microcopy","Interface writing helps people decide and act through concise labels, instructions, feedback and error messages.","Replace 'OK' with 'Assign course' and explain what happens after confirmation.","Specific labels reduce uncertainty and accidental actions.","Write from the user's task, not the database operation."],
 ["Validation and Delivery","Wireframes and Fidelity","Wireframes explore structure and flow cheaply; higher fidelity adds realistic content, interaction and visual decisions when needed.","Test three dashboard layouts as low-fidelity wireframes before polishing one.","Early comparison keeps teams from overinvesting in the first idea.","Choose fidelity based on the question being tested."],
 ["Validation and Delivery","Prototyping Interactions","A prototype simulates selected states and transitions so a team can test behaviour before full implementation.","Prototype login, first-time password update, error, loading and success states.","Testing state changes exposes gaps that static happy-path screens hide.","Define what the prototype intentionally does not simulate."],
 ["Validation and Delivery","Usability Testing","Usability testing observes representative people attempting realistic tasks and distinguishes evidence from facilitator interpretation.","Ask a participant to assign a course without showing where to click, then note success, time and confusion.","Behaviour reveals discoverability better than asking whether the screen seems easy.","Do not lead participants or teach during the task."],
 ["Validation and Delivery","Accessibility and Inclusive Design","Accessible design supports diverse perception, movement and cognition through semantics, keyboard use, alternatives and understandable content.","Complete course purchase using keyboard only and verify visible focus, labels and error announcements.","The test checks operability and communication, not merely colour contrast.","Accessibility is a design requirement from the start."],
 ["Validation and Delivery","Portfolio Case Study Capstone","A credible case study communicates context, role, evidence, decisions, iterations, outcome and reflection rather than only polished screens.","Document redesign of course assignment with research evidence, flow alternatives, prototype findings and measured outcome.","The narrative demonstrates reasoning, collaboration and learning behind the final design.","Be honest about constraints and distinguish your work from the team's." ]
].map(r=>({module:r[0],title:r[1],definition:r[2],example:r[3],answer:r[4],tip:r[5],practice:[`Perform the activity for ${r[1]}.`,`Name one common mistake and its user impact.`,`Define evidence that would validate the design.`] as [string,string,string]}));

export const careerStarterCurriculum:AuthoredCurriculumItem[]=[
 ...python.map((s,i)=>make("Python Fundamentals","Programming",s,i)),
 ...prompt.map((s,i)=>make("Prompt Engineering Fundamentals","Prompt engineering",s,i)),
 ...ux.map((s,i)=>make("UI/UX Fundamentals","Product design",s,i)),
];
