import type { AuthoredCurriculumItem } from "@/lib/content-factory/authored-curriculum";

export type LaunchModule = {
  title: string;
  skills: string[];
  concept: string;
  workflow: string;
  workplace: string;
  tool: string;
  mistake: string;
  interview: string;
};

export type LaunchCourse = {
  code: string;
  title: string;
  slug: string;
  category: string;
  description: string;
  outcome: string;
  skills: string[];
  modules: LaunchModule[];
};

const m=(title:string,skills:string[],concept:string,workflow:string,workplace:string,tool:string,mistake:string,interview:string):LaunchModule=>({title,skills,concept,workflow,workplace,tool,mistake,interview});

export const launchCourses:LaunchCourse[]=[
  {code:"JFS-001",title:"Java Full Stack",slug:"java-full-stack",category:"Software Development",description:"Build a reliable Java full-stack foundation spanning core language skills, object-oriented design, databases, APIs, frontend integration, testing and deployment.",outcome:"Deliver and explain a tested full-stack application with a Java API, relational persistence, a usable web interface and documented engineering decisions.",skills:["Java","Object-Oriented Programming","Spring Boot","SQL","REST APIs","Web Development","Testing","Git"],modules:[
    m("Java Language Foundations",["Java","Programming Fundamentals"],"Java programs combine statically typed data, expressions, control flow and methods inside a compiled, object-oriented runtime.","Translate a requirement into inputs, typed state, branches, loops and small methods; compile, run and test boundary cases.","Build a command-line fee calculator that validates inputs and applies explicit pricing rules.","JDK, jshell and an IDE","Memorising syntax without tracing state, choosing suitable types or testing invalid input.","Explain Java's compile-and-run process and when to use primitive versus reference types."),
    m("Object-Oriented Design",["Java","Object-Oriented Programming"],"Object-oriented design assigns cohesive responsibilities to objects while protecting invariants through encapsulation and clear collaboration.","Identify domain responsibilities, model state and behaviour, prefer composition, define contracts and test invariants.","Model a course enrolment domain where a learner cannot enrol twice and capacity cannot become negative.","Classes, records, interfaces and collections","Creating inheritance hierarchies for reuse alone or exposing mutable fields publicly.","Compare abstraction, encapsulation, inheritance and polymorphism using one domain example."),
    m("Collections, Exceptions and Files",["Java Collections","Exception Handling","File I/O"],"Collections organise groups of values, exceptions communicate failure, and resource-safe I/O moves data across system boundaries.","Choose a collection by access and uniqueness needs, validate external data, throw meaningful exceptions and close resources deterministically.","Import learner records from CSV, reject malformed rows, remove duplicate IDs and report accepted and rejected counts.","List, Set, Map, try-with-resources and java.nio.file","Catching Exception broadly, ignoring failures or choosing a List when uniqueness is a business rule.","When would you use a Set or Map, and what makes an exception checked or unchecked?"),
    m("Relational Data and Persistence",["SQL","JDBC","Data Modelling"],"Reliable persistence maps domain facts to constrained relational tables and performs parameterised, transactional operations.","Declare table grain and keys, normalise repeated facts, write parameterised queries, control transactions and verify affected rows.","Persist students, courses and enrolments while preventing duplicate enrolment and preserving referential integrity.","PostgreSQL, SQL and JDBC concepts","Concatenating SQL strings, omitting constraints or assuming an ORM removes the need to understand queries.","Explain primary and foreign keys, transaction atomicity and how parameterised queries prevent injection."),
    m("Spring Boot REST APIs",["Spring Boot","REST APIs","Java"],"A REST API exposes resource-oriented operations through HTTP contracts while separating transport, application and persistence responsibilities.","Define resource and status semantics, validate request DTOs, implement service rules, persist safely and return consistent errors.","Create enrolment endpoints that return 201 on creation, 404 for missing resources and 409 for a duplicate enrolment.","Spring Boot, Spring Web and Bean Validation","Putting all logic in controllers, returning 200 for every outcome or exposing persistence entities directly.","Trace an HTTP request through controller, service and repository layers."),
    m("Frontend and API Integration",["HTML","CSS","JavaScript","Web Accessibility"],"A usable frontend represents application state, submits validated requests and communicates loading, success and failure accessibly.","Design semantic structure, collect controlled input, call the API, handle each response state and verify keyboard and screen-reader behaviour.","Build an enrolment screen that prevents duplicate submission and preserves user input after a recoverable server error.","HTML, CSS, browser JavaScript and Fetch API","Treating the happy path as the whole experience or displaying technical server errors directly to users.","How should a frontend distinguish validation, authentication, conflict and server errors?"),
    m("Testing, Security and Observability",["JUnit","Testing","Application Security","Observability"],"Production confidence comes from layered tests, least-privilege controls, safe input handling and diagnostic logs and metrics.","Identify risks, test domain rules and API contracts, authenticate protected actions, avoid secret exposure and log useful context without personal data.","Test duplicate enrolment at unit and integration levels, restrict administrative endpoints and trace a failed request with a correlation ID.","JUnit, Spring Boot Test and structured logging","Testing only getters, storing secrets in source code or logging credentials and tokens.","Differentiate unit, integration and end-to-end tests and name one control for broken access control."),
    m("Delivery and Full-Stack Capstone",["Git","CI/CD","Deployment","Full-Stack Development"],"A deployable application combines reproducible source control, configuration, database migration, automated verification and operational documentation.","Plan thin vertical slices, use reviewable commits, automate checks, externalise configuration, deploy safely and document rollback and limitations.","Deliver a course-enrolment application with a Java API, PostgreSQL, responsive interface, tests, migration and concise README.","Git, CI workflow, container or managed hosting","Submitting disconnected screenshots, committing secrets or deploying without health checks and rollback thinking.","Walk through one engineering trade-off, one failure you tested and the evidence that your system works.")
  ]},
  {code:"DAF-001",title:"Data Analytics Fundamentals",slug:"data-analytics-fundamentals",category:"Data & Analytics",description:"Build an entry-level analytics workflow from business questions and clean data to evidence-based reporting.",outcome:"Complete a portfolio-ready analysis that combines spreadsheet cleaning, SQL summaries, visualisation and a concise stakeholder recommendation.",skills:["Data Analytics","Excel","SQL","Data Cleaning","Data Visualization","Business Reporting"],modules:[
    m("Analytics and Business Questions",["Data Analytics","Business Reporting"],"Analytics converts a decision question into measurable definitions, trustworthy evidence and a recommendation.","Clarify the stakeholder, decision, metric, grain, period and success criterion before opening a tool.","A retail manager asks why repeat purchases fell and needs causes separated from assumptions.","Analysis brief and metric dictionary","Starting with charts before defining the decision and metric.","Explain how you would turn a vague request such as 'analyse sales' into a testable brief."),
    m("Spreadsheet Analysis Foundations",["Excel","Data Analytics"],"A rectangular dataset uses one row per observation and one column per consistently typed variable.","Import data, convert it to a table, validate types, filter records and calculate controlled summaries.","An operations analyst reviews delivery time by courier, city and week without overwriting source data.","Excel tables, formulas and PivotTables","Mixing totals, merged headings and raw records in one analysis range.","When would you use a PivotTable instead of a row-level formula?"),
    m("Data Cleaning and Quality",["Data Cleaning","Excel"],"Cleaning detects and resolves missing, duplicate, inconsistent, invalid and outlying values while preserving an audit trail.","Profile quality, define rules, create cleaned fields, document exceptions and reconcile row counts.","Customer records contain duplicate emails, inconsistent city names and impossible ages.","Excel, Power Query and a cleaning log","Silently deleting inconvenient records or changing raw values without documentation.","How do you decide whether to correct, exclude or retain an outlier?"),
    m("SQL for Analysis",["SQL","Data Analytics"],"SQL filters, joins and aggregates relational data at an explicitly chosen level of detail.","Inspect tables, define join keys, filter early, aggregate deliberately and reconcile totals.","A marketplace combines orders, customers and products to calculate category revenue and repeat rate.","PostgreSQL-compatible SQL","Using a many-to-many join that duplicates revenue without checking row counts.","Explain WHERE versus HAVING and describe a join-validation check."),
    m("Descriptive Analysis",["Data Analytics","Statistics"],"Descriptive analysis uses counts, proportions, central tendency, spread, segments and trends to explain what happened.","Establish a baseline, compare segments, inspect distribution, test sensitivity and state limitations.","An HR analyst compares hiring time across roles without hiding a long tail behind the mean.","Excel or SQL summary tables","Reporting an average without sample size, distribution or relevant comparison.","When is median more useful than mean?"),
    m("Visualisation and Storytelling",["Data Visualization","Business Reporting"],"A useful visual encodes one decision-relevant comparison accurately and pairs it with context and annotation.","Choose the message, select an appropriate chart, remove noise, label evidence and test interpretation.","A weekly dashboard shows target, actual, variance and the operational driver that needs action.","Excel charts or Power BI","Using decorative charts, truncated axes or too many colours that distort comparison.","Choose a chart for trend, ranking and relationship, and justify each choice."),
    m("Reporting and Recommendations",["Business Reporting","Stakeholder Communication"],"An analytics report separates evidence, interpretation, recommendation, owner and expected impact.","Lead with the decision, show decisive evidence, quantify uncertainty and propose a monitored next action.","A churn analysis recommends a targeted onboarding change rather than claiming correlation proves cause.","One-page report and presentation","Listing observations without an accountable action or overstating causality.","How would you communicate an important result that remains uncertain?"),
    m("Analytics Portfolio Project",["Data Analytics","Excel","SQL","Data Visualization"],"A credible portfolio project demonstrates problem framing, reproducible work, validation and business communication.","Select a dataset, write the brief, clean it, analyse it, visualise findings and present a recommendation.","Build a sales-performance case study with a data dictionary, SQL file, dashboard and executive summary.","Excel, SQL and presentation tools","Showing only a polished dashboard without the checks and reasoning behind it.","Walk through one analytical decision, one validation check and one limitation from your project.")
  ]},
  {code:"AEX-001",title:"Advanced Excel for Professionals",slug:"advanced-excel-for-professionals",category:"Workplace Productivity",description:"Use modern Excel confidently for reliable analysis, reporting, automation and workplace decision support.",outcome:"Build a controlled Excel reporting workbook with cleaned inputs, reusable formulas, PivotTables, a dashboard and documented checks.",skills:["Excel","Power Query","PivotTables","Data Validation","Dashboarding","Workplace Productivity"],modules:[
    m("Professional Workbook Design",["Excel","Workplace Productivity"],"A professional workbook separates inputs, calculations, outputs and documentation so another person can audit and reuse it.","Define purpose and owners, structure sheets, use tables and named fields, protect formulas and document assumptions.","A finance tracker has a controlled input sheet, calculation layer, dashboard and read-me tab.","Excel tables, names and protection","Building one crowded sheet with hidden formulas and unexplained hard-coded values.","How would you make a workbook auditable for a colleague?"),
    m("Reliable Formula Logic",["Excel","Spreadsheet Modelling"],"Reliable formulas use appropriate references, explicit error handling and testable intermediate logic.","Define the rule, choose relative or absolute references, calculate, test boundaries and reconcile results.","A commission model applies tiered rates without breaking when copied across months.","IF, IFS, LET, IFERROR and reference types","Hiding genuine data errors with IFERROR or copying formulas with incorrect references.","Explain absolute, relative and mixed references with a practical example."),
    m("Lookup and Matching",["Excel","Data Reconciliation"],"Lookup functions retrieve related values using stable keys and explicit missing-match behaviour.","Clean keys, confirm uniqueness, select exact matching, return controlled defaults and reconcile unmatched rows.","HR joins employee IDs to department and manager data while reporting missing IDs separately.","XLOOKUP, INDEX/MATCH and XMATCH","Using approximate matching accidentally or trusting duplicate lookup keys.","Why is XLOOKUP generally safer than a default VLOOKUP?"),
    m("Dynamic Arrays and Text",["Excel","Data Cleaning"],"Dynamic arrays and text functions transform variable-sized data without fragile copied formulas.","Normalise text, split or combine fields, filter records, create unique lists and sort outputs.","Recruitment data is cleaned into unique skill lists and filtered candidate shortlists.","FILTER, UNIQUE, SORT, TEXTSPLIT and TEXTJOIN","Embedding business logic in unreadable nested formulas without validation.","How do spilled arrays change workbook design?"),
    m("PivotTables and Analysis",["PivotTables","Excel","Data Analytics"],"PivotTables aggregate structured data quickly by dimensions, measures, filters and time groupings.","Validate the source table, choose grain, add measures, compare segments and refresh after source changes.","A sales analyst reports revenue, units and average order value by region and month.","PivotTables, slicers and calculated fields","Counting rows when the business metric requires distinct customers.","What checks should follow a PivotTable refresh?"),
    m("Power Query",["Power Query","Data Cleaning"],"Power Query records repeatable import and transformation steps instead of manual copy-paste cleaning.","Connect, profile, type, clean, merge or append, validate and load only the required result.","Monthly files from a folder are combined into one refreshable operations table.","Excel Power Query","Applying manual fixes after refresh or changing column types too late.","Differentiate merge and append with workplace examples."),
    m("Dashboards and Controls",["Dashboarding","Excel","Data Visualization"],"An Excel dashboard combines a small set of decision metrics, comparisons and filters with controlled inputs.","Define users and questions, build a clean data model, create measures, design visuals and test filters.","A service dashboard tracks volume, turnaround, backlog and SLA breaches with owner-level filters.","Charts, PivotCharts, slicers and validation lists","Packing every available metric onto one screen without hierarchy.","How do you select KPIs for a dashboard?"),
    m("Automation and Capstone",["Excel","Automation","Quality Assurance"],"Safe spreadsheet automation removes repetitive work while preserving validation, transparency and recovery.","Identify a stable repetitive task, standardise inputs, automate refresh or actions, log results and test failures.","Deliver a monthly management reporting pack with refresh instructions and reconciliation checks.","Power Query, Office Scripts or recorded macros","Automating an unstable process before standardising it or enabling unsafe macros blindly.","Describe how you would test and hand over an automated workbook.")
  ]},
  {code:"SQL-001",title:"SQL & Database Fundamentals",slug:"sql-database-fundamentals",category:"Data & Technology",description:"Learn relational database thinking and write trustworthy SQL for entry-level development, analysis and interview tasks.",outcome:"Design a small relational model and answer workplace questions with validated SQL queries, joins, aggregates and transactions.",skills:["SQL","Databases","PostgreSQL","Data Modelling","Joins","Query Optimisation"],modules:[
    m("Relational Database Foundations",["Databases","SQL"],"A relational database stores typed facts in related tables with keys and constraints that protect meaning.","Identify entities, attributes, identifiers and relationships before writing queries.","An LMS separates students, courses, assignments and progress instead of repeating everything in one sheet.","PostgreSQL schema browser","Treating a database as unrelated spreadsheets without keys or rules.","Explain primary keys, foreign keys and referential integrity."),
    m("SELECT and Filtering",["SQL","PostgreSQL"],"SELECT projects required columns while WHERE restricts rows using explicit predicates and null-aware logic.","Inspect columns, select only what is needed, apply predicates, test nulls and order deterministic output.","Support retrieves open payment issues created this week for a specific provider.","SELECT, WHERE, ORDER BY and LIMIT","Using SELECT * in production or comparing NULL with equals.","What is SQL's three-valued logic and why does IS NULL matter?"),
    m("Expressions and Functions",["SQL","Data Transformation"],"SQL expressions derive controlled values using arithmetic, text, date, conditional and null-handling functions.","Define the expected type, calculate a field, handle nulls, label it clearly and test boundaries.","A report derives ageing bands from ticket creation dates and a consistent reporting timestamp.","CASE, COALESCE and date functions","Mixing data types implicitly or using the current time inconsistently across a report.","Compare CASE and COALESCE use cases."),
    m("Aggregations and Grouping",["SQL","Data Analytics"],"Aggregate queries summarise rows at a declared grouping grain using measures such as count, sum and average.","State one output row's meaning, group dimensions, calculate measures, filter groups and reconcile totals.","A product report calculates paid orders and revenue by month and programme.","GROUP BY, aggregate functions and HAVING","Selecting non-grouped columns or confusing row count with distinct customer count.","Explain WHERE versus HAVING with an example."),
    m("Joins",["SQL","Joins","Data Modelling"],"Joins combine related tables through keys; result cardinality depends on one-to-one, one-to-many or many-to-many relationships.","Define the required rows, inspect key uniqueness, choose join type, join, then compare row counts and totals.","Orders join customers and line items while preserving order-level and item-level measures correctly.","INNER, LEFT and self joins","Creating duplicate measures through an unchecked many-to-many join.","How do you diagnose unexpected duplicates after a join?"),
    m("Subqueries, CTEs and Window Functions",["SQL","Window Functions"],"CTEs clarify staged logic and window functions calculate across related rows without collapsing them.","Break the question into named stages, validate each stage, then add ranking, running or comparative calculations.","Rank salespeople within region and compare each month's revenue with the previous month.","WITH, ROW_NUMBER, RANK, LAG and SUM OVER","Using a complex one-line query that cannot be tested stage by stage.","How does GROUP BY differ from a window function?"),
    m("Data Changes and Transactions",["SQL","Transactions","Data Integrity"],"INSERT, UPDATE and DELETE change data; transactions make related changes succeed or fail as one controlled unit.","Preview target rows, begin a transaction, make constrained changes, validate, then commit or roll back.","Activating a payment and entitlement must not leave only one record updated after a failure.","Transactions and constraints","Running broad UPDATE or DELETE statements without a WHERE preview or rollback plan.","Explain atomicity using a business transaction."),
    m("Performance, Security and Project",["Query Optimisation","Database Security","SQL"],"Reliable SQL balances correct results, appropriate indexes, least privilege and observable query performance.","Create a small schema, seed realistic data, write report queries, inspect plans and document security assumptions.","Build a support-ticket database and management report with ownership controls and tested queries.","EXPLAIN, indexes and database roles","Adding indexes to every column or exposing privileged credentials in application code.","When can an index slow a system, and how do you verify benefit?")
  ]},
  {code:"PBI-001",title:"Power BI Fundamentals",slug:"power-bi-fundamentals",category:"Data & Analytics",description:"Create trustworthy Power BI models, DAX measures and decision-focused dashboards from practical business data.",outcome:"Publish a portfolio dashboard backed by a star schema, refreshable Power Query steps, validated DAX and a stakeholder narrative.",skills:["Power BI","Power Query","DAX","Data Modelling","Data Visualization","Business Intelligence"],modules:[
    m("Business Intelligence Foundations",["Business Intelligence","Power BI"],"Business intelligence connects governed data, reusable metrics and interactive reporting to recurring decisions.","Define the audience, decision, metric ownership, refresh need and access boundary before designing visuals.","A college placement team monitors applications, interviews, offers and conversion by cohort.","Power BI Desktop","Starting from a visual idea instead of the decision and metric definitions.","How is a BI dashboard different from a one-time analysis?"),
    m("Getting Data",["Power BI","Data Connections"],"Power BI connects to files, databases and services while preserving source lineage and refresh requirements.","Choose the source, understand credentials and privacy, select tables, limit unnecessary data and test refresh.","A dashboard combines an approved SQL view with a controlled target spreadsheet.","Get Data and data-source settings","Importing personal copies of files whose location and ownership will change.","Compare Import and DirectQuery at a beginner level."),
    m("Power Query Transformation",["Power Query","Data Cleaning"],"Power Query creates a recorded, refreshable transformation pipeline before data enters the model.","Profile columns, set types early, clean values, merge or append, validate counts and name steps clearly.","Folder-based monthly sales files refresh into a standard fact table.","Power Query Editor","Relying on manual source fixes that disappear or break during refresh.","Why should data types be set deliberately in Power Query?"),
    m("Data Modelling",["Data Modelling","Power BI","Star Schema"],"A star schema connects event-level fact tables to descriptive dimensions through stable one-to-many relationships.","Declare grain, separate facts and dimensions, create a date table, set relationships and hide technical keys.","Sales facts link to date, customer, product and region dimensions.","Model view","Building many bidirectional relationships that create ambiguous filters.","Explain fact table grain and why it matters."),
    m("DAX Measures",["DAX","Power BI"],"DAX measures evaluate dynamically in filter context and should encode reusable business definitions.","Write a base measure, verify totals, modify context deliberately and test it across slicers.","Revenue, prior-year revenue and growth percentage respond correctly to date and region filters.","CALCULATE, DIVIDE and time-intelligence functions","Writing calculated columns for every metric or ignoring filter context.","Explain measure versus calculated column."),
    m("Visual Design and Interaction",["Data Visualization","Power BI"],"Power BI visuals should make comparison accurate, interaction predictable and exceptions easy to investigate.","Match chart to question, establish hierarchy, configure tooltips and drill-through, then test every filter state.","Executives see KPIs and trend; managers drill into region and product drivers.","Visuals, slicers, bookmarks and drill-through","Using too many visuals, colours or interactions without a clear reading path.","Which visual would you use for trend, ranking and target variance?"),
    m("Validation, Refresh and Sharing",["Power BI","Data Quality","Governance"],"A dashboard is trustworthy only when measures reconcile, refresh succeeds and access matches business policy.","Reconcile source totals, test edge filters, configure refresh, document ownership and verify workspace permissions.","A published report refreshes daily and restricts managers to authorised regions.","Power BI Service, gateways and workspaces","Publishing before validating totals or granting broad workspace access for convenience.","Describe your pre-publication validation checklist."),
    m("Dashboard Capstone",["Power BI","DAX","Data Storytelling"],"A portfolio dashboard demonstrates business framing, transformation, modelling, DAX, visual design and communication.","Build the brief, transform data, model it, create measures, design pages, validate and present recommendations.","Create a sales or placement dashboard with an executive page and a diagnostic detail page.","Power BI Desktop and Service","Showing screenshots without explaining data model, measure logic or decisions enabled.","Walk through one DAX measure and one design trade-off from your dashboard.")
  ]},
  {code:"SQA-001",title:"Software Testing & QA Fundamentals",slug:"software-testing-qa-fundamentals",category:"Software Quality",description:"Develop practical manual-testing skills across requirements, test cases, defects, Jira, APIs and release quality.",outcome:"Produce a job-ready QA portfolio containing a test plan, traceability, test cases, defect reports, API checks and a release summary.",skills:["Software Testing","Quality Assurance","Test Cases","Defect Management","Jira","API Testing"],modules:[
    m("Quality and SDLC",["Quality Assurance","SDLC"],"Software quality is fitness for agreed needs; testing provides evidence about behaviour and risk throughout the development lifecycle.","Review objectives and risks early, define test involvement by lifecycle stage and maintain traceability to outcomes.","A tester challenges unclear payment requirements before code is built.","Requirements, risk register and lifecycle models","Treating testing as a final phase that only checks whether screens open.","Differentiate quality assurance, quality control and testing."),
    m("STLC and Test Planning",["STLC","Test Planning"],"The software testing lifecycle structures requirement analysis, planning, design, environment, execution, closure and learning.","Assess scope and risk, estimate work, define entry and exit criteria, plan data and environments, then report evidence.","A release test plan prioritises checkout, entitlement and refund paths over decorative changes.","Test plan and risk matrix","Writing a generic plan without scope, dependencies, responsibilities or exit criteria.","What should influence test priority when time is limited?"),
    m("Test Scenarios and Cases",["Test Cases","Test Design"],"A good test case has a clear objective, preconditions, controlled data, reproducible steps and an observable expected result.","Derive scenarios from requirements and risks, apply design techniques, review coverage and maintain traceability.","Signup tests cover valid, invalid, boundary, duplicate and interrupted flows.","Test-case repository and traceability matrix","Writing many repetitive happy-path cases while missing boundaries and state transitions.","Turn a password rule into positive, negative and boundary tests."),
    m("Defect Management",["Defect Management","Jira"],"A useful defect report helps a team reproduce, assess and resolve a gap using evidence and business impact.","Reproduce, isolate, capture environment and data, write steps and expected versus actual, assign severity, then verify the fix.","A payment succeeds but course access is missing; the report includes order reference and API evidence without secrets.","Jira and screen/network evidence","Using vague titles, confusing priority with severity or omitting reproducible data.","Explain severity versus priority with examples."),
    m("Web and Mobile Testing",["Web Testing","Mobile Testing"],"Client applications must be tested across functional states, browsers, devices, accessibility, performance and unreliable networks.","Map states, test responsive and keyboard behaviour, vary browser and network, inspect errors and retest recovery.","A course lesson is tested on narrow screens, keyboard navigation and interrupted progress saving.","Browser developer tools and device emulation","Testing only the developer's browser and one happy path.","What additional risks appear on mobile or slow networks?"),
    m("API Testing Basics",["API Testing","HTTP","Postman"],"API testing verifies request contracts, authentication, status, response schema, business rules and side effects independently of the UI.","Read the contract, build valid and invalid requests, inspect status and body, verify data changes and protect credentials.","Test a support-ticket POST for authentication, validation, success and database persistence.","Postman or an API client","Checking only HTTP 200 and ignoring response data or downstream state.","What should be validated beyond an API status code?"),
    m("Agile QA and Regression",["Agile","Regression Testing","Jira"],"Agile QA collaborates throughout refinement, delivery and review while maintaining risk-based regression coverage.","Clarify acceptance criteria, identify impacted areas, test within the story, update regression and communicate residual risk.","A new fullscreen assessment rule triggers tests for submission, resume, mobile support and existing timers.","Jira boards, acceptance criteria and regression suite","Automating or rerunning every test without impact analysis and maintenance value.","How do you select tests for a regression suite?"),
    m("QA Portfolio Project",["Software Testing","Jira","API Testing"],"A QA portfolio should demonstrate analysis, design, evidence, communication and release judgement, not only a list of cases.","Choose an application, analyse requirements, plan risk, design and execute tests, report defects, test an API and write closure.","Test an LMS purchase-to-learning journey and present coverage, defects and release recommendation.","Jira, spreadsheet and API client","Claiming full coverage without traceability, results or unresolved-risk discussion.","Present the most valuable defect you found and how your evidence accelerated resolution.")
  ]},
  {code:"BAF-001",title:"Business Analysis Fundamentals",slug:"business-analysis-fundamentals",category:"Business & Operations",description:"Learn practical business analysis from stakeholder discovery and requirements to user stories, process maps and solution validation.",outcome:"Create a BA portfolio pack containing a problem brief, stakeholder map, process model, requirements, stories and acceptance evidence.",skills:["Business Analysis","Requirements","BRD","FRD","User Stories","Agile","Jira","Process Mapping"],modules:[
    m("BA Role and Problem Framing",["Business Analysis","Problem Framing"],"Business analysis defines the real need, expected value, constraints and change impact before committing to a solution.","Clarify current state, problem evidence, affected users, desired outcome, scope and measurable value.","A college asks for 'an app' when the actual problem is delayed and inconsistent student onboarding.","Problem statement and business case","Accepting a requested feature as the problem without examining evidence or alternatives.","How does a business need differ from a proposed solution?"),
    m("Stakeholders and Elicitation",["Stakeholder Management","Requirements"],"Stakeholder analysis identifies influence, needs and decision rights; elicitation gathers evidence through suitable collaborative methods.","Map stakeholders, plan questions, conduct interviews or workshops, observe work and confirm findings.","Students, faculty, administrators and finance have different needs in a course-assignment process.","Stakeholder map, interview guide and workshop notes","Asking leading questions or treating the loudest stakeholder as the only source of truth.","Which elicitation technique would you choose for conflicting requirements and why?"),
    m("Requirements Documentation",["Requirements","BRD","FRD"],"Requirements describe business outcomes, user capabilities, system behaviour, data, rules and quality constraints at appropriate detail.","Classify, write clearly, assign identifiers, define acceptance, trace to goals and obtain review decisions.","A BRD explains the onboarding outcome; functional requirements define invitation, password and role behaviour.","BRD, FRD and requirements catalogue","Writing ambiguous words such as fast or user-friendly without measurable criteria.","Differentiate business, stakeholder, functional and non-functional requirements."),
    m("Process Mapping",["Process Mapping","BPMN"],"A process model shows actors, events, activities, decisions, handoffs, data and exceptions in the current or future state.","Set boundaries, observe reality, map the as-is flow, expose pain points, design to-be options and validate with participants.","Map student support from request submission through triage, response and resolution.","Flowcharts, swimlanes and BPMN basics","Drawing the assumed process without exceptions, owners or stakeholder validation.","When is a swimlane diagram particularly useful?"),
    m("Data and Business Rules",["Data Analysis","Business Rules"],"A BA defines key information, ownership, validation and decision rules so the solution behaves consistently.","Identify entities and fields, define sources and quality, document rules as testable statements and resolve conflicts.","Eligibility depends on payment status, entitlement dates and assigned products, not a screen label.","Data dictionary and decision table","Mixing policy, implementation and exception handling in one vague sentence.","Turn a complex eligibility rule into a decision table."),
    m("User Stories and Agile",["User Stories","Agile","Jira"],"A user story expresses a small valuable capability, while acceptance criteria make expected behaviour testable.","Split by workflow or rule, write user-value context, add Given-When-Then criteria, refine dependencies and prioritise.","As a student, I can submit a support request and receive a reference so I can track that help was requested.","Jira backlog and story mapping","Using the story format for large projects or writing acceptance criteria as design instructions only.","What makes a story ready for development?"),
    m("Solution Evaluation and UAT",["UAT","Solution Evaluation","Traceability"],"Solution evaluation checks whether delivered behaviour satisfies requirements and produces the intended business outcome.","Trace requirements, plan representative UAT, prepare data, record evidence, manage decisions and measure post-release value.","College admins validate student onboarding with realistic roles, duplicates and recovery cases before launch.","Traceability matrix, UAT plan and issue log","Treating UAT as another developer test or accepting feedback without agreed criteria.","How do system testing and user acceptance testing differ?"),
    m("BA Portfolio Project",["Business Analysis","BRD","User Stories","Process Mapping"],"A BA portfolio demonstrates structured discovery, traceable decisions, clear artefacts and stakeholder communication.","Select a real process, frame the problem, analyse stakeholders, map it, document requirements, write stories and define evaluation.","Redesign a support or course-assignment process and present an evidence-backed recommendation.","Document, diagram and backlog tools","Producing templates filled with generic text that do not connect to one coherent problem.","Explain one requirement conflict and how you resolved it using evidence and trade-offs.")
  ]},
  {code:"AWS-001",title:"AWS & Cloud Fundamentals",slug:"aws-cloud-fundamentals",category:"Cloud Technology",description:"Understand cloud concepts and design secure, cost-aware AWS foundations for entry-level technical roles.",outcome:"Create and explain a small AWS architecture with identity controls, networking, compute, storage, monitoring and cost safeguards.",skills:["AWS","Cloud Computing","IAM","Networking","EC2","S3","Cloud Security"],modules:[
    m("Cloud Concepts",["Cloud Computing","AWS"],"Cloud computing delivers metered technology resources through APIs with elasticity, managed services and shared responsibility.","Translate a workload's demand, control and compliance needs into service and deployment model choices.","A startup uses managed cloud services to launch quickly but keeps responsibility for data and access configuration.","AWS global infrastructure overview","Assuming cloud automatically makes an application secure, cheap or highly available.","Compare IaaS, PaaS and SaaS with responsibility examples."),
    m("AWS Global Infrastructure",["AWS","High Availability"],"AWS Regions contain isolated Availability Zones; service scope and architecture determine resilience and latency.","Choose a Region, identify service scope, distribute critical components and plan failure recovery.","A web application runs across two Availability Zones and stores durable backups separately.","AWS console and service documentation","Confusing Regions, Availability Zones and edge locations.","Why can multiple Availability Zones improve availability?"),
    m("Identity and Access Management",["IAM","Cloud Security","AWS"],"IAM controls authentication and authorisation through identities, roles, policies and least-privilege permissions.","Use strong account protection, prefer roles and temporary credentials, grant minimum actions and review access.","An EC2 workload reads one S3 bucket through an instance role instead of embedded access keys.","IAM users, roles, policies and MFA","Using the root account daily or placing long-lived keys in source code.","Differentiate an IAM role from an IAM user."),
    m("Networking Foundations",["AWS Networking","VPC","Cloud Security"],"A VPC defines private network boundaries, subnets, routes and traffic controls for cloud resources.","Plan CIDR ranges, separate public and private subnets, route intentionally and restrict inbound and outbound traffic.","A load balancer is public while application and database resources remain in private subnets.","VPC, subnets, route tables and security groups","Making every resource public to solve connectivity problems quickly.","Compare security groups and network ACLs at a foundation level."),
    m("Compute and Scaling",["EC2","Auto Scaling","AWS"],"Cloud compute choices balance control, operational effort, traffic pattern and execution model.","Characterise workload duration and state, choose EC2 or serverless, configure health, scaling and failure recovery.","A stateless web tier uses a load balancer and Auto Scaling; a scheduled task uses Lambda.","EC2, Elastic Load Balancing, Auto Scaling and Lambda","Choosing the largest instance or serverless for every workload without analysing constraints.","When would Lambda be a poor fit?"),
    m("Storage and Databases",["S3","RDS","Cloud Storage"],"Object, block, file and database services solve different durability, access and query requirements.","Classify data and access, choose service, configure encryption and lifecycle, back up and test recovery.","Documents use S3 lifecycle rules while transactional records use a managed relational database.","S3, EBS and RDS","Using S3 like a relational database or assuming snapshots replace tested recovery.","Compare S3, EBS and RDS use cases."),
    m("Monitoring, Security and Cost",["CloudWatch","Cloud Security","Cloud Cost"],"A production cloud foundation needs logs, metrics, alerts, configuration controls and accountable cost visibility.","Define health indicators, centralise logs, alert on action, tag ownership, set budgets and review security findings.","A team alerts on error rate and cost anomaly while retaining audit logs for investigation.","CloudWatch, CloudTrail, Budgets and security services","Monitoring only CPU or discovering cost after the billing period closes.","What is the difference between CloudWatch and CloudTrail?"),
    m("Cloud Architecture Project",["AWS","Cloud Architecture","Cloud Security"],"A sound entry-level architecture explains workload, components, data flow, security, resilience, monitoring and cost assumptions.","Gather requirements, draw the architecture, apply least privilege, model failure, estimate cost and present trade-offs.","Design a small learning platform with web delivery, API compute, relational data, object storage and monitoring.","AWS Architecture icons and pricing calculator","Drawing many services without explaining necessity, data flow or failure behaviour.","Defend one service choice and one security control in your architecture.")
  ]},
  {code:"DMF-001",title:"Digital Marketing Fundamentals",slug:"digital-marketing-fundamentals",category:"Marketing",description:"Plan, execute and measure ethical entry-level digital marketing across content, search, social, email and paid campaigns.",outcome:"Build a channel plan and campaign portfolio with audience research, creative, landing-page logic, measurement and optimisation recommendations.",skills:["Digital Marketing","SEO","Social Media Marketing","Content Marketing","Email Marketing","Marketing Analytics"],modules:[
    m("Marketing Strategy and Funnel",["Digital Marketing","Marketing Funnel"],"Digital marketing connects a defined audience and value proposition to measurable acquisition, conversion and retention outcomes.","Set the business goal, research the audience, state the offer, map funnel stages and choose metrics before channels.","A training programme targets final-year students with different messages for discovery, evaluation and enrolment.","Campaign brief and funnel map","Choosing channels because they are popular rather than because they fit audience and objective.","Differentiate awareness, consideration and conversion metrics."),
    m("Audience and Positioning",["Audience Research","Positioning"],"Audience research identifies needs, behaviour, language and barriers; positioning explains relevant value against alternatives.","Combine interviews, search behaviour and analytics, segment meaningfully, then write evidence-based message hypotheses.","Job seekers value interview practice, transparent curriculum and affordability for different reasons.","Persona, jobs-to-be-done and message matrix","Inventing personas from stereotypes or trying to speak to everyone with one generic promise.","How would you validate a target-audience assumption?"),
    m("Content Marketing",["Content Marketing","Copywriting"],"Content earns attention by solving a relevant audience problem in a format suited to its journey stage and channel.","Choose a question, define intent, outline useful evidence, create, edit, distribute and measure the intended action.","A practical SQL interview checklist leads readers to a detailed course page without exaggerated claims.","Editorial calendar and content brief","Publishing high volume without a useful point of view, distribution plan or conversion path.","How do you match content to search or audience intent?"),
    m("SEO Fundamentals",["SEO","Keyword Research"],"Search optimisation helps useful pages be discoverable by aligning intent, content, technical accessibility and credible signals.","Research query intent, map a primary topic, create clear page structure, improve technical basics and monitor results.","A Power BI course page answers curriculum, audience, prerequisites and project questions clearly.","Search Console concepts and keyword tools","Stuffing keywords, copying competitors or promising rankings without technical and content evidence.","Explain search intent and why it matters more than raw keyword volume."),
    m("Social Media Marketing",["Social Media Marketing","Community Management"],"Social strategy selects platforms, formats and interaction based on audience behaviour and a measurable role in the funnel.","Set a channel job, develop content pillars, create platform-native posts, schedule, engage and analyse quality signals.","LinkedIn posts share portfolio guidance and route interested graduates to a readiness assessment.","Native analytics and publishing tools","Cross-posting identical content everywhere or treating follower count as business impact.","Which metrics indicate meaningful social engagement?"),
    m("Email and Lifecycle Marketing",["Email Marketing","CRM"],"Email marketing uses permission, segmentation and timely value to move relationships through onboarding, activation and retention.","Define trigger and segment, write a focused message, design one action, test deliverability and measure beyond opens.","A learner receives welcome, incomplete-assessment and course-progress messages based on actual status.","Email platform and CRM","Buying lists, hiding consent or sending one generic campaign to every contact.","Why are click and conversion metrics often more useful than open rate?"),
    m("Paid Media and Landing Pages",["Paid Advertising","Conversion Optimisation"],"Paid campaigns combine objective, audience, creative, bid and landing-page continuity under controlled budgets and experiments.","Set conversion and economics, create testable audience and creative hypotheses, align the landing page and monitor quality.","An ad for a ₹999 bundle lands on a page explaining included courses and verified checkout clearly.","Ad platform concepts and landing-page analytics","Optimising clicks while ignoring lead quality, conversion tracking or message mismatch.","What causes a high click-through rate but poor conversion?"),
    m("Measurement and Campaign Project",["Marketing Analytics","Digital Marketing"],"Marketing measurement links channel activity to defined outcomes while recognising attribution and data-quality limitations.","Create a measurement plan, tag campaigns, validate events, analyse funnel conversion, recommend a test and report uncertainty.","Launch a small career-course campaign with UTM tracking, content assets, email follow-up and a performance review.","Analytics, UTM conventions and reporting dashboard","Claiming one channel caused every conversion or changing campaigns before enough evidence accumulates.","How would you evaluate a campaign with strong traffic but weak enrolment?")
  ]},
  {code:"SBD-001",title:"Sales & Business Development",slug:"sales-business-development",category:"Sales",description:"Build ethical entry-level sales capability from prospecting and qualification to CRM discipline, objections and closing.",outcome:"Complete a practical sales portfolio with an ICP, prospect list, outreach sequence, discovery guide, CRM pipeline and forecast review.",skills:["Sales","Business Development","Prospecting","Lead Qualification","CRM","Negotiation","Sales Analytics"],modules:[
    m("Sales Foundations and Customer Value",["Sales","Value Proposition"],"Professional selling helps a suitable customer make a sound decision by connecting verified needs to relevant value.","Understand the market and offer, define an ideal customer, identify value hypotheses and set ethical qualification boundaries.","A training provider sells employability outcomes through curriculum evidence rather than guaranteeing jobs.","Value proposition canvas and ICP","Pitching features immediately or making unsupported promises to force interest.","How do features, benefits and customer value differ?"),
    m("Prospecting and Research",["Prospecting","Business Development"],"Prospecting identifies accounts and contacts with plausible need, fit and timing using responsible research.","Define account criteria, research trigger events and roles, prioritise, record evidence and select an outreach reason.","A B2B learning team identifies colleges with placement initiatives and the appropriate decision roles.","LinkedIn, company sources and prospect list","Collecting large unqualified lists or using personal data without a legitimate sales purpose.","What makes a prospect worth contacting now?"),
    m("Outreach and Communication",["Sales Communication","Cold Email"],"Effective outreach is relevant, concise and credible: it connects a researched trigger to one useful conversation.","Open with context, state a relevant problem and evidence, offer a clear value hypothesis and ask for a low-friction next step.","An email references a college's placement drive and proposes a brief diagnostic pilot discussion.","Email, phone and social outreach","Writing self-centred templates, fake personalisation or repeated spam without learning.","Critique a cold email that begins with a long company introduction."),
    m("Qualification and Discovery",["Lead Qualification","Discovery"],"Qualification tests fit, need, impact, authority, process and timing while discovery uncovers the customer's current reality.","Prepare hypotheses, ask open and diagnostic questions, listen, summarise, quantify impact and agree next steps.","A discovery call explores current student preparation, completion, reporting and procurement constraints.","Discovery guide and qualification framework","Interrogating prospects, leading them to desired answers or qualifying only on budget.","Which discovery questions reveal impact rather than surface preference?"),
    m("Presentations and Proposals",["Sales Presentation","Proposal Writing"],"A sales presentation should reflect discovered priorities and connect solution evidence to agreed outcomes and evaluation criteria.","Restate the problem, prioritise relevant capabilities, demonstrate proof, address implementation and document decisions.","A proposal maps diagnostic, learning and reporting capabilities to the college's placement objectives.","Presentation and proposal template","Delivering the same feature tour to every buyer or hiding assumptions and responsibilities.","How do you tailor a demo after discovery?"),
    m("Objections and Negotiation",["Objection Handling","Negotiation"],"An objection signals risk, uncertainty or misfit; effective handling clarifies it before responding with evidence or alternatives.","Acknowledge, ask focused questions, confirm the real concern, respond honestly, check resolution and document follow-up.","For a price objection, explore comparison, budget timing and expected value before discussing scope.","Objection log and negotiation plan","Arguing, discounting immediately or using manipulative pressure.","How would you respond to 'Send information; we are not ready'?"),
    m("CRM, Pipeline and Forecasting",["CRM","Sales Pipeline","Forecasting"],"CRM discipline records verified customer state, next action and evidence so teams can manage pipeline and forecast responsibly.","Define stages with exit criteria, update interactions and next steps, inspect ageing and conversion, and forecast using evidence.","An opportunity advances only after need and agreed next meeting are confirmed, not because an email was sent.","CRM and pipeline dashboard","Keeping deals in optimistic stages without next actions or using CRM only for management reporting.","What evidence should be required to advance an opportunity stage?"),
    m("Closing, Handover and Sales Project",["Closing","Customer Handover","Sales Analytics"],"Closing confirms mutual fit, commercial agreement and implementation expectations; handover protects the value promised.","Summarise decisions, resolve remaining risk, confirm terms and stakeholders, document handover and review outcomes.","Create an end-to-end sales simulation from target account through discovery, proposal, CRM forecast and implementation handoff.","CRM, proposal and handover checklist","Treating signature as the end of responsibility or handing over incomplete customer context.","Explain how a clean handover supports retention and future revenue.")
  ]},
  {code:"MOW-001",title:"MS Office & Workplace Productivity",slug:"ms-office-workplace-productivity",category:"Workplace Productivity",description:"Develop practical document, spreadsheet, presentation, email and collaboration habits for professional office work.",outcome:"Deliver a workplace portfolio containing a polished document, controlled tracker, decision presentation and collaboration workflow.",skills:["MS Office","Microsoft Word","Excel","PowerPoint","Outlook","Microsoft Teams","Workplace Productivity"],modules:[
    m("Digital Work Organisation",["Workplace Productivity","File Management"],"Professional digital work uses consistent naming, ownership, versions, storage and access so information can be found and trusted.","Choose the system of record, design folders and names, assign owners, manage versions and archive deliberately.","A project keeps approved documents in shared storage rather than email attachments named final-v7.","OneDrive, SharePoint and file conventions","Saving work only locally or creating uncontrolled duplicate copies.","How do you distinguish version history from multiple filenames?"),
    m("Word Documents",["Microsoft Word","Document Design"],"A professional Word document uses styles, structure, navigation and controlled layout instead of manual formatting.","Plan the reader and purpose, apply heading styles, use tables and lists appropriately, add references and run accessibility checks.","Create a project report with title page, headings, table of contents and consistent captions.","Microsoft Word","Using spaces and blank lines for layout or formatting each heading separately.","Why are styles important beyond appearance?"),
    m("Excel Workplace Tracking",["Excel","Data Management"],"A workplace tracker uses structured tables, validation, formulas and protected fields to maintain reliable operational status.","Define one row's meaning, create controlled fields, add validation and calculations, then build exception views.","A task tracker records owner, due date, status and ageing with overdue highlighting.","Excel tables, validation and conditional formatting","Using merged cells, inconsistent status text or manual totals in operational data.","What makes a spreadsheet suitable for filtering and reporting?"),
    m("PowerPoint Communication",["PowerPoint","Business Communication"],"A strong presentation follows a decision narrative and uses each slide to communicate one supported message.","Define audience and decision, outline the story, write message titles, choose evidence, simplify visuals and rehearse.","A five-slide review covers objective, progress, issue, options and recommendation.","Microsoft PowerPoint","Decorating slides before clarifying the message or reading dense paragraphs aloud.","How does a message title differ from a topic title?"),
    m("Outlook and Professional Email",["Outlook","Email Communication"],"Professional email makes purpose, action, owner and timing clear while using recipients and attachments responsibly.","Choose the right channel, write a specific subject, lead with purpose, state action and deadline, review recipients and send.","A meeting follow-up records decisions, owners and dates without exposing confidential information.","Microsoft Outlook","Using Reply All unnecessarily, unclear subjects or sending sensitive attachments to the wrong audience.","When should CC, BCC and a Teams message be used?"),
    m("Meetings and Teams Collaboration",["Microsoft Teams","Collaboration","Meeting Management"],"Effective collaboration uses shared context, purposeful meetings, recorded decisions and accountable follow-through.","Set an outcome and agenda, invite necessary roles, facilitate time, capture decisions and track actions in shared tools.","A project channel contains the current files, decision notes and owner-tagged actions.","Microsoft Teams, calendar and shared notes","Holding meetings without decisions or storing key information only in private chats.","What makes a meeting necessary rather than an email or shared document?"),
    m("Integrated Office Workflows",["MS Office","Automation","Workplace Productivity"],"Office tools create more value when information flows predictably between data, documents, presentations and collaboration.","Identify source data, create reusable outputs, link rather than duplicate where safe, refresh, validate and distribute.","An Excel status table supplies charts for a PowerPoint review and actions for a Teams follow-up.","Word, Excel, PowerPoint, Outlook and Teams","Copying numbers manually across files without recording source or refresh date.","How would you prevent inconsistent figures across a report and presentation?"),
    m("Workplace Productivity Capstone",["MS Office","Workplace Productivity","Business Communication"],"A workplace portfolio demonstrates clear communication, reliable information handling and efficient collaboration across common office tasks.","Plan a small project, build its tracker, write a report, present a recommendation and communicate actions professionally.","Deliver a mock campus-placement event pack with schedule, budget tracker, briefing deck and follow-up email.","Microsoft 365 applications","Showing isolated formatting exercises rather than one coherent business workflow.","Present one productivity improvement and the control that keeps it reliable.")
  ]}
];

function checks(course:LaunchCourse,module:LaunchModule,kind:"concept"|"workflow"|"assessment"){
  const base=[
    {question:`In your own words, what problem does ${module.title.toLowerCase()} solve?`,answer:module.concept,explanation:"A strong answer states the business or user problem before naming a tool."},
    {question:`How would you apply this capability in the following workplace situation: ${module.workplace}`,answer:module.workflow,explanation:"The response should describe a controlled, verifiable workflow rather than only a feature."},
    {question:module.interview,answer:`Use ${module.concept} Then describe the workflow: ${module.workflow}`,explanation:"Interview answers should connect principle, action, validation and outcome."}
  ];
  if(kind!=="assessment")return base;
  return [...base,
    {question:`Identify the main risk in this incorrect approach: ${module.mistake}`,answer:`The approach is unreliable because it breaks the controls implied by ${module.concept}`,explanation:"The correction should address cause and verification, not only appearance."},
    {question:`Which tool or artefact would you use first, and what would you verify?`,answer:`Use ${module.tool}; verify that the result satisfies the stated decision, data and quality requirements.`,explanation:"Tools support a method; they do not replace validation."}
  ];
}

function lesson(course:LaunchCourse,module:LaunchModule,moduleIndex:number,kind:"concept"|"workflow"|"assessment"):AuthoredCurriculumItem{
  const title=kind==="concept"?`${module.title}: Core Concepts`:kind==="workflow"?`${module.title}: Practical Workflow`:`${module.title}: Workplace Lab & Module Check`;
  const definition=kind==="concept"?module.concept:kind==="workflow"?`${module.workflow} The work should be reproducible and reviewed against a clear outcome.`:`Apply ${module.concept} Complete the scenario, produce evidence, explain the decision and correct the common failure: ${module.mistake}`;
  return {course:course.title,module:`Module ${moduleIndex+1} · ${module.title}`,topic:kind==="concept"?"Understand":kind==="workflow"?"Apply":"Assess",subtopic:title,definition,coverage:module.skills,practical:kind==="assessment"?`Complete this workplace lab: ${module.workplace}`:`Practise this workflow: ${module.workflow}`,example:module.workplace,answer:kind==="assessment"?`A complete submission uses ${module.tool}, follows the workflow, records validation evidence and explains one limitation.`:module.workflow,tip:`Avoid this common mistake: ${module.mistake}`,difficulty:moduleIndex<3?"Foundation":"Foundation to applied",estimatedMinutes:kind==="assessment"?30:22,targetAudience:"College students, fresh graduates and entry-level job seekers",whyItMatters:`${module.title} is used in entry-level work and is assessed through practical scenarios and interviews.`,examContext:`${course.title} module assessment and entry-level interview preparation`,detailedSections:[{title:"Principle",explanation:module.concept,example:module.workplace},{title:"Workplace method",explanation:module.workflow,example:`Use ${module.tool} and retain evidence of the result.`},{title:"Quality and interview check",explanation:`Verify the outcome, explain trade-offs and avoid: ${module.mistake}`,example:module.interview}],keyTerms:module.skills.slice(0,4).map(skill=>({term:skill,definition:`A practical capability used in ${module.title.toLowerCase()} work.`,example:module.workplace})),practiceQuestions:checks(course,module,kind)};
}

function finalLesson(course:LaunchCourse):AuthoredCurriculumItem{
  const modules=course.modules.map(module=>module.title);
  return {course:course.title,module:`Module 8 · ${course.modules[7].title}`,topic:"Final assessment",subtopic:`${course.title}: Final Assessment & Portfolio Review`,definition:`The final assessment integrates ${modules.join(", ")} into one coherent, job-relevant deliverable.`,coverage:course.skills,practical:course.outcome,example:`Present the final deliverable as if handing it to a manager or interviewer. Include the problem, method, evidence, result and limitation.`,answer:`A complete submission achieves this outcome: ${course.outcome}`,tip:"Demonstrate judgement and verification; do not submit disconnected screenshots or unsupported claims.",difficulty:"Applied entry-level",estimatedMinutes:60,targetAudience:"College students, fresh graduates and entry-level job seekers",whyItMatters:"The capstone becomes portfolio evidence and a structured interview story.",examContext:`${course.title} final course assessment`,detailedSections:[{title:"Plan",explanation:"Define the user, decision, inputs, deliverables and success checks before building.",example:course.outcome},{title:"Build and validate",explanation:"Complete the workflow using controlled data, appropriate tools and recorded checks.",example:"Retain source, working files and a short validation log."},{title:"Present",explanation:"Communicate the outcome, evidence, trade-offs and next action concisely.",example:"Use a problem-action-result-reflection interview narrative."}],keyTerms:course.skills.slice(0,5).map(skill=>({term:skill,definition:`A core employability skill in ${course.title}.`,example:course.outcome})),practiceQuestions:[{question:"What problem and user does your capstone address?",answer:"State a specific user, decision and measurable outcome.",explanation:"A portfolio project needs a real purpose."},{question:"Which evidence proves the result is correct?",answer:"Provide reconciliation, tests or review evidence appropriate to the course.",explanation:"Visible validation builds trust."},{question:"What was the most important trade-off?",answer:"Name the alternatives, constraint, decision and consequence.",explanation:"Trade-offs demonstrate judgement."},{question:"What limitation remains?",answer:"State one honest boundary and how future work could address it.",explanation:"Professional communication does not overclaim."},{question:"Explain your project in 90 seconds.",answer:"Use problem, action, validated result and reflection.",explanation:"This structure creates a concise interview story."}]};
}

export const launchCatalogueCurriculum:AuthoredCurriculumItem[]=launchCourses.flatMap(course=>[
  ...course.modules.flatMap((module,index)=>[lesson(course,module,index,"concept"),lesson(course,module,index,"workflow"),lesson(course,module,index,"assessment")]),
  finalLesson(course)
]);
