import type { LaunchCourse, LaunchModule } from "@/lib/content-factory/launch-catalogue";

type Seed={title:string;skills:[string,string];focus:string;example:string;mistake:string};
const modules=(items:Seed[]):LaunchModule[]=>items.map(item=>({title:item.title,skills:item.skills,concept:item.focus,workflow:`Define the purpose and audience, gather verified facts, apply the ${item.skills[0]} method, check the result, and record the next action.`,workplace:item.example,tool:`${item.title} checklist and evidence log`,mistake:item.mistake,interview:`Explain how you would apply ${item.skills[0].toLowerCase()} in this scenario: ${item.example}`}));
const make=(code:string,title:string,slug:string,category:string,description:string,outcome:string,skills:string[],items:Seed[]):LaunchCourse=>({code,title,slug,category,description,outcome,skills,modules:modules(items)});

export const nonTechnicalCourses:LaunchCourse[]=[
 make("BCP-001","Business Communication & Professional English","business-communication-professional-english","Career Readiness","Communicate clearly in workplace conversations, email, meetings and presentations.","Write and speak with professional structure, accuracy, listening discipline and audience awareness.",["Professional English","Email Writing","Meetings","Presentations","Active Listening","Team Communication"],[
  {title:"Professional English",skills:["Professional English","Vocabulary"],focus:"Professional English is clear, courteous and specific; familiar words and explicit actions are stronger than decorative language.",example:"Rewrite a delay update so a manager can see the cause, impact, owner and revised time.",mistake:"Using inflated vocabulary or translated informal speech."},
  {title:"Grammar for Clear Work",skills:["Grammar","Editing"],focus:"Grammar supports meaning through controlled tense, agreement, sentence boundaries and consistent references.",example:"Correct an ambiguous status report without changing its verified facts.",mistake:"Editing for sophistication instead of accuracy."},
  {title:"Email Writing",skills:["Email Writing","Business Writing"],focus:"A useful email exposes its purpose, evidence, requested action and timing quickly.",example:"Send minutes that separate decisions, owners, deadlines and open questions.",mistake:"Using a vague subject or hiding the request."},
  {title:"Listening and Feedback",skills:["Active Listening","Feedback"],focus:"Workplace dialogue requires listening for facts, intent and constraints before responding.",example:"Clarify conflicting instructions and document the agreed priority.",mistake:"Interrupting, assuming intent or giving personality-based feedback."},
  {title:"Meetings",skills:["Meetings","Facilitation"],focus:"A productive meeting has a decision purpose, prepared inputs and recorded ownership.",example:"Run a 15-minute risk review and close with three owned actions.",mistake:"Recording discussion without decisions."},
  {title:"Presentations",skills:["Presentations","Audience Awareness"],focus:"A presentation organises evidence around what the audience must understand, decide or do.",example:"Present a five-minute recommendation using one chart and two actions.",mistake:"Reading slides or reporting numbers without a conclusion."},
  {title:"Managers and Teams",skills:["Team Communication","Stakeholder Management"],focus:"Channel, tone, detail and escalation should reflect authority, urgency and stakeholder need.",example:"Escalate a missed dependency while preserving team trust and delivery evidence.",mistake:"Sending the same message to every stakeholder."},
  {title:"Communication Capstone",skills:["Communication Planning","Professional Judgement"],focus:"Integrated communication uses the right channel, accurate evidence and a controlled next action.",example:"Handle a missed client deadline through escalation, update, recovery meeting and follow-up.",mistake:"Promising an unapproved recovery."},
 ]),
 make("IPB-001","Interview Skills & Personal Branding","interview-skills-personal-branding","Career Readiness","Build truthful career stories, interview structure and a consistent professional profile.","Present relevant evidence confidently across resumes, LinkedIn, HR and behavioural interviews.",["Self Introduction","STAR Method","Resume Presentation","LinkedIn","Interview Skills","Follow-up"],[
  {title:"Career Story",skills:["Self Introduction","Career Direction"],focus:"A strong introduction connects present capability, evidence and intended role without retelling a biography.",example:"Link event coordination and Excel reporting to an operations role.",mistake:"Listing adjectives without evidence."},
  {title:"Resume Evidence",skills:["Resume Presentation","Achievement Writing"],focus:"Every resume claim should be truthful, relevant and explainable.",example:"Turn a college project into a bullet with scope, contribution and tested result.",mistake:"Inventing metrics or claiming team work as individual ownership."},
  {title:"HR Interviews",skills:["HR Interview","Role Fit"],focus:"HR answers should connect motivation, availability and evidence to the actual role.",example:"Explain why a customer-operations role fits your transferable experience.",mistake:"Giving a generic company-praise answer."},
  {title:"STAR Method",skills:["STAR Method","Behavioural Questions"],focus:"Behavioural answers show judgement through situation, personal action, result and learning.",example:"Describe a project disagreement resolved through an agreed test.",mistake:"Using hypotheticals or saying only what the team did."},
  {title:"Strengths and Weaknesses",skills:["Self Awareness","Improvement"],focus:"Credible answers balance self-awareness with evidence and improvement action.",example:"Explain a presentation weakness through feedback and recent progress.",mistake:"Calling perfectionism a weakness."},
  {title:"LinkedIn and Networking",skills:["LinkedIn","Networking"],focus:"A professional brand is consistent evidence across profile, work samples and communication.",example:"Improve an analyst profile and send a concise alumni outreach message.",mistake:"Requesting referrals before building context."},
  {title:"Offers and Salary",skills:["Salary Discussion","Offer Evaluation"],focus:"Offer discussions require research, clarification and evaluation of the full role.",example:"Compare offers using learning, scope, fixed pay, location and conditions.",mistake:"Lying about another offer."},
  {title:"Mock Interview Capstone",skills:["Interview Practice","Follow-up"],focus:"Interview readiness combines concise evidence, listening, professional questions and follow-up.",example:"Complete a mock interview from introduction through candidate questions.",mistake:"Memorising one answer for every role."},
 ]),
 make("SNF-001","Sales & Negotiation Fundamentals","sales-negotiation-fundamentals","Business & Sales","Learn ethical prospecting, discovery, pitching, objection handling, negotiation and follow-up.","Run a structured sales conversation that creates value, records evidence and protects trust.",["Prospecting","Discovery","Pitching","Objection Handling","Negotiation","CRM"],[
  {title:"Ethical Sales",skills:["Sales Process","Sales Ethics"],focus:"Professional selling identifies a genuine need and helps a buyer evaluate fit.",example:"Assess whether a training product fits a college before proposing a demo.",mistake:"Promising unsupported results."},
  {title:"Prospecting",skills:["Prospecting","Research"],focus:"Good prospecting earns a conversation with a researched, relevant reason.",example:"Write outreach based on a visible graduate-hiring initiative.",mistake:"Sending generic bulk messages."},
  {title:"Qualification",skills:["Qualification","Pipeline"],focus:"Qualification tests need, fit, stakeholder authority, timing and a credible next step.",example:"Separate an interested contact from a qualified opportunity.",mistake:"Confusing interest with buying authority."},
  {title:"Discovery",skills:["Discovery","Active Listening"],focus:"Discovery uncovers situation, impact, desired outcome, constraints and decision process.",example:"Explore why a retailer wants more leads before proposing spend.",mistake:"Pitching after the first pain point."},
  {title:"Pitching",skills:["Pitching","Value Proposition"],focus:"A relevant pitch connects an agreed problem to outcome, mechanism and evidence.",example:"Present only the features relevant to a confirmed hiring bottleneck.",mistake:"Feature dumping."},
  {title:"Objections",skills:["Objection Handling","Follow-up"],focus:"An objection should be clarified before it is answered or negotiated.",example:"Handle 'too expensive' by checking comparison, value, budget and timing.",mistake:"Arguing or discounting immediately."},
  {title:"Negotiation and Closing",skills:["Negotiation","Closing"],focus:"Negotiation trades variables while protecting priorities, authority and trust.",example:"Trade implementation timing for commitment without unauthorised discount.",mistake:"Negotiating against yourself."},
  {title:"CRM and Relationships",skills:["CRM","Relationship Building"],focus:"Reliable sales work depends on accurate records, dated actions and useful post-sale communication.",example:"Record stakeholders, need, risk and next step after discovery.",mistake:"Writing vague notes or chasing without value."},
 ]),
 make("DMF-001","Digital Marketing Fundamentals","digital-marketing-fundamentals","Marketing","Plan practical audience, content, search, social, email and measurement workflows.","Build and evaluate a small ethical campaign using objectives, channel choices and evidence.",["Customer Personas","Content Marketing","Social Media","SEO","Lead Generation","Analytics"],[
  {title:"Marketing Fundamentals",skills:["Marketing Goals","Value Proposition"],focus:"Marketing connects a defined audience and need to an offer through measurable communication.",example:"Translate an enrolment objective into audience, behaviour and metric.",mistake:"Starting with a channel trend."},
  {title:"Personas",skills:["Customer Personas","Research"],focus:"Personas summarise evidence about goals, barriers and behaviour; they are not invented biographies.",example:"Segment first-time job seekers using research evidence.",mistake:"Treating all students as one persona."},
  {title:"Content Marketing",skills:["Content Marketing","Copywriting"],focus:"Useful content serves a specific audience question and journey stage.",example:"Plan content from interview anxiety to mock-interview registration.",mistake:"Publishing unrelated posts consistently."},
  {title:"Social Media",skills:["Social Media","Community"],focus:"Social performance depends on audience-platform fit, interaction and measurement.",example:"Adapt one campaign for LinkedIn and Instagram.",mistake:"Buying followers or copying the same post everywhere."},
  {title:"SEO",skills:["SEO","Search Intent"],focus:"SEO improves useful pages for real intent, accessible structure and trustworthy discovery.",example:"Optimise a course page for a specific early-career search.",mistake:"Keyword stuffing or chasing irrelevant volume."},
  {title:"Funnels and Leads",skills:["Lead Generation","Funnels"],focus:"A funnel measures steps from attention to qualified action and their drop-offs.",example:"Build a webinar signup that separates attendance from purchase intent.",mistake:"Treating every signup as sales-ready."},
  {title:"Email Marketing",skills:["Email Marketing","Consent"],focus:"Email develops consent-based relationships through relevant sequencing and suppression controls.",example:"Write a three-message webinar follow-up sequence.",mistake:"Buying lists or hiding unsubscribe choices."},
  {title:"Analytics Capstone",skills:["Analytics","Optimisation"],focus:"Analysis compares performance with an objective and proposes a controlled next test.",example:"Compare channels using cost, qualified leads and conversion.",mistake:"Optimising vanity metrics or changing many variables at once."},
 ]),
 make("FLY-001","Financial Literacy for Young Professionals","financial-literacy-young-professionals","Personal Finance","Make safer early-career decisions about salary, budgets, banking, credit, insurance, taxes and investing.","Create a realistic personal money plan and evaluate products and risks without unsupported promises.",["Budgeting","Banking","Credit","Loans","Insurance","Taxes","Investing","Fraud Awareness"],[
  {title:"Salary Basics",skills:["Salary","Payslips"],focus:"Fixed pay, variable pay, contributions, deductions and take-home are different figures.",example:"Compare offers with different fixed pay, incentives and relocation costs.",mistake:"Comparing only CTC."},
  {title:"Budgeting",skills:["Budgeting","Cash Flow"],focus:"A useful budget reflects actual income, essentials, goals and flexibility.",example:"Build a first-job budget with rent, commute and family support.",mistake:"Using unrealistic percentages."},
  {title:"Emergency Savings",skills:["Savings","Emergency Fund"],focus:"Emergency money protects near-term needs and should remain accessible and low risk.",example:"Set a staged reserve target after joining a first job.",mistake:"Investing money needed for emergencies."},
  {title:"Banking and Payments",skills:["Banking","Digital Payments"],focus:"Accounts and payment systems differ in fees, limits, controls and recovery responsibilities.",example:"Investigate a failed UPI payment without paying twice.",mistake:"Sharing OTPs or trusting screenshots."},
  {title:"Credit, Loans and EMI",skills:["Credit Score","Loans"],focus:"Borrowing should be evaluated using total cost, fees, tenure and repayment risk.",example:"Compare shorter and longer EMIs using total interest.",mistake:"Choosing by EMI alone."},
  {title:"Insurance",skills:["Insurance","Risk Protection"],focus:"Insurance transfers defined risks under coverage limits and exclusions.",example:"Compare employer health cover with personal needs.",mistake:"Buying insurance only for returns."},
  {title:"Taxes",skills:["Taxes","Financial Records"],focus:"Tax decisions require accurate income records and current official rules.",example:"Organise salary and investment documents for filing.",mistake:"Relying on social-media tax claims."},
  {title:"Investing and Scam Safety",skills:["Investing","Fraud Awareness"],focus:"Investing matches goals, horizon, risk, diversification and cost; returns are not guaranteed.",example:"Flag red signs in a guaranteed-return messaging-group offer.",mistake:"Borrowing to speculate or sharing remote access."},
 ])
].filter(course=>course.slug!=="digital-marketing-fundamentals");
