import type { AuthoredCurriculumItem } from "@/lib/content-factory/authored-curriculum";

export const SERVICENOW_COURSE = "ServiceNow ITSM, Development & GenAI Career Program";
export const serviceNowProgram = {
  duration:"12-16 weeks", schedule:"2 hours a day, 5 days a week", learningMix:"40% concept / 60% hands-on",
  audience:"Fresh graduates, working professionals, service desk analysts, and learners preparing for ServiceNow administration or development roles",
  promise:"Learn the process. Configure the platform. Build the solution. Use AI responsibly.",
  tracks:["ServiceNow ITSM","ServiceNow Development","Prompt Engineering"],
  projects:["ITSM Case Study","ServiceNow Application","AI-assisted Service Desk"],
};

const sn=(module:string,topic:string,subtopic:string,definition:string,coverage:string[],practical:string,example:string,answer:string,tip:string,estimatedMinutes=30):AuthoredCurriculumItem=>({course:SERVICENOW_COURSE,module,topic,subtopic,definition,coverage,practical,example,answer,tip,estimatedMinutes,targetAudience:serviceNowProgram.audience,difficulty:"Career-ready: foundation to applied",whyItMatters:"This capability is part of the practical pathway from service-management fundamentals to secure platform development and AI-assisted operations.",examContext:"ServiceNow administration, development, ITSM practice, portfolio evidence and interview readiness"});

export const serviceNowCurriculum:AuthoredCurriculumItem[]=[
  sn("Track 1 - ServiceNow ITSM","ITSM Foundations","ServiceNow and ITSM Foundations","ITSM provides structured practices for designing, delivering, supporting and improving technology services.",["ITSM and ITIL terminology","ServiceNow platform, roles and navigation","Lists, forms, filters and records"],"Explore a ServiceNow developer instance and create sample records.","A new analyst must locate incidents, filter assigned records and open a record safely. Describe the workflow.","Navigate to the correct module, filter the list, inspect the form and create a clearly labelled sample record.","Separate the service-management process from the platform feature used to support it."),
  sn("Track 1 - ServiceNow ITSM","Core ITSM Workflows","Incident Management","Incident management restores normal service quickly while recording impact, ownership, progress and resolution evidence.",["Incident lifecycle, categorisation and assignment","Impact, urgency, priority and escalation","Resolution, SLAs and major incidents"],"Handle an incident from logging to closure.","A payroll outage affects all employees before salary processing. How should it be handled?","Log and categorise it, set impact and urgency, assign ownership, invoke major-incident escalation, communicate progress, restore service and close with validated resolution notes.","Priority follows impact and urgency; it should not be guessed from emotion."),
  sn("Track 1 - ServiceNow ITSM","Core ITSM Workflows","Request and Service Catalog","A service request asks for a standard product, access or service and is fulfilled through a defined catalog workflow rather than incident restoration.",["Requests versus incidents","Catalog items, variables and approvals","Request, requested item and catalog task lifecycle"],"Build laptop and access-request catalog items.","Design a laptop request that captures model, justification and manager approval.","Create the catalog item and variables, route approval, generate fulfilment tasks and verify the REQ-RITM-SCTASK lifecycle.","Model the user experience first, then approvals and fulfilment."),
  sn("Track 1 - ServiceNow ITSM","Core ITSM Workflows","Problem Management","Problem management identifies and controls the underlying causes of incidents, including documented workarounds and known errors.",["Recurring incidents and root-cause analysis","Known errors and workarounds","Linking incidents, problems and changes"],"Create a problem and document a known error.","Several offices report the same VPN failure every Monday. What records and links are needed?","Relate the recurring incidents to a problem, investigate root cause, record a workaround and known error, and link the permanent corrective change.","A workaround restores productivity; it does not prove the root cause is removed."),
  sn("Track 1 - ServiceNow ITSM","Service Control","Change Management","Change management evaluates and authorises controlled modifications while balancing value, risk and service stability.",["Standard, normal and emergency changes","Risk, approvals, implementation and backout plans","Change Advisory Board and post-implementation review"],"Prepare a complete normal-change record.","A production database upgrade is planned for the weekend. What makes the change implementation-ready?","Document scope, risk, test evidence, approvals, implementation steps, validation, backout plan, schedule, CAB review and post-implementation review.","A change without a testable backout and validation plan is not ready."),
  sn("Track 1 - ServiceNow ITSM","Knowledge and Service Quality","Knowledge Management","Knowledge management turns verified experience into governed, searchable and reusable guidance.",["Knowledge bases and article lifecycle","Authoring, review, publishing and feedback","Turning resolutions into reusable knowledge"],"Publish a troubleshooting article.","Convert a resolved email-sync incident into a reusable support article.","Write clear symptoms, environment, cause, ordered resolution and validation steps; route review, publish to the correct audience and monitor feedback.","Write for the next reader, not for the person who already solved the issue."),
  sn("Track 1 - ServiceNow ITSM","Knowledge and Service Quality","Service Level Management","Service-level management defines measurable commitments and tracks whether response and resolution targets are achieved within agreed schedules.",["SLAs, OLAs and business schedules","Start, pause, stop and breach conditions","Response and resolution reporting"],"Configure and test an incident SLA.","Create a high-priority resolution SLA that pauses while awaiting the caller.","Define the target and schedule, configure start-pause-stop conditions, attach it to matching incidents, test timing and report breaches.","Test lifecycle conditions with a sample record before trusting an SLA report."),
  sn("Track 1 - ServiceNow ITSM","Service Visibility","CMDB and Reporting Fundamentals","The CMDB represents configuration items and their relationships so teams can understand service dependency, impact and operational performance.",["Configuration items, relationships and services","Assets versus configuration items and business impact","Operational reports, dashboards and KPIs"],"Map a small service and create an incident dashboard.","Map an employee portal to its application and database, then show incident health.","Create the service and CI relationships, distinguish owned assets from operational CIs, and build a dashboard with meaningful incident KPIs.","A dashboard should answer an operational question, not simply display available fields."),

  sn("Track 2 - ServiceNow Development","Platform Administration","Users, Roles and Platform Operations","Platform administration establishes the people, navigation, properties, communications and scheduled operations required for a maintainable ServiceNow environment.",["Users, groups, roles and impersonation","Application menus, modules and system properties","Notifications, logs and scheduled activities"],"Create a small support organisation.","Set up a support group with appropriate access, navigation and notifications.","Create users and group membership, assign least-privilege roles, configure modules and properties, test notifications, review logs and validate through impersonation.","Use impersonation to verify the user experience; never assume a role works."),
  sn("Track 2 - ServiceNow Development","Application Design","Data Model, Forms and Lists","A maintainable application starts with a clear data model and then exposes the right fields, views, related information and validation to each user.",["Tables, fields, references and table extension","Forms, views, related lists and UI actions","UI Policies and Data Policies"],"Design the data model for a Training Request application.","Model employees requesting training courses with approvals and status tracking.","Define scoped tables and references, choose appropriate extension, configure forms and related lists, add the required UI action, and enforce UI and server data policies.","Fix the data model before polishing the form."),
  sn("Track 2 - ServiceNow Development","Scripting Foundations","JavaScript for ServiceNow","ServiceNow JavaScript applies standard language fundamentals within client-side and server-side platform execution contexts.",["Variables, conditions, functions, arrays and objects","JSON, dates and error handling","Client-side versus server-side execution"],"Complete short platform-based scripting exercises.","Parse a JSON request, validate a date and return a controlled error for invalid input.","Use clear variables and functions, parse the JSON safely, compare dates in the correct context, catch errors and log only useful diagnostic information.","Know where code runs before choosing an API."),
  sn("Track 2 - ServiceNow Development","Scripting Foundations","Client-side Development","Client-side development guides form behaviour and validation without treating the browser as a trusted security boundary.",["Client Scripts: onLoad, onChange and onSubmit","g_form, UI Policies and validation","GlideAjax for safe server communication"],"Build dynamic form behaviour.","Show a justification field for high-cost requests and validate it before submit.","Use a UI Policy or onChange script for presentation, g_form for controlled interaction, onSubmit for usability validation and GlideAjax when server data is required.","Client validation improves experience; server enforcement protects data."),
  sn("Track 2 - ServiceNow Development","Server Automation","Server-side Development","Server-side logic enforces reusable business behaviour close to platform data and events.",["Business Rules and execution timing","GlideRecord and GlideAggregate","Script Includes, events and scheduled scripts"],"Automate assignment and create reusable logic.","Assign incoming requests by location and calculate open workload per group.","Choose the correct Business Rule timing, query safely with GlideRecord, aggregate workload, place reusable logic in a Script Include, and use events or schedules for decoupled processing.","Avoid database queries inside loops and keep Business Rules focused."),
  sn("Track 2 - ServiceNow Development","Secure Delivery","Security and Access","ServiceNow security combines roles and Access Control Rules to protect tables, records and fields under least-privilege access.",["Roles and Access Control Rules","Table, record and field security","Impersonation and security debugging"],"Protect sensitive data with ACLs.","Only HR case managers may read salary information while employees may read their own non-sensitive case fields.","Define the roles and table-record-field ACLs, avoid relying on client hiding, impersonate representative users and use security debugging to confirm decisions.","Hidden is not secure; enforce access with ACLs."),
  sn("Track 2 - ServiceNow Development","Workflow Automation","Flow Designer and Automation","Flow Designer orchestrates triggers, actions, decisions, approvals and reusable subflows with visible execution evidence and error handling.",["Triggers, actions, conditions and data pills","Approvals, subflows and error handling","Choosing configuration, flow or script"],"Automate an employee onboarding request.","After manager approval, create onboarding tasks for IT, facilities and HR.","Select the request trigger, map data pills, route approval, call reusable subflows, handle failures and verify every branch in execution details.","Choose the simplest maintainable tool that meets the requirement."),
  sn("Track 2 - ServiceNow Development","Data and Integration","Data, Deployment and Integration","Reliable delivery moves data and configuration deliberately and integrates external systems through tested, secure interfaces.",["Import Sets and Transform Maps","Update Sets and deployment discipline","REST APIs, JSON and API testing"],"Import data and create an incident through REST.","Import a user spreadsheet and submit an incident through a tested API request.","Stage and transform the data with coalescing and validation, capture configuration in a clean Update Set, authenticate the REST request, validate JSON and inspect the response and logs.","Test integrations with non-production data and document every dependency."),

  sn("Track 3 - Prompt Engineering","Responsible GenAI","Generative AI Foundations","Generative AI predicts useful language from context but can produce confident errors, so model output requires privacy controls, grounding and human verification.",["How language models work at a practical level","Tokens, context, model choice and limitations","Hallucinations, privacy and responsible use"],"Compare model outputs and identify failure points.","Compare two incident summaries and identify unsupported claims or exposed sensitive information.","Select the grounded summary, remove private data, flag unsupported statements and define a human verification step.","AI output is a draft to be checked, not a decision to be trusted blindly."),
  sn("Track 3 - Prompt Engineering","Prompt Design","Writing Effective Prompts","An effective prompt states the objective, supplies relevant context, defines constraints and requests a testable output format.",["Objective, context, constraints and output format","Zero-shot and few-shot prompting","Examples, delimiters and reusable templates"],"Improve weak prompts using a consistent framework.","Rewrite 'summarise this ticket' for a customer-safe incident update.","Specify audience and goal, delimit the ticket evidence, forbid invented facts, provide an example if useful and require a structured update with status, impact and next step.","If success cannot be evaluated, the prompt is not finished."),
  sn("Track 3 - Prompt Engineering","Reliable AI Delivery","Reliable AI Workflows","Reliable AI workflows decompose complex work, ground each step in supplied evidence, validate structured outputs and improve through measured iteration.",["Prompt decomposition and chaining","Grounding responses in supplied information","Structured output, evaluation and iteration"],"Create and score a repeatable prompt workflow.","Design a workflow that classifies a ticket, drafts a summary and checks it against source evidence.","Create separate grounded steps, pass only required context, require a schema, define a scoring rubric, test edge cases and iterate from recorded failures.","Evaluate the workflow, not just one impressive response."),
  sn("Track 3 - Prompt Engineering","AI for Service Operations","AI for ServiceNow and ITSM","AI can accelerate service operations and development support when outputs stay grounded, private, reviewable and subordinate to accountable human decisions.",["Incident summaries and customer updates","Knowledge articles and change-risk summaries","User stories, test cases and script explanation"],"Build an AI-assisted service-desk toolkit.","Create reusable prompts for classification, communication, resolution notes and knowledge drafting.","Build templates with source delimiters, privacy constraints, structured outputs and verification checklists for each use case, then test them against representative tickets.","Never let generated text silently become an operational decision."),

  sn("Track 4 - Capstone Projects","Portfolio Project","ITSM Case Study","This capstone demonstrates end-to-end service-management judgment across related operational records and measurable outcomes.",["Manage an incident","Identify a recurring problem and raise a change","Publish knowledge and present SLA results"],"Complete and present the ITSM case study with record evidence.","A recurring business-service outage must be restored, investigated and permanently corrected.","Deliver linked incident, problem, known-error, change and knowledge records plus an SLA results presentation.","Tell one connected service story rather than presenting isolated screenshots.",60),
  sn("Track 4 - Capstone Projects","Portfolio Project","ServiceNow Application","This capstone proves the learner can design, secure, automate, test and package a maintainable scoped application.",["Tables, forms and scripts","Security, approvals and notifications","Reports and deployment packaging"],"Build a scoped request application.","Build a Training Request application from data model through deployment package.","Deliver working tables, forms, scripts, ACLs, approval flow, notifications, reports, test evidence and a clean deployment package.","Demonstrate security and failure handling, not only the happy path.",90),
  sn("Track 4 - Capstone Projects","Portfolio Project","AI-assisted Service Desk","This capstone demonstrates a tested and responsible prompt toolkit for real service-desk work.",["Classification and summarisation","Customer communication and resolution notes","Knowledge generation with evaluation"],"Create and test the AI-assisted service-desk prompt portfolio.","Build prompts that operate only on supplied ticket evidence and produce reviewable outputs.","Deliver versioned prompts, representative test cases, scoring results and templates for classification, summaries, updates, resolution notes and knowledge drafts.","Show failed tests and improvements; reliability evidence is part of the project.",60),

  sn("Track 5 - Assessment & Career Readiness","Assessment Model","How You Will Be Assessed","Assessment rewards consistent knowledge, hands-on execution, integrated projects and a final demonstration.",["Weekly quizzes - 15%","Hands-on labs - 30%","ITSM case study - 15%","ServiceNow application - 25%","AI project - 10%","Final demonstration - 5%"],"Build an evidence tracker for every assessed component.","A learner has strong quiz scores but incomplete labs. Where should effort be focused?","Prioritise hands-on labs and application evidence because practical work carries the largest combined weighting.","Track evidence weekly; do not wait until the final demonstration.",20),
  sn("Track 5 - Assessment & Career Readiness","Program Completion","Career-ready Outcomes","Completion means the learner can explain, configure, build, automate, integrate, verify and present practical ServiceNow and responsible GenAI work.",["Explain and execute core ITSM workflows with confidence","Navigate and administer a ServiceNow instance","Configure tables, forms, lists, roles, notifications and reports","Build client-side and server-side platform logic","Create approval flows and automate service processes","Move configuration safely using Update Sets","Import data and work with REST integrations","Use generative AI for service operations without ignoring privacy or verification","Present three practical projects during interviews"],"Prepare a final portfolio demonstration using the three capstones.","Structure a concise interview demonstration of the program outcomes.","Present the service problem, design decisions, secure implementation, test evidence, measurable outcome and lessons learned across all three projects.","Show proof of capability: working records, tests, reports and explainable decisions.",30),
];
