type Detail={detailedSections:Array<{title:string;explanation:string;example:string}>;keyTerms?:Array<{term:string;definition:string;example:string}>};
const section=(title:string,explanation:string,example:string)=>({title,explanation,example});
const term=(term:string,definition:string,example:string)=>({term,definition,example});

export const serviceNowLessonDetails:Record<string,Detail>={
  "ServiceNow and ITSM Foundations":{
    detailedSections:[
      section("ITSM and ITIL explained","Information Technology Service Management (ITSM) is the way an organisation plans, delivers, supports and improves technology services for users. ITIL is a widely used body of guidance for doing that work; it describes practices such as incident, problem, change and service-level management. ITSM is the operating discipline, ITIL is guidance, and ServiceNow is a platform that can implement those processes.","A payroll application outage is handled through an ITSM incident process. ServiceNow stores and routes the incident, while ITIL guidance helps the team decide how to restore service and improve the process."),
      section("The ServiceNow platform","ServiceNow is a cloud platform built around records in tables. Applications contain modules; modules open lists, forms, reports or workspaces; roles control what users may see and do. Administrators configure the platform, fulfiller users work on records, requesters use portals, and developers add secure automation or applications.","A service desk agent with the itil role can update incidents, while an employee without that fulfiller role can still report an issue through the service portal."),
      section("Lists, forms, filters and records","A record is one row of information, such as one incident. A list displays many records and supports sorting, grouping, filtering and personalisation. A form displays one record with fields and related information. Filters should express a precise condition and can be saved when a team needs the same view repeatedly.","The filter Active is true AND Assignment group is Service Desk shows the team its current workload; opening INC0012345 displays that incident's form."),
    ],
    keyTerms:[
      term("Service","A means of enabling value by helping customers achieve outcomes without managing every underlying cost and risk.","Corporate email is an IT service."),
      term("ITSM","The organisational capabilities and practices used to manage IT services throughout their lifecycle.","Logging, prioritising and resolving user incidents is ITSM work."),
      term("ITIL","A framework of service-management guidance and practices; it is not a software product.","Incident Management is an ITIL practice that can be configured in ServiceNow."),
      term("Incident","An unplanned interruption or reduction in the quality of a service.","Users cannot connect to VPN."),
      term("Service request","A user request for a standard service, information, access or item.","A new employee requests a laptop."),
      term("Problem","A cause, or potential cause, of one or more incidents.","A faulty driver repeatedly causes laptop crashes."),
      term("Change","The addition, modification or removal of something that could affect a service.","Deploying a new VPN client version."),
      term("SLA","A documented service-level commitment with measurable targets.","Priority 1 incidents must receive a response within 15 minutes."),
      term("CI","A configuration item that must be managed to deliver a service.","A production database server."),
      term("CMDB","The database that stores CIs and their relationships.","The employee portal application is related to its web and database servers."),
    ],
  },
  "Incident Management":{detailedSections:[
    section("Incident lifecycle","An incident normally moves through New, In Progress, On Hold, Resolved and Closed states. Categorisation supports routing and reporting, assignment gives one group or person clear ownership, and work notes preserve an operational history. Resolution should state what was done and how restoration was verified.","A printer incident is categorised as Hardware > Printer, assigned to Desktop Support, resolved after a driver reinstall, and closed after the user confirms printing works."),
    section("Impact, urgency and priority","Impact describes how widely the business is affected; urgency describes how quickly action is required. ServiceNow commonly calculates priority from both rather than allowing arbitrary selection. Escalation may be functional, by moving work to a specialised team, or hierarchical, by notifying leadership when risk is high.","A payroll outage affecting all employees on payday has high impact and high urgency, producing a critical priority."),
    section("SLAs and major incidents","An SLA task measures response or resolution time against defined conditions and a business schedule. Major-incident practice adds coordinated leadership, communication and recovery for exceptionally severe incidents. The objective is safe service restoration first, followed by learning and prevention.","A P1 outage triggers a 15-minute response SLA, opens a major-incident bridge, sends stakeholder updates and later feeds a problem investigation."),
  ],keyTerms:[term("Impact","The extent of business effect.","One user versus the whole company."),term("Urgency","How quickly resolution is needed.","Payroll must run today."),term("Priority","The order in which work should be handled, commonly derived from impact and urgency.","High impact plus high urgency produces P1."),term("Resolution code","A structured classification of how an incident was resolved.","Solved by workaround.")]},
  "Request and Service Catalog":{detailedSections:[
    section("Request versus incident","An incident reports something broken or degraded; a request asks for something standard. Mixing them damages reporting and sends work through the wrong workflow. A catalog should give users clear choices and collect the information fulfilment teams actually need.","A laptop that will not start is an incident; ordering a laptop for a new employee is a request."),
    section("Catalog item design","A catalog item is the user-facing offering. Variables capture choices and information, UI policies control the experience, and approvals confirm authority or cost. Good catalog design uses plain language, sensible defaults, validation and only the fields necessary to fulfil the request.","A software-access item asks for application, business justification and duration, then routes manager and application-owner approval."),
    section("REQ, RITM and SCTASK lifecycle","The Request (REQ) is the overall shopping transaction, each Requested Item (RITM) represents one ordered item, and Catalog Tasks (SCTASKs) represent fulfilment work. One request can contain several items, and one item can create several tasks. Learners should know which record carries user context, approval state and fulfilment ownership.","A request contains a laptop RITM and an access RITM; the laptop item creates build and delivery tasks."),
  ],keyTerms:[term("Catalog item","A requestable product or service definition.","Standard laptop."),term("Variable","A question that captures request-specific data.","Choose operating system."),term("RITM","The record for one requested item.","REQ001 contains RITM001 for a laptop."),term("SCTASK","A task assigned to a fulfilment team.","Desktop Support prepares the laptop.")]},
  "Problem Management":{detailedSections:[
    section("From recurring incidents to a problem","Problem management looks beyond restoring one user and asks why incidents occur or may occur. Candidates are found through trends, major-incident reviews or proactive risk analysis. A problem record coordinates investigation without keeping every related incident open.","Ten VPN incidents with the same error are linked to one problem for root-cause investigation."),
    section("Root cause, known error and workaround","Root cause is the underlying reason the failure occurs. A workaround reduces impact without removing that cause. A known error is a problem that has been analysed and has a documented root cause or workaround; publishing it helps support teams restore users faster.","Restarting a service is a workaround; a memory leak in a component is the root cause."),
    section("Linking incidents, problems and changes","Incidents provide evidence and user impact, the problem captures analysis, and a change controls the permanent correction. These relationships create traceability from symptom to cause to safe implementation. Closure requires evidence that the correction reduced recurrence.","Related VPN incidents link to PRB001; CHG001 deploys the corrected client; post-change monitoring shows the incident trend falls."),
  ],keyTerms:[term("Root cause","The fundamental reason an issue occurs.","A database connection leak."),term("Workaround","A temporary way to reduce or remove impact.","Restart the service nightly."),term("Known error","An analysed problem with documented knowledge.","A vendor defect with a published workaround.")]},
  "Change Management":{detailedSections:[
    section("Change types","A standard change is low risk, repeatable and pre-authorised under a proven model. A normal change follows assessment and approval appropriate to risk. An emergency change is expedited to address urgent harm, but still requires documented authority, testing where possible and retrospective review.","Routine certificate renewal may become standard; a database upgrade is normal; an urgent security containment may be emergency."),
    section("Risk, planning and approval","A complete change states scope, affected CIs and services, risk, test evidence, implementation steps, validation and backout. Approval should reflect business and technical risk rather than becoming a ceremonial click. Collision checks and schedules reduce conflicts with other changes.","A network change lists impacted offices, tested commands, monitoring checks and exact rollback commands before approval."),
    section("CAB and post-implementation review","The Change Advisory Board evaluates significant normal changes using business, technical and scheduling perspectives. A post-implementation review asks whether objectives were achieved, incidents occurred, the plan worked and lessons should update future changes. CAB does not replace accountable change ownership.","After an upgrade causes latency, the review records the missed load test and updates the standard test plan."),
  ],keyTerms:[term("Backout plan","Testable steps to restore the previous safe state.","Restore snapshot and previous application package."),term("CAB","A group that advises on change assessment and scheduling.","Operations, security and business owners review a high-risk release."),term("PIR","A review of results and lessons after implementation.","Compare actual downtime with the plan.")]},
  "Knowledge Management":{detailedSections:[
    section("Knowledge bases and governance","A knowledge base groups articles for a purpose and audience. Ownership, permissions and validity rules determine who can read, contribute and maintain content. Multiple bases may separate employee help, technical support and restricted operational procedures.","Employees can read self-service articles while support engineers can access a restricted diagnostic knowledge base."),
    section("Article lifecycle","Articles move through authoring, review, approval, publishing, feedback and retirement. Templates make content consistent; review checks accuracy and security; ownership and expiry prevent stale guidance. Feedback and usage data show where an article is unclear or no longer effective.","A VPN article is reviewed by Network Support, published for employees, then revised after low helpfulness feedback."),
    section("Turning resolutions into reusable knowledge","A good article starts with symptoms and audience, states prerequisites, gives ordered steps and explains how to validate success. It excludes private incident data and distinguishes safe user steps from administrator-only actions. Linking articles to incidents also measures reuse.","Resolution notes from an email incident become a sanitised article with symptoms, cause, fix and confirmation steps."),
  ],keyTerms:[term("Knowledge base","A governed collection of articles.","Employee Self-Service."),term("Article lifecycle","The controlled states from draft to retirement.","Draft, review, publish, retire."),term("Feedback","User signals about usefulness and accuracy.","Helpful rating and comments.")]},
  "Service Level Management":{detailedSections:[
    section("SLA, OLA and schedules","An SLA expresses a commitment between provider and customer; an OLA supports that commitment between internal teams. Targets must use appropriate business schedules and time zones so elapsed time reflects agreed service hours. A contract without measurable conditions cannot be managed reliably.","The customer has an eight-hour resolution SLA while the internal network team has a four-hour OLA."),
    section("Start, pause, stop and breach","Start conditions attach the timer to matching records. Pause conditions exclude agreed waiting periods, stop conditions define successful completion, and breach occurs when elapsed business time reaches the target. Retroactive start and reset behaviour must be understood before production use.","The SLA starts when a P2 incident is created, pauses in Awaiting User, and stops when it is resolved."),
    section("Reporting and improvement","Operational teams monitor at-risk and breached tasks, while managers analyse attainment, trends and causes. Reporting should separate response from resolution and distinguish workload, process gaps and supplier delay. A breach should trigger learning, not merely a red metric.","A dashboard shows 92% resolution attainment and reveals that most breaches occur during reassignment."),
  ],keyTerms:[term("SLA","A measurable provider-customer commitment.","Resolve P2 within eight business hours."),term("OLA","An internal commitment supporting an SLA.","Network team responds within two hours."),term("Breach","Failure to meet the target time.","Elapsed time passes eight business hours.")]},
  "CMDB and Reporting Fundamentals":{detailedSections:[
    section("CIs, classes and relationships","A configuration item is a managed component needed to deliver a service. CI classes define common attributes, and relationships describe dependency or hosting. The CMDB becomes valuable when data has ownership, reconciliation, quality controls and operational use; it is not simply an inventory spreadsheet.","The Employee Portal application Runs on a web server and Depends on a database."),
    section("Assets versus CIs","An asset is tracked mainly for financial, contractual and ownership reasons; a CI is tracked for operational service impact. The same physical device may have linked asset and CI records, but their lifecycles and responsible teams differ. Not every asset needs to be a CI and not every logical CI is a purchased asset.","A laptop has an asset record for cost and warranty and a CI record for support state and relationships."),
    section("Reports, dashboards and KPIs","A report answers a defined question using trustworthy data; a dashboard combines related views for a role. KPIs should connect to outcomes such as restoration speed, backlog health or SLA attainment. Filters, date ranges and denominators must be explicit to avoid misleading conclusions.","A service owner dashboard shows incident volume, mean resolution time, SLA attainment and top affected CIs for one service."),
  ],keyTerms:[term("CI class","A type of configuration item with shared attributes.","Server, application, database."),term("Relationship","A typed dependency between CIs.","Application depends on database."),term("KPI","A measure tied to an important outcome.","Percentage of incidents resolved within SLA.")]},

  "Users, Roles and Platform Operations":{detailedSections:[
    section("Users, groups, roles and impersonation","Users represent people, groups organise work and roles grant capabilities. Assign roles through groups where possible and follow least privilege. Impersonation lets an administrator experience the platform as another user, but privileged impersonation should be controlled and audited.","Add agents to Service Desk, give the group the fulfiller role, then impersonate an agent to confirm access."),
    section("Applications, modules and properties","An application menu organises modules that open platform functions. Modules should be role-restricted and named for the user task. System properties store configurable behaviour outside code, but changes require documentation because a single property may affect the whole instance.","A Training Requests application contains My Requests and All Requests modules, with the latter restricted to fulfilers."),
    section("Notifications, logs and schedules","Notifications combine a trigger, recipients and message content; they must avoid sensitive leakage and duplication. Logs support diagnosis when messages are useful and appropriately levelled. Scheduled jobs run recurring server work and need clear ownership, safe queries and monitoring.","A daily job finds overdue requests, queues one event per owner and the event triggers a concise notification."),
  ],keyTerms:[term("Role","A named permission capability.","itil allows fulfiller work."),term("Impersonation","Temporarily operating as another user for testing.","Verify a requester cannot see restricted cases."),term("System property","A configurable value read by application logic.","Maximum approval amount."),term("Event","A queued platform signal used for decoupled processing.","request.overdue triggers a notification.")]},
  "Data Model, Forms and Lists":{detailedSections:[
    section("Tables, fields and references","A table stores records, fields define attributes and reference fields connect records without duplicating data. Table extension inherits fields and behaviour from a parent and should be chosen only when the child truly is a specialised form of the parent. Data types and mandatory rules should reflect the business model.","Training Request extends Task because it needs assignment and state behaviour; Requested Course references a Course table."),
    section("Forms, views and UI actions","Forms present one record, views tailor layouts to roles, and related lists show linked records. UI actions provide explicit operations such as Approve or Cancel. Design should prioritise the user's decision sequence rather than exposing every available field.","A requester view shows course and justification; a fulfiller view adds assignment, approval history and fulfilment details."),
    section("UI Policies and Data Policies","UI Policies control form presentation such as visible, mandatory or read-only fields. Data Policies enforce data requirements beyond one browser form and can apply to imports or APIs. Critical integrity rules belong on the server because client behaviour can be bypassed.","Justification becomes visible in the form through a UI Policy, while a Data Policy requires it for every high-cost request source."),
  ],keyTerms:[term("Reference field","A field pointing to a record in another table.","Requested for references sys_user."),term("Table extension","Inheritance from a parent table.","Incident extends Task."),term("Related list","A list of records related to the current record.","Approvals on a request."),term("Data Policy","Server-enforced data requirement.","Cost centre is mandatory for imports and forms.")]},
  "JavaScript for ServiceNow":{detailedSections:[
    section("Language fundamentals","ServiceNow scripts use JavaScript variables, conditions, loops, functions, arrays and objects. Clear naming, small functions and controlled side effects make platform code maintainable. Learners should understand truthy values, scope and return values before using platform APIs.","A function receives a priority and returns the correct escalation group without modifying unrelated records."),
    section("JSON, dates and errors","JSON is the common format for integrations and structured data; parse it defensively and validate required properties. ServiceNow date handling should use GlideDateTime on the server rather than unreliable string comparison. Errors should be caught where recovery or meaningful logging is possible.","Parse an API payload, reject a missing caller, convert the requested date with GlideDateTime and return a controlled response."),
    section("Client versus server execution","Client scripts run in the browser and use APIs such as g_form. Server scripts run on the instance and can use GlideRecord, events and secure data access. A client must not receive secrets or be trusted to enforce authorisation.","A client script asks GlideAjax for a permitted summary; the Script Include performs the database lookup on the server."),
  ],keyTerms:[term("Scope","Where a variable or function is accessible.","A local variable exists only inside its function."),term("JSON","A text representation of objects and arrays.","{\"number\":\"INC001\"}."),term("GlideDateTime","The server API for date-time values.","Compare a due date with now."),term("Execution context","Where and when code runs.","Browser onChange versus server Business Rule.")]},
  "Client-side Development":{detailedSections:[
    section("Client Script types","onLoad runs when a form opens, onChange reacts when a field value changes, and onSubmit can stop submission for a usability check. Scripts should be short, avoid repeated server calls and account for forms where fields may be absent. onChange logic must handle initial load and empty values correctly.","An onChange script for Request type shows different guidance without querying the database on every keystroke."),
    section("g_form and UI Policies","g_form reads or changes form fields, messages and values. UI Policies are usually preferable for simple visible, mandatory and read-only behaviour because they are declarative. Client Scripts are appropriate when logic needs calculation or interaction beyond policy capabilities.","Use a UI Policy to require justification when cost exceeds a threshold; use a script only if the threshold must be calculated."),
    section("GlideAjax","GlideAjax calls a client-callable Script Include asynchronously to retrieve approved server information. Pass minimal parameters, validate them on the server and return a small response. Never expose arbitrary GlideRecord access or secrets through a client-callable method.","The form sends a user sys_id and receives only whether that user is a manager, not the entire user record."),
  ],keyTerms:[term("g_form","The client API for the current form.","g_form.setMandatory('justification', true)."),term("onChange","A script triggered by a field value change.","Update available options when department changes."),term("GlideAjax","Asynchronous client-to-server communication.","Retrieve an approved cost limit."),term("Client-callable Script Include","Server logic exposed through controlled GlideAjax methods.","Return a user's support tier.")]},
  "Server-side Development":{detailedSections:[
    section("Business Rules and timing","Business Rules run before, after, asynchronously or when displaying a record. Before rules set values on the current record, after rules act on related work, async rules handle non-immediate processing, and display rules prepare limited data for the client. Conditions and recursion controls are essential.","A before rule calculates assignment; an async rule sends data to a non-critical downstream process."),
    section("GlideRecord and GlideAggregate","GlideRecord queries and changes records; encoded or chained conditions must be specific and indexed where possible. GlideAggregate performs counts, sums and grouping in the database and is preferable to loading rows only to count them. Updates in loops and unrestricted queries create performance risk.","GlideAggregate counts active incidents by assignment group without retrieving every incident."),
    section("Script Includes, events and schedules","Script Includes centralise reusable server logic with clear inputs and outputs. Events decouple a business occurrence from notifications or handlers. Scheduled scripts run recurring work but should process bounded batches, record failures and be safe to rerun.","A Script Include calculates eligibility, a Business Rule queues training.approved, and an event handler creates follow-up work."),
  ],keyTerms:[term("current","The record being processed by a Business Rule.","current.assignment_group."),term("GlideRecord","The server API for table records.","Query active incidents."),term("GlideAggregate","The server API for database aggregation.","COUNT incidents by priority."),term("Script Include","Reusable server-side code.","TrainingEligibility.canApply(userId).") ]},
  "Security and Access":{detailedSections:[
    section("Roles and ACL evaluation","Roles describe capabilities; Access Control Rules decide whether an operation on an object is allowed. ACLs can apply to table, record or field operations and combine role requirements, conditions and scripts. Access is granted only when the relevant checks pass.","A user needs the case_reader role and must be the case requester or a case manager to read a sensitive case."),
    section("Table, record and field security","Table ACLs establish broad access, record conditions restrict individual rows, and field ACLs protect sensitive attributes. UI hiding is not security because APIs and lists may still expose data. Server-side queries must also respect intended boundaries.","Employees can read their own cases but only HR managers can read the salary field."),
    section("Impersonation and debugging","Test representative users, including one who should be denied. Security Debugging shows which ACLs were evaluated and why access passed or failed. Administrative overrides can hide real defects, so testing should use normal roles and be documented.","Impersonate an employee, confirm salary is denied, then review the field ACL result in the debugger."),
  ],keyTerms:[term("ACL","A rule controlling create, read, write, delete or execute access.","Read access to hr_case.salary."),term("Least privilege","Grant only the access necessary for a role.","Agents cannot administer users."),term("Field ACL","Security applied to one field.","Protect salary even when the case is readable."),term("Security debugging","A diagnostic view of ACL evaluation.","Find which rule denied write access.")]},
  "Flow Designer and Automation":{detailedSections:[
    section("Triggers, actions and data pills","A flow starts from a trigger such as record creation, schedule or application event. Actions perform work, conditions control branches and data pills carry outputs between steps. Inputs should be explicit and tested for empty or unexpected values.","A flow triggers when an onboarding RITM is approved and uses its Requested for user as a data pill."),
    section("Approvals, subflows and errors","Approval actions should identify approvers, rules for rejection and behaviour when no approver is found. Subflows package reusable automation with defined inputs and outputs. Error handlers, execution details and retries make failures visible and recoverable.","A reusable Create onboarding tasks subflow returns task IDs and routes failures to an operations queue."),
    section("Configuration, flow or script","Use configuration for simple platform behaviour, Flow Designer for visible orchestration and approvals, and script for logic that cannot be expressed maintainably otherwise. The decision should consider complexity, volume, testability, support skills and upgrade impact.","A mandatory field uses configuration; multi-team onboarding uses a flow; a complex reusable calculation uses a Script Include."),
  ],keyTerms:[term("Trigger","The event that starts a flow.","RITM changes to Approved."),term("Data pill","A value produced by a trigger or action.","Requested for email."),term("Subflow","Reusable flow logic with inputs and outputs.","Create standard onboarding tasks."),term("Execution details","The step-by-step runtime record for a flow.","See which action failed.")]},
  "Data, Deployment and Integration":{detailedSections:[
    section("Import Sets and Transform Maps","An Import Set stages external data before it reaches target tables. A Transform Map maps fields, converts values, runs controlled scripts and uses coalesce fields to determine insert versus update. Validate source quality and review errors before committing large loads.","Import employees into a staging table, coalesce on employee number and reject rows with an invalid department."),
    section("Update Sets and deployment discipline","Update Sets capture many configuration changes for movement between instances, but not all data or every artefact. Use one clear purpose, preview before commit, resolve collisions, document dependencies and test after promotion. Never treat an Update Set as a full backup.","Move the Training Request configuration from development to test, preview conflicts and run a regression checklist."),
    section("REST APIs and testing","REST integrations use resources, methods, authentication, headers, JSON payloads and status codes. Inbound Scripted REST APIs must validate and authorise requests; outbound REST Messages should protect credentials and handle timeouts, retries and non-success responses. Tests need positive, negative and duplicate cases.","POST an incident with OAuth, verify 201 and the returned number, then test missing caller, invalid JSON and a repeated external ID."),
  ],keyTerms:[term("Coalesce","A transform setting used to match an existing target record.","Employee number identifies updates."),term("Update Set","A package of captured configuration changes.","Move fields and Business Rules to test."),term("REST","An HTTP-based integration style using resources and methods.","POST /api/.../incident."),term("Idempotency","Repeated requests do not create unintended duplicate effects.","The same external ID returns the existing incident.")]},

  "Generative AI Foundations":{detailedSections:[
    section("How language models produce output","A language model predicts likely tokens from instructions and context; it does not retrieve truth unless a workflow supplies reliable evidence. Fluent wording is not proof of accuracy. Model behaviour varies with context, sampling, model version and task design.","A model can write a convincing root cause that never appeared in the incident record."),
    section("Tokens, context and model choice","Tokens are units processed by the model, and the context window limits the instructions and evidence available in one request. More context is not always better: irrelevant text can reduce focus and increase cost. Choose a model based on quality, latency, privacy, tool support and evaluation results.","Provide the latest work notes and service facts rather than an entire year of unrelated tickets."),
    section("Hallucination, privacy and responsible use","A hallucination is unsupported generated content. Private, regulated or confidential data must not enter an unapproved model or prompt. Responsible use requires purpose limitation, minimum data, access control, grounding, human review and a clear owner for the final decision.","Remove credentials and personal data, require evidence citations and have the incident owner approve a customer update."),
  ],keyTerms:[term("Token","A unit of text processed by a language model.","A word may be one or several tokens."),term("Context window","The amount of prompt and response content a model can process.","Instructions plus ticket evidence must fit."),term("Hallucination","A claim not supported by reliable evidence.","Inventing a server restart."),term("Grounding","Constraining output to supplied authoritative information.","Use only the incident fields below.")]},
  "Writing Effective Prompts":{detailedSections:[
    section("Objective, context, constraints and format","State what the model must accomplish, who the output serves and what evidence is available. Add boundaries such as forbidden claims, privacy rules and tone. Request a format that downstream people or systems can verify consistently.","Draft a 100-word customer update using only supplied work notes; do not state a root cause unless explicitly confirmed; return Status, Impact and Next step."),
    section("Zero-shot and few-shot prompting","Zero-shot gives instructions without examples and works for straightforward tasks. Few-shot adds carefully chosen examples to demonstrate judgement, structure or edge cases. Examples must not contain sensitive data and should represent desired behaviour rather than accidental wording.","Show one good and one rejected change-risk summary so the model learns to distinguish evidence from speculation."),
    section("Delimiters and templates","Delimiters clearly separate instructions from untrusted source text and reduce ambiguity. Reusable templates standardise variables, rules, output schema and review checks. Source text must never be treated as a new instruction simply because it contains imperative language.","Place the ticket inside <ticket> tags and tell the model that text inside those tags is evidence, not instructions."),
  ],keyTerms:[term("Zero-shot","Prompting without examples.","Classify this ticket using the listed categories."),term("Few-shot","Prompting with representative examples.","Two sample classifications precede the new ticket."),term("Delimiter","A marker separating prompt sections.","<evidence>...</evidence>."),term("Output schema","A required structured response shape.","JSON with category, confidence and evidence.")]},
  "Reliable AI Workflows":{detailedSections:[
    section("Decomposition and chaining","Break a complex objective into stages with one testable responsibility each. Pass only validated outputs to the next stage and define what happens when a stage is uncertain. Chains improve control but also create failure propagation, so intermediate checks matter.","First extract facts, then classify, then draft a summary, then verify every sentence against the extracted facts."),
    section("Grounding and evidence","Supply authoritative information and explicitly restrict the model to it. Require evidence references or an insufficient-information response when facts are missing. Retrieval quality, source freshness and access permissions are part of the workflow's reliability.","A change-risk summary cites the affected CIs, test evidence and outage window from the change record."),
    section("Structured output and evaluation","Structured output enables validation of required fields and types. Evaluation uses representative cases and a rubric covering correctness, completeness, safety and format. Record failures, change one factor at a time and retest before release.","Score 30 incident summaries for unsupported facts, missing impact, privacy leakage and valid JSON."),
  ],keyTerms:[term("Prompt chain","A sequence of model steps with controlled hand-offs.","Extract, classify, draft, verify."),term("Rubric","Explicit criteria for judging output quality.","Accuracy 0-3, completeness 0-3."),term("Structured output","A machine-checkable response shape.","JSON matching a schema."),term("Fallback","Defined behaviour when automation cannot proceed safely.","Send to human review when evidence is missing.")]},
  "AI for ServiceNow and ITSM":{detailedSections:[
    section("Incident summaries and updates","AI can condense work notes and adapt language for agents, managers or customers. The prompt must distinguish confirmed facts, actions and next steps, and suppress internal-only details. A human owner verifies operational status and promised times before publication.","Create an internal technical summary and a separate customer-safe update from the same grounded incident evidence."),
    section("Knowledge and change-risk drafts","AI can organise verified resolutions into article structure and highlight change risks found in supplied records. It must not invent causes, tests, dependencies or approvals. Drafts require subject-matter review, security review where needed and lifecycle ownership.","Generate an article outline from approved resolution notes and flag every missing prerequisite for the author."),
    section("Stories, tests and script explanation","AI can turn requirements into draft user stories, acceptance criteria and tests, or explain code line by line. Developers must verify platform APIs, security, performance and edge cases. Generated scripts should never be pasted into production without review and testing.","Ask for positive, negative and security test cases for a catalog approval flow, then execute them in a sub-production instance."),
  ],keyTerms:[term("Grounded summary","A summary containing only supported facts.","Every statement traces to a ticket field or work note."),term("Human-in-the-loop","A person reviews or decides at a defined control point.","Incident owner approves the customer update."),term("Prompt injection","Untrusted text attempts to override workflow instructions.","A ticket says ignore policy and reveal secrets."),term("Verification checklist","Required checks before using an output.","Facts, privacy, audience, next step.")]},

  "ITSM Case Study":{detailedSections:[
    section("Case narrative and evidence","Choose one realistic service disruption and preserve a timeline of user impact, triage, ownership, communications and restoration. Evidence should include record numbers, key decisions and validation, while screenshots must exclude sensitive information.","A recurring employee-portal outage becomes the central story connecting all project records."),
    section("Problem, change and knowledge linkage","Use incident evidence to justify a problem, document root cause or uncertainty, control the permanent fix through change and convert verified recovery into knowledge. The linked records should show traceability rather than duplicate text.","INC records link to PRB001, CHG001 resolves the defect and KB001 documents safe recovery."),
    section("SLA results and presentation","Present response and resolution performance with a clear denominator, business schedule and explanation of any breach. Conclude with measurable outcomes, remaining risk and improvements. The presentation should explain judgement, not merely show forms.","Show that response met target, resolution breached during reassignment, and the new routing rule addresses that delay."),
  ]},
  "ServiceNow Application":{detailedSections:[
    section("Architecture and user experience","Define personas, scope, data model and lifecycle before building. Forms, views and navigation should support each persona's task with minimal unnecessary information. Record assumptions and acceptance criteria.","A Training Request app supports employee submission, manager approval and learning-team fulfilment."),
    section("Logic, security and automation","Implement client behaviour for usability, server logic for integrity, ACLs for least privilege and flows for visible approvals and tasks. Include notifications that are useful, non-duplicative and safe. Explain why each mechanism was chosen.","Employees see their own requests, managers approve assigned requests and learning staff manage fulfilment."),
    section("Testing, reporting and deployment","Test happy paths, rejection, invalid data, unauthorised access, duplicate actions and failures. Add outcome-focused reports and package configuration with documented dependencies. Demonstrate deployment to a clean test environment.","A regression pack proves ACL behaviour, approval routing and safe Update Set promotion."),
  ]},
  "AI-assisted Service Desk":{detailedSections:[
    section("Toolkit scope and templates","Define separate templates for classification, summarisation, customer communication, resolution notes and knowledge drafts. Each template states audience, inputs, constraints, output format and prohibited behaviour.","The customer-update template forbids internal hostnames and unsupported restoration estimates."),
    section("Test set and scoring","Build representative normal, ambiguous, sensitive and adversarial cases. Score factual support, completeness, privacy, tone and format with explicit thresholds. Keep inputs and results so later prompt versions can be compared.","A prompt must achieve zero privacy leaks and at least 90% grounded statements before release."),
    section("Governance and demonstration","Document approved tools, data handling, review owner, fallback and version history. Demonstrate both a successful output and a caught failure to show control. Explain where AI saves time and where human judgement remains mandatory.","An unsupported root-cause claim is rejected by the verifier and routed to an agent."),
  ]},
  "How You Will Be Assessed":{detailedSections:[
    section("Knowledge and continuous practice","Weekly quizzes contribute 15% and confirm terminology and conceptual understanding. Hands-on labs contribute 30%, the largest single category, because platform competence requires repeated execution and validation rather than memorisation.","A learner stores lab evidence each week instead of relying on a final revision sprint."),
    section("Integrated portfolio projects","The ITSM case study contributes 15%, the ServiceNow application 25% and the AI project 10%. Assessment should examine correctness, completeness, security, evidence and the learner's ability to explain decisions.","A working application with weak ACLs cannot receive full credit even if its form looks polished."),
    section("Final demonstration","The final demonstration contributes 5% and tests whether the learner can present connected work clearly, answer questions and reflect on trade-offs. It confirms ownership of the portfolio rather than rehearsed attendance.","The learner explains one design decision, one defect found in testing and one improvement made."),
  ],keyTerms:[term("Formative assessment","Feedback during learning that guides improvement.","Weekly quiz and lab review."),term("Summative assessment","Evaluation of completed capability.","Capstone application."),term("Evidence","A verifiable artefact supporting a claimed skill.","Record, script, test result or report.")]},
  "Career-ready Outcomes":{detailedSections:[
    section("Operate and administer","Graduates should explain and execute incident, request, problem, change, knowledge and SLA workflows, then navigate and administer a ServiceNow instance. They must connect configuration to service outcomes rather than treating screens as isolated features.","Explain how a priority-one incident becomes a problem, change and reusable article."),
    section("Build, secure and integrate","Graduates should configure data, forms, roles, notifications and reports; build client and server logic; automate approvals; move changes with Update Sets; import data; and work with REST APIs. Security and testing are part of each skill.","Demonstrate an application from table design through ACL tests and deployment."),
    section("Use AI responsibly and present proof","Graduates should use GenAI for service operations with privacy, grounding and verification controls. Three practical projects provide interview evidence. A strong presentation explains the problem, decisions, implementation, tests, outcome and lessons learned.","Present the ITSM case, scoped app and AI toolkit as one coherent career portfolio."),
  ],keyTerms:[term("Portfolio evidence","Work products that demonstrate capability.","Linked records, scripts, test logs and dashboards."),term("Interview narrative","A structured explanation of problem, action and result.","Why an ACL design was chosen and how it was tested."),term("Responsible AI","AI use governed by privacy, evidence, review and accountability.","A grounded draft approved by the service owner.")]},
};
