import { auth } from "@/auth";
import { DashboardShell } from "@/components/dashboard-shell";
import { ReferralShare } from "@/components/sales-challenge/referral-share";
import { prisma } from "@/lib/prisma";
import { headers } from "next/headers";
import { redirect } from "next/navigation";

type Metrics={visits:bigint;registrations:bigint;paid:bigint;revenue:bigint;pending:bigint;refunded:bigint};
export default async function SalesRepDashboard(){
 const session=await auth();if(!session?.user||session.user.role!=="SALES_REP")redirect("/login?callbackUrl=/sales-rep");
 const rep=(await prisma.$queryRaw<Array<{id:string;full_name:string;referral_code:string;status:string}>>`select id,full_name,referral_code,status from public.sales_reps where user_id=${session.user.id}::uuid`)[0];if(!rep||rep.status!=="active")throw new Error("Your Sales Rep access is not active.");
 const metric=(await prisma.$queryRaw<Metrics[]>`select coalesce((select sum(total_visits) from public.sales_referral_attributions where sales_rep_id=${rep.id}::uuid and validity_status='valid'),0)::bigint visits,coalesce((select count(*) from public.sales_referral_attributions where sales_rep_id=${rep.id}::uuid and validity_status='valid' and registered_user_id is not null),0)::bigint registrations,coalesce((select count(*) from public.referral_sales where sales_rep_id=${rep.id}::uuid and status in('confirmed','partially_refunded')),0)::bigint paid,coalesce((select sum(amount_in_paise-refunded_amount_in_paise) from public.referral_sales where sales_rep_id=${rep.id}::uuid and status in('confirmed','partially_refunded')),0)::bigint revenue,coalesce((select count(*) from public.payment_orders o join public.sales_referral_attributions a on a.id=o.sales_attribution_id where a.sales_rep_id=${rep.id}::uuid and o.status in('pending','created','awaiting_payment','pending_verification')),0)::bigint pending,coalesce((select count(*) from public.referral_sales where sales_rep_id=${rep.id}::uuid and status='refunded'),0)::bigint refunded`)[0];
 const sales=await prisma.$queryRaw<Array<{id:string;paid_at:Date;product:string;amount_in_paise:number;refunded_amount_in_paise:number;status:string;customer:string}>>`select sale.id,sale.paid_at,coalesce(product.name,sale.product_type,'Taksh product') product,sale.amount_in_paise,sale.refunded_amount_in_paise,sale.status,'Customer #'||upper(substr(md5(sale.referred_user_id::text),1,4)) customer from public.referral_sales sale left join public.products product on product.id=sale.product_id where sale.sales_rep_id=${rep.id}::uuid order by sale.paid_at desc limit 20`;
 const timeline=await prisma.$queryRaw<Array<{day:Date;revenue:bigint;conversions:bigint}>>`select date_trunc('day',paid_at) day,sum(amount_in_paise-refunded_amount_in_paise)::bigint revenue,count(*) filter(where status<>'refunded')::bigint conversions from public.referral_sales where sales_rep_id=${rep.id}::uuid and paid_at>=now()-interval '30 days' group by 1 order by 1`;
 const h=await headers(),host=h.get("x-forwarded-host")??h.get("host")??"takshai.in",protocol=h.get("x-forwarded-proto")??"https",url=`${protocol}://${host}/r/${rep.referral_code}`;const registrations=Number(metric.registrations),paid=Number(metric.paid),conversion=registrations?paid/registrations*100:0;
 const cards:[[string,string|number],[string,string|number],[string,string|number],[string,string|number],[string,string|number],[string,string|number],[string,string|number]]=[["Link visits",Number(metric.visits).toLocaleString("en-IN")],["Registrations",registrations],["Paid conversions",paid],["Revenue generated",`₹${(Number(metric.revenue)/100).toLocaleString("en-IN")}`],["Conversion rate",`${conversion.toFixed(1)}%`],["Pending payments",Number(metric.pending)],["Refunded sales",Number(metric.refunded)]];
 return <DashboardShell {...session.user}><div className="rounded-2xl border border-zinc-200 bg-[#f8f7f3] p-6 text-zinc-950 sm:p-8"><p className="text-sm font-medium text-violet-700">Sales performance</p><h2 className="mt-2 text-3xl font-semibold">Welcome, {rep.full_name.split(" ")[0]}</h2><p className="mt-2 text-zinc-600">Verified payments only. Metrics automatically account for refunds.</p><section className="mt-7 rounded-xl border border-zinc-200 bg-white p-5"><p className="text-xs uppercase tracking-wider text-zinc-500">Referral code</p><b className="text-xl">{rep.referral_code}</b><div className="mt-4 [&_.field]:border-zinc-300 [&_.field]:bg-zinc-50 [&_.field]:text-zinc-900 [&_.btn-ghost]:border-zinc-300 [&_.btn-ghost]:text-zinc-800"><ReferralShare url={url}/></div><p className="mt-3 text-xs text-zinc-500">First valid referral attribution is protected for 30 days.</p></section><section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label,value])=><article className="rounded-xl border border-zinc-200 bg-white p-5" key={label}><p className="text-sm text-zinc-500">{label}</p><b className="mt-2 block text-2xl">{value}</b></article>)}</section><section className="mt-6 grid gap-5 lg:grid-cols-[2fr_1fr]"><div className="overflow-hidden rounded-xl border border-zinc-200 bg-white"><div className="border-b border-zinc-200 p-5"><h3 className="font-semibold">Recent sales</h3></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-zinc-50 text-zinc-500"><tr><th className="p-4">Date</th><th>Customer</th><th>Product</th><th>Amount</th><th className="pr-4">Status</th></tr></thead><tbody>{sales.map(s=><tr className="border-t border-zinc-100" key={s.id}><td className="p-4">{s.paid_at.toLocaleDateString("en-IN")}</td><td>{s.customer}</td><td>{s.product}</td><td>₹{((s.amount_in_paise-s.refunded_amount_in_paise)/100).toLocaleString("en-IN")}</td><td className="pr-4 capitalize">{s.status.replaceAll("_"," ")}</td></tr>)}</tbody></table>{!sales.length&&<p className="p-5 text-zinc-500">No confirmed sales yet.</p>}</div></div><div className="rounded-xl border border-zinc-200 bg-white p-5"><h3 className="font-semibold">Last 30 days</h3><div className="mt-4 space-y-3">{timeline.map(d=><div className="flex justify-between border-b border-zinc-100 pb-3 text-sm" key={d.day.toISOString()}><span>{d.day.toLocaleDateString("en-IN",{day:"numeric",month:"short"})}</span><span>{Number(d.conversions)} · ₹{(Number(d.revenue)/100).toLocaleString("en-IN")}</span></div>)}{!timeline.length&&<p className="text-sm text-zinc-500">Performance will appear after a verified sale.</p>}</div></div></section></div></DashboardShell>;
}
