"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { LoaderCircle } from "lucide-react";

type Question={id:string;question:string;options:Record<string,string|null>};
type Started={attemptId:string;startedAt:string;durationMinutes:number;questions:Question[]};
type Result={score:number;maxScore:number;percentage:number;passed:boolean};
const format=(seconds:number)=>`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;

export function InstitutionalAttempt({assessmentId}:{assessmentId:string}){
  const[started,setStarted]=useState<Started>();const[answers,setAnswers]=useState<Record<string,string>>({});
  const[result,setResult]=useState<Result>();const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[remaining,setRemaining]=useState(0);const[confirming,setConfirming]=useState(false);
  const autoSubmitted=useRef(false);
  const submit=useCallback(async()=>{if(!started||busy)return;setBusy(true);setError("");try{const response=await fetch(`/api/institutional-assessments/attempts/${started.attemptId}/submit`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({answers:Object.entries(answers).map(([questionId,selectedAnswer])=>({questionId,selectedAnswer}))})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Submission failed.");setResult(payload);setConfirming(false)}catch(caught){setError(caught instanceof Error?caught.message:"Submission failed.")}finally{setBusy(false)}},[answers,busy,started]);
  useEffect(()=>{if(!started||result)return;const deadline=new Date(started.startedAt).getTime()+started.durationMinutes*60000;const update=()=>{const next=Math.max(0,Math.ceil((deadline-Date.now())/1000));setRemaining(next);if(next===0&&!autoSubmitted.current){autoSubmitted.current=true;void submit()}};update();const interval=window.setInterval(update,1000);return()=>window.clearInterval(interval)},[result,started,submit]);
  async function start(){setBusy(true);setError("");try{const response=await fetch(`/api/institutional-assessments/${assessmentId}/start`,{method:"POST"});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Attempt could not start.");setStarted(payload)}catch(caught){setError(caught instanceof Error?caught.message:"Attempt could not start.")}finally{setBusy(false)}}
  if(result)return <div className="rounded-xl border border-emerald-400/20 bg-emerald-500/10 p-4"><b>{result.score}/{result.maxScore} · {result.percentage}%</b><p>{result.passed?"Passed":"Needs improvement"}</p></div>;
  if(!started)return <><button className="btn-primary" disabled={busy} onClick={()=>void start()}>{busy&&<LoaderCircle className="size-4 animate-spin"/>}{busy?"Starting…":"Start attempt"}</button>{error&&<p role="alert" className="mt-3 text-red-300">{error}</p>}</>;
  return <div className="space-y-6"><div className={`sticky top-3 z-20 flex items-center justify-between rounded-xl border p-4 backdrop-blur ${remaining<=300?"border-amber-400/30 bg-amber-950/90":"border-white/10 bg-[#111218]/90"}`}><div><b>{Object.keys(answers).length}/{started.questions.length} answered</b><p className="text-xs text-zinc-400">The attempt submits automatically at zero.</p></div><strong className="text-xl tabular-nums">{format(remaining)}</strong></div>{started.questions.map((question,index)=><fieldset className="rounded-xl border border-white/10 p-4" key={question.id}><legend className="px-2 font-medium">{index+1}. {question.question}</legend>{Object.entries(question.options).filter(([,option])=>option).map(([key,option])=><label className={`mt-2 block cursor-pointer rounded-xl border p-3 ${answers[question.id]===key?"border-violet-400 bg-violet-500/15":"border-white/10"}`} key={key}><input className="mr-2" type="radio" name={question.id} checked={answers[question.id]===key} onChange={()=>setAnswers(current=>({...current,[question.id]:key}))}/>{key}. {option}</label>)}</fieldset>)}<button className="btn-primary" disabled={busy} onClick={()=>setConfirming(true)}>Review and submit</button>{error&&<p role="alert" className="text-red-300">{error}</p>}{confirming&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4" role="dialog" aria-modal="true" aria-labelledby="institutional-submit-title"><div className="w-full max-w-md rounded-2xl border border-white/10 bg-[#111218] p-6"><h3 className="text-xl font-semibold" id="institutional-submit-title">Submit assessment?</h3><p className="mt-2 text-sm text-zinc-400">Answered {Object.keys(answers).length} of {started.questions.length}. This submission is final.</p><div className="mt-6 flex justify-end gap-3"><button className="btn-ghost" disabled={busy} onClick={()=>setConfirming(false)}>Continue reviewing</button><button className="btn-primary" disabled={busy} onClick={()=>void submit()}>{busy?"Submitting…":"Submit now"}</button></div></div></div>}</div>;
}
